name: aya-is

services:
  webclient:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ./webclient/
      target: production-runner
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000
