/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LocaleNewsRouteImport } from './routes/$locale/news'
import { Route as LocaleEventsRouteImport } from './routes/$locale/events'
import { Route as LocaleStoriesRouteRouteImport } from './routes/$locale/stories/route'
import { Route as LocaleElementsRouteRouteImport } from './routes/$locale/elements/route'
import { Route as LocaleSlugRouteRouteImport } from './routes/$locale/$slug/route'
import { Route as LocaleStoriesIndexRouteImport } from './routes/$locale/stories/index'
import { Route as LocaleProductsIndexRouteImport } from './routes/$locale/products/index'
import { Route as LocaleElementsIndexRouteImport } from './routes/$locale/elements/index'
import { Route as LocaleSlugIndexRouteImport } from './routes/$locale/$slug/index'
import { Route as LocaleStoriesStoryslugRouteImport } from './routes/$locale/stories/$storyslug'
import { Route as LocaleAuthCallbackRouteImport } from './routes/$locale/auth/callback'
import { Route as LocaleSlugMembersRouteImport } from './routes/$locale/$slug/members'
import { Route as LocaleSlugContributionsRouteImport } from './routes/$locale/$slug/contributions'
import { Route as LocaleSlugPageslugRouteImport } from './routes/$locale/$slug/$pageslug'
import { Route as LocaleSlugSplatRouteImport } from './routes/$locale/$slug/$'
import { Route as LocaleSlugStoriesRouteRouteImport } from './routes/$locale/$slug/stories/route'
import { Route as LocaleSlugSettingsRouteRouteImport } from './routes/$locale/$slug/settings/route'
import { Route as LocaleSlugStoriesIndexRouteImport } from './routes/$locale/$slug/stories/index'
import { Route as LocaleSlugSettingsIndexRouteImport } from './routes/$locale/$slug/settings/index'
import { Route as LocaleSlugStoriesNewRouteImport } from './routes/$locale/$slug/stories/new'
import { Route as LocaleSlugStoriesStoryslugRouteImport } from './routes/$locale/$slug/stories/$storyslug'
import { Route as LocaleSlugSettingsPagesRouteImport } from './routes/$locale/$slug/settings/pages'
import { Route as LocaleSlugSettingsLinksRouteImport } from './routes/$locale/$slug/settings/links'
import { Route as LocaleSlugPageslugEditRouteImport } from './routes/$locale/$slug/$pageslug/edit'
import { Route as LocaleSlugStoriesStoryslugEditRouteImport } from './routes/$locale/$slug/stories/$storyslug/edit'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleNewsRoute = LocaleNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsRoute = LocaleEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleStoriesRouteRoute = LocaleStoriesRouteRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleElementsRouteRoute = LocaleElementsRouteRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSlugRouteRoute = LocaleSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleStoriesIndexRoute = LocaleStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleStoriesRouteRoute,
} as any)
const LocaleProductsIndexRoute = LocaleProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleElementsIndexRoute = LocaleElementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleElementsRouteRoute,
} as any)
const LocaleSlugIndexRoute = LocaleSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleStoriesStoryslugRoute = LocaleStoriesStoryslugRouteImport.update({
  id: '/$storyslug',
  path: '/$storyslug',
  getParentRoute: () => LocaleStoriesRouteRoute,
} as any)
const LocaleAuthCallbackRoute = LocaleAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSlugMembersRoute = LocaleSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugContributionsRoute = LocaleSlugContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugPageslugRoute = LocaleSlugPageslugRouteImport.update({
  id: '/$pageslug',
  path: '/$pageslug',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugSplatRoute = LocaleSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugStoriesRouteRoute = LocaleSlugStoriesRouteRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugSettingsRouteRoute = LocaleSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugStoriesIndexRoute = LocaleSlugStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugStoriesRouteRoute,
} as any)
const LocaleSlugSettingsIndexRoute = LocaleSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugSettingsRouteRoute,
} as any)
const LocaleSlugStoriesNewRoute = LocaleSlugStoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LocaleSlugStoriesRouteRoute,
} as any)
const LocaleSlugStoriesStoryslugRoute =
  LocaleSlugStoriesStoryslugRouteImport.update({
    id: '/$storyslug',
    path: '/$storyslug',
    getParentRoute: () => LocaleSlugStoriesRouteRoute,
  } as any)
const LocaleSlugSettingsPagesRoute = LocaleSlugSettingsPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => LocaleSlugSettingsRouteRoute,
} as any)
const LocaleSlugSettingsLinksRoute = LocaleSlugSettingsLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => LocaleSlugSettingsRouteRoute,
} as any)
const LocaleSlugPageslugEditRoute = LocaleSlugPageslugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LocaleSlugPageslugRoute,
} as any)
const LocaleSlugStoriesStoryslugEditRoute =
  LocaleSlugStoriesStoryslugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LocaleSlugStoriesStoryslugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$slug': typeof LocaleSlugRouteRouteWithChildren
  '/$locale/elements': typeof LocaleElementsRouteRouteWithChildren
  '/$locale/stories': typeof LocaleStoriesRouteRouteWithChildren
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/news': typeof LocaleNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$slug/settings': typeof LocaleSlugSettingsRouteRouteWithChildren
  '/$locale/$slug/stories': typeof LocaleSlugStoriesRouteRouteWithChildren
  '/$locale/$slug/$': typeof LocaleSlugSplatRoute
  '/$locale/$slug/$pageslug': typeof LocaleSlugPageslugRouteWithChildren
  '/$locale/$slug/contributions': typeof LocaleSlugContributionsRoute
  '/$locale/$slug/members': typeof LocaleSlugMembersRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/stories/$storyslug': typeof LocaleStoriesStoryslugRoute
  '/$locale/$slug/': typeof LocaleSlugIndexRoute
  '/$locale/elements/': typeof LocaleElementsIndexRoute
  '/$locale/products': typeof LocaleProductsIndexRoute
  '/$locale/stories/': typeof LocaleStoriesIndexRoute
  '/$locale/$slug/$pageslug/edit': typeof LocaleSlugPageslugEditRoute
  '/$locale/$slug/settings/links': typeof LocaleSlugSettingsLinksRoute
  '/$locale/$slug/settings/pages': typeof LocaleSlugSettingsPagesRoute
  '/$locale/$slug/stories/$storyslug': typeof LocaleSlugStoriesStoryslugRouteWithChildren
  '/$locale/$slug/stories/new': typeof LocaleSlugStoriesNewRoute
  '/$locale/$slug/settings/': typeof LocaleSlugSettingsIndexRoute
  '/$locale/$slug/stories/': typeof LocaleSlugStoriesIndexRoute
  '/$locale/$slug/stories/$storyslug/edit': typeof LocaleSlugStoriesStoryslugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/news': typeof LocaleNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$slug/$': typeof LocaleSlugSplatRoute
  '/$locale/$slug/$pageslug': typeof LocaleSlugPageslugRouteWithChildren
  '/$locale/$slug/contributions': typeof LocaleSlugContributionsRoute
  '/$locale/$slug/members': typeof LocaleSlugMembersRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/stories/$storyslug': typeof LocaleStoriesStoryslugRoute
  '/$locale/$slug': typeof LocaleSlugIndexRoute
  '/$locale/elements': typeof LocaleElementsIndexRoute
  '/$locale/products': typeof LocaleProductsIndexRoute
  '/$locale/stories': typeof LocaleStoriesIndexRoute
  '/$locale/$slug/$pageslug/edit': typeof LocaleSlugPageslugEditRoute
  '/$locale/$slug/settings/links': typeof LocaleSlugSettingsLinksRoute
  '/$locale/$slug/settings/pages': typeof LocaleSlugSettingsPagesRoute
  '/$locale/$slug/stories/$storyslug': typeof LocaleSlugStoriesStoryslugRouteWithChildren
  '/$locale/$slug/stories/new': typeof LocaleSlugStoriesNewRoute
  '/$locale/$slug/settings': typeof LocaleSlugSettingsIndexRoute
  '/$locale/$slug/stories': typeof LocaleSlugStoriesIndexRoute
  '/$locale/$slug/stories/$storyslug/edit': typeof LocaleSlugStoriesStoryslugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$slug': typeof LocaleSlugRouteRouteWithChildren
  '/$locale/elements': typeof LocaleElementsRouteRouteWithChildren
  '/$locale/stories': typeof LocaleStoriesRouteRouteWithChildren
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/news': typeof LocaleNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$slug/settings': typeof LocaleSlugSettingsRouteRouteWithChildren
  '/$locale/$slug/stories': typeof LocaleSlugStoriesRouteRouteWithChildren
  '/$locale/$slug/$': typeof LocaleSlugSplatRoute
  '/$locale/$slug/$pageslug': typeof LocaleSlugPageslugRouteWithChildren
  '/$locale/$slug/contributions': typeof LocaleSlugContributionsRoute
  '/$locale/$slug/members': typeof LocaleSlugMembersRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/stories/$storyslug': typeof LocaleStoriesStoryslugRoute
  '/$locale/$slug/': typeof LocaleSlugIndexRoute
  '/$locale/elements/': typeof LocaleElementsIndexRoute
  '/$locale/products/': typeof LocaleProductsIndexRoute
  '/$locale/stories/': typeof LocaleStoriesIndexRoute
  '/$locale/$slug/$pageslug/edit': typeof LocaleSlugPageslugEditRoute
  '/$locale/$slug/settings/links': typeof LocaleSlugSettingsLinksRoute
  '/$locale/$slug/settings/pages': typeof LocaleSlugSettingsPagesRoute
  '/$locale/$slug/stories/$storyslug': typeof LocaleSlugStoriesStoryslugRouteWithChildren
  '/$locale/$slug/stories/new': typeof LocaleSlugStoriesNewRoute
  '/$locale/$slug/settings/': typeof LocaleSlugSettingsIndexRoute
  '/$locale/$slug/stories/': typeof LocaleSlugStoriesIndexRoute
  '/$locale/$slug/stories/$storyslug/edit': typeof LocaleSlugStoriesStoryslugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/$slug'
    | '/$locale/elements'
    | '/$locale/stories'
    | '/$locale/events'
    | '/$locale/news'
    | '/auth/callback'
    | '/$locale/'
    | '/$locale/$slug/settings'
    | '/$locale/$slug/stories'
    | '/$locale/$slug/$'
    | '/$locale/$slug/$pageslug'
    | '/$locale/$slug/contributions'
    | '/$locale/$slug/members'
    | '/$locale/auth/callback'
    | '/$locale/stories/$storyslug'
    | '/$locale/$slug/'
    | '/$locale/elements/'
    | '/$locale/products'
    | '/$locale/stories/'
    | '/$locale/$slug/$pageslug/edit'
    | '/$locale/$slug/settings/links'
    | '/$locale/$slug/settings/pages'
    | '/$locale/$slug/stories/$storyslug'
    | '/$locale/$slug/stories/new'
    | '/$locale/$slug/settings/'
    | '/$locale/$slug/stories/'
    | '/$locale/$slug/stories/$storyslug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/events'
    | '/$locale/news'
    | '/auth/callback'
    | '/$locale'
    | '/$locale/$slug/$'
    | '/$locale/$slug/$pageslug'
    | '/$locale/$slug/contributions'
    | '/$locale/$slug/members'
    | '/$locale/auth/callback'
    | '/$locale/stories/$storyslug'
    | '/$locale/$slug'
    | '/$locale/elements'
    | '/$locale/products'
    | '/$locale/stories'
    | '/$locale/$slug/$pageslug/edit'
    | '/$locale/$slug/settings/links'
    | '/$locale/$slug/settings/pages'
    | '/$locale/$slug/stories/$storyslug'
    | '/$locale/$slug/stories/new'
    | '/$locale/$slug/settings'
    | '/$locale/$slug/stories'
    | '/$locale/$slug/stories/$storyslug/edit'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/$slug'
    | '/$locale/elements'
    | '/$locale/stories'
    | '/$locale/events'
    | '/$locale/news'
    | '/auth/callback'
    | '/$locale/'
    | '/$locale/$slug/settings'
    | '/$locale/$slug/stories'
    | '/$locale/$slug/$'
    | '/$locale/$slug/$pageslug'
    | '/$locale/$slug/contributions'
    | '/$locale/$slug/members'
    | '/$locale/auth/callback'
    | '/$locale/stories/$storyslug'
    | '/$locale/$slug/'
    | '/$locale/elements/'
    | '/$locale/products/'
    | '/$locale/stories/'
    | '/$locale/$slug/$pageslug/edit'
    | '/$locale/$slug/settings/links'
    | '/$locale/$slug/settings/pages'
    | '/$locale/$slug/stories/$storyslug'
    | '/$locale/$slug/stories/new'
    | '/$locale/$slug/settings/'
    | '/$locale/$slug/stories/'
    | '/$locale/$slug/stories/$storyslug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/news': {
      id: '/$locale/news'
      path: '/news'
      fullPath: '/$locale/news'
      preLoaderRoute: typeof LocaleNewsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events': {
      id: '/$locale/events'
      path: '/events'
      fullPath: '/$locale/events'
      preLoaderRoute: typeof LocaleEventsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/stories': {
      id: '/$locale/stories'
      path: '/stories'
      fullPath: '/$locale/stories'
      preLoaderRoute: typeof LocaleStoriesRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/elements': {
      id: '/$locale/elements'
      path: '/elements'
      fullPath: '/$locale/elements'
      preLoaderRoute: typeof LocaleElementsRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/stories/': {
      id: '/$locale/stories/'
      path: '/'
      fullPath: '/$locale/stories/'
      preLoaderRoute: typeof LocaleStoriesIndexRouteImport
      parentRoute: typeof LocaleStoriesRouteRoute
    }
    '/$locale/products/': {
      id: '/$locale/products/'
      path: '/products'
      fullPath: '/$locale/products'
      preLoaderRoute: typeof LocaleProductsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/elements/': {
      id: '/$locale/elements/'
      path: '/'
      fullPath: '/$locale/elements/'
      preLoaderRoute: typeof LocaleElementsIndexRouteImport
      parentRoute: typeof LocaleElementsRouteRoute
    }
    '/$locale/$slug/': {
      id: '/$locale/$slug/'
      path: '/'
      fullPath: '/$locale/$slug/'
      preLoaderRoute: typeof LocaleSlugIndexRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/stories/$storyslug': {
      id: '/$locale/stories/$storyslug'
      path: '/$storyslug'
      fullPath: '/$locale/stories/$storyslug'
      preLoaderRoute: typeof LocaleStoriesStoryslugRouteImport
      parentRoute: typeof LocaleStoriesRouteRoute
    }
    '/$locale/auth/callback': {
      id: '/$locale/auth/callback'
      path: '/auth/callback'
      fullPath: '/$locale/auth/callback'
      preLoaderRoute: typeof LocaleAuthCallbackRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$slug/members': {
      id: '/$locale/$slug/members'
      path: '/members'
      fullPath: '/$locale/$slug/members'
      preLoaderRoute: typeof LocaleSlugMembersRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/contributions': {
      id: '/$locale/$slug/contributions'
      path: '/contributions'
      fullPath: '/$locale/$slug/contributions'
      preLoaderRoute: typeof LocaleSlugContributionsRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/$pageslug': {
      id: '/$locale/$slug/$pageslug'
      path: '/$pageslug'
      fullPath: '/$locale/$slug/$pageslug'
      preLoaderRoute: typeof LocaleSlugPageslugRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/$': {
      id: '/$locale/$slug/$'
      path: '/$'
      fullPath: '/$locale/$slug/$'
      preLoaderRoute: typeof LocaleSlugSplatRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/stories': {
      id: '/$locale/$slug/stories'
      path: '/stories'
      fullPath: '/$locale/$slug/stories'
      preLoaderRoute: typeof LocaleSlugStoriesRouteRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/settings': {
      id: '/$locale/$slug/settings'
      path: '/settings'
      fullPath: '/$locale/$slug/settings'
      preLoaderRoute: typeof LocaleSlugSettingsRouteRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/stories/': {
      id: '/$locale/$slug/stories/'
      path: '/'
      fullPath: '/$locale/$slug/stories/'
      preLoaderRoute: typeof LocaleSlugStoriesIndexRouteImport
      parentRoute: typeof LocaleSlugStoriesRouteRoute
    }
    '/$locale/$slug/settings/': {
      id: '/$locale/$slug/settings/'
      path: '/'
      fullPath: '/$locale/$slug/settings/'
      preLoaderRoute: typeof LocaleSlugSettingsIndexRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/stories/new': {
      id: '/$locale/$slug/stories/new'
      path: '/new'
      fullPath: '/$locale/$slug/stories/new'
      preLoaderRoute: typeof LocaleSlugStoriesNewRouteImport
      parentRoute: typeof LocaleSlugStoriesRouteRoute
    }
    '/$locale/$slug/stories/$storyslug': {
      id: '/$locale/$slug/stories/$storyslug'
      path: '/$storyslug'
      fullPath: '/$locale/$slug/stories/$storyslug'
      preLoaderRoute: typeof LocaleSlugStoriesStoryslugRouteImport
      parentRoute: typeof LocaleSlugStoriesRouteRoute
    }
    '/$locale/$slug/settings/pages': {
      id: '/$locale/$slug/settings/pages'
      path: '/pages'
      fullPath: '/$locale/$slug/settings/pages'
      preLoaderRoute: typeof LocaleSlugSettingsPagesRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/settings/links': {
      id: '/$locale/$slug/settings/links'
      path: '/links'
      fullPath: '/$locale/$slug/settings/links'
      preLoaderRoute: typeof LocaleSlugSettingsLinksRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/$pageslug/edit': {
      id: '/$locale/$slug/$pageslug/edit'
      path: '/edit'
      fullPath: '/$locale/$slug/$pageslug/edit'
      preLoaderRoute: typeof LocaleSlugPageslugEditRouteImport
      parentRoute: typeof LocaleSlugPageslugRoute
    }
    '/$locale/$slug/stories/$storyslug/edit': {
      id: '/$locale/$slug/stories/$storyslug/edit'
      path: '/edit'
      fullPath: '/$locale/$slug/stories/$storyslug/edit'
      preLoaderRoute: typeof LocaleSlugStoriesStoryslugEditRouteImport
      parentRoute: typeof LocaleSlugStoriesStoryslugRoute
    }
  }
}

interface LocaleSlugSettingsRouteRouteChildren {
  LocaleSlugSettingsLinksRoute: typeof LocaleSlugSettingsLinksRoute
  LocaleSlugSettingsPagesRoute: typeof LocaleSlugSettingsPagesRoute
  LocaleSlugSettingsIndexRoute: typeof LocaleSlugSettingsIndexRoute
}

const LocaleSlugSettingsRouteRouteChildren: LocaleSlugSettingsRouteRouteChildren =
  {
    LocaleSlugSettingsLinksRoute: LocaleSlugSettingsLinksRoute,
    LocaleSlugSettingsPagesRoute: LocaleSlugSettingsPagesRoute,
    LocaleSlugSettingsIndexRoute: LocaleSlugSettingsIndexRoute,
  }

const LocaleSlugSettingsRouteRouteWithChildren =
  LocaleSlugSettingsRouteRoute._addFileChildren(
    LocaleSlugSettingsRouteRouteChildren,
  )

interface LocaleSlugStoriesStoryslugRouteChildren {
  LocaleSlugStoriesStoryslugEditRoute: typeof LocaleSlugStoriesStoryslugEditRoute
}

const LocaleSlugStoriesStoryslugRouteChildren: LocaleSlugStoriesStoryslugRouteChildren =
  {
    LocaleSlugStoriesStoryslugEditRoute: LocaleSlugStoriesStoryslugEditRoute,
  }

const LocaleSlugStoriesStoryslugRouteWithChildren =
  LocaleSlugStoriesStoryslugRoute._addFileChildren(
    LocaleSlugStoriesStoryslugRouteChildren,
  )

interface LocaleSlugStoriesRouteRouteChildren {
  LocaleSlugStoriesStoryslugRoute: typeof LocaleSlugStoriesStoryslugRouteWithChildren
  LocaleSlugStoriesNewRoute: typeof LocaleSlugStoriesNewRoute
  LocaleSlugStoriesIndexRoute: typeof LocaleSlugStoriesIndexRoute
}

const LocaleSlugStoriesRouteRouteChildren: LocaleSlugStoriesRouteRouteChildren =
  {
    LocaleSlugStoriesStoryslugRoute:
      LocaleSlugStoriesStoryslugRouteWithChildren,
    LocaleSlugStoriesNewRoute: LocaleSlugStoriesNewRoute,
    LocaleSlugStoriesIndexRoute: LocaleSlugStoriesIndexRoute,
  }

const LocaleSlugStoriesRouteRouteWithChildren =
  LocaleSlugStoriesRouteRoute._addFileChildren(
    LocaleSlugStoriesRouteRouteChildren,
  )

interface LocaleSlugPageslugRouteChildren {
  LocaleSlugPageslugEditRoute: typeof LocaleSlugPageslugEditRoute
}

const LocaleSlugPageslugRouteChildren: LocaleSlugPageslugRouteChildren = {
  LocaleSlugPageslugEditRoute: LocaleSlugPageslugEditRoute,
}

const LocaleSlugPageslugRouteWithChildren =
  LocaleSlugPageslugRoute._addFileChildren(LocaleSlugPageslugRouteChildren)

interface LocaleSlugRouteRouteChildren {
  LocaleSlugSettingsRouteRoute: typeof LocaleSlugSettingsRouteRouteWithChildren
  LocaleSlugStoriesRouteRoute: typeof LocaleSlugStoriesRouteRouteWithChildren
  LocaleSlugSplatRoute: typeof LocaleSlugSplatRoute
  LocaleSlugPageslugRoute: typeof LocaleSlugPageslugRouteWithChildren
  LocaleSlugContributionsRoute: typeof LocaleSlugContributionsRoute
  LocaleSlugMembersRoute: typeof LocaleSlugMembersRoute
  LocaleSlugIndexRoute: typeof LocaleSlugIndexRoute
}

const LocaleSlugRouteRouteChildren: LocaleSlugRouteRouteChildren = {
  LocaleSlugSettingsRouteRoute: LocaleSlugSettingsRouteRouteWithChildren,
  LocaleSlugStoriesRouteRoute: LocaleSlugStoriesRouteRouteWithChildren,
  LocaleSlugSplatRoute: LocaleSlugSplatRoute,
  LocaleSlugPageslugRoute: LocaleSlugPageslugRouteWithChildren,
  LocaleSlugContributionsRoute: LocaleSlugContributionsRoute,
  LocaleSlugMembersRoute: LocaleSlugMembersRoute,
  LocaleSlugIndexRoute: LocaleSlugIndexRoute,
}

const LocaleSlugRouteRouteWithChildren = LocaleSlugRouteRoute._addFileChildren(
  LocaleSlugRouteRouteChildren,
)

interface LocaleElementsRouteRouteChildren {
  LocaleElementsIndexRoute: typeof LocaleElementsIndexRoute
}

const LocaleElementsRouteRouteChildren: LocaleElementsRouteRouteChildren = {
  LocaleElementsIndexRoute: LocaleElementsIndexRoute,
}

const LocaleElementsRouteRouteWithChildren =
  LocaleElementsRouteRoute._addFileChildren(LocaleElementsRouteRouteChildren)

interface LocaleStoriesRouteRouteChildren {
  LocaleStoriesStoryslugRoute: typeof LocaleStoriesStoryslugRoute
  LocaleStoriesIndexRoute: typeof LocaleStoriesIndexRoute
}

const LocaleStoriesRouteRouteChildren: LocaleStoriesRouteRouteChildren = {
  LocaleStoriesStoryslugRoute: LocaleStoriesStoryslugRoute,
  LocaleStoriesIndexRoute: LocaleStoriesIndexRoute,
}

const LocaleStoriesRouteRouteWithChildren =
  LocaleStoriesRouteRoute._addFileChildren(LocaleStoriesRouteRouteChildren)

interface LocaleRouteRouteChildren {
  LocaleSlugRouteRoute: typeof LocaleSlugRouteRouteWithChildren
  LocaleElementsRouteRoute: typeof LocaleElementsRouteRouteWithChildren
  LocaleStoriesRouteRoute: typeof LocaleStoriesRouteRouteWithChildren
  LocaleEventsRoute: typeof LocaleEventsRoute
  LocaleNewsRoute: typeof LocaleNewsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAuthCallbackRoute: typeof LocaleAuthCallbackRoute
  LocaleProductsIndexRoute: typeof LocaleProductsIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSlugRouteRoute: LocaleSlugRouteRouteWithChildren,
  LocaleElementsRouteRoute: LocaleElementsRouteRouteWithChildren,
  LocaleStoriesRouteRoute: LocaleStoriesRouteRouteWithChildren,
  LocaleEventsRoute: LocaleEventsRoute,
  LocaleNewsRoute: LocaleNewsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAuthCallbackRoute: LocaleAuthCallbackRoute,
  LocaleProductsIndexRoute: LocaleProductsIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
