/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LocaleNewsRouteImport } from './routes/$locale/news'
import { Route as LocaleEventsRouteImport } from './routes/$locale/events'
import { Route as LocaleStoriesRouteRouteImport } from './routes/$locale/stories/route'
import { Route as LocaleElementsRouteRouteImport } from './routes/$locale/elements/route'
import { Route as LocaleSlugRouteRouteImport } from './routes/$locale/$slug/route'
import { Route as LocaleStoriesIndexRouteImport } from './routes/$locale/stories/index'
import { Route as LocaleSearchIndexRouteImport } from './routes/$locale/search/index'
import { Route as LocaleProductsIndexRouteImport } from './routes/$locale/products/index'
import { Route as LocaleElementsIndexRouteImport } from './routes/$locale/elements/index'
import { Route as LocaleSlugIndexRouteImport } from './routes/$locale/$slug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LocaleStoriesNewRouteImport } from './routes/$locale/stories/new'
import { Route as LocaleAuthCallbackRouteImport } from './routes/$locale/auth/callback'
import { Route as LocaleSlugMembersRouteImport } from './routes/$locale/$slug/members'
import { Route as LocaleSlugContributionsRouteImport } from './routes/$locale/$slug/contributions'
import { Route as LocaleSlugSplatRouteImport } from './routes/$locale/$slug/$'
import { Route as LocaleStoriesStoryslugRouteRouteImport } from './routes/$locale/stories/$storyslug/route'
import { Route as LocaleSlugStoriesRouteRouteImport } from './routes/$locale/$slug/stories/route'
import { Route as LocaleSlugSettingsRouteRouteImport } from './routes/$locale/$slug/settings/route'
import { Route as LocaleSlugPageslugRouteRouteImport } from './routes/$locale/$slug/$pageslug/route'
import { Route as LocaleStoriesStoryslugIndexRouteImport } from './routes/$locale/stories/$storyslug/index'
import { Route as LocaleSlugStoriesIndexRouteImport } from './routes/$locale/$slug/stories/index'
import { Route as LocaleSlugSettingsIndexRouteImport } from './routes/$locale/$slug/settings/index'
import { Route as LocaleSlugPageslugIndexRouteImport } from './routes/$locale/$slug/$pageslug/index'
import { Route as LocaleStoriesStoryslugEditRouteImport } from './routes/$locale/stories/$storyslug/edit'
import { Route as LocaleSlugSettingsStoriesRouteImport } from './routes/$locale/$slug/settings/stories'
import { Route as LocaleSlugSettingsPagesRouteImport } from './routes/$locale/$slug/settings/pages'
import { Route as LocaleSlugSettingsLinksRouteImport } from './routes/$locale/$slug/settings/links'
import { Route as LocaleSlugPageslugEditRouteImport } from './routes/$locale/$slug/$pageslug/edit'
import { Route as LocaleSlugStoriesStoryslugRouteRouteImport } from './routes/$locale/$slug/stories/$storyslug/route'
import { Route as LocaleSlugStoriesStoryslugIndexRouteImport } from './routes/$locale/$slug/stories/$storyslug/index'
import { Route as LocaleSlugSettingsPagesNewRouteImport } from './routes/$locale/$slug/settings/pages/new'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleNewsRoute = LocaleNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsRoute = LocaleEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleStoriesRouteRoute = LocaleStoriesRouteRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleElementsRouteRoute = LocaleElementsRouteRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSlugRouteRoute = LocaleSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleStoriesIndexRoute = LocaleStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleStoriesRouteRoute,
} as any)
const LocaleSearchIndexRoute = LocaleSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleProductsIndexRoute = LocaleProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleElementsIndexRoute = LocaleElementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleElementsRouteRoute,
} as any)
const LocaleSlugIndexRoute = LocaleSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleStoriesNewRoute = LocaleStoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LocaleStoriesRouteRoute,
} as any)
const LocaleAuthCallbackRoute = LocaleAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSlugMembersRoute = LocaleSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugContributionsRoute = LocaleSlugContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugSplatRoute = LocaleSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleStoriesStoryslugRouteRoute =
  LocaleStoriesStoryslugRouteRouteImport.update({
    id: '/$storyslug',
    path: '/$storyslug',
    getParentRoute: () => LocaleStoriesRouteRoute,
  } as any)
const LocaleSlugStoriesRouteRoute = LocaleSlugStoriesRouteRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugSettingsRouteRoute = LocaleSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleSlugPageslugRouteRoute = LocaleSlugPageslugRouteRouteImport.update({
  id: '/$pageslug',
  path: '/$pageslug',
  getParentRoute: () => LocaleSlugRouteRoute,
} as any)
const LocaleStoriesStoryslugIndexRoute =
  LocaleStoriesStoryslugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleStoriesStoryslugRouteRoute,
  } as any)
const LocaleSlugStoriesIndexRoute = LocaleSlugStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugStoriesRouteRoute,
} as any)
const LocaleSlugSettingsIndexRoute = LocaleSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugSettingsRouteRoute,
} as any)
const LocaleSlugPageslugIndexRoute = LocaleSlugPageslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSlugPageslugRouteRoute,
} as any)
const LocaleStoriesStoryslugEditRoute =
  LocaleStoriesStoryslugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LocaleStoriesStoryslugRouteRoute,
  } as any)
const LocaleSlugSettingsStoriesRoute =
  LocaleSlugSettingsStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => LocaleSlugSettingsRouteRoute,
  } as any)
const LocaleSlugSettingsPagesRoute = LocaleSlugSettingsPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => LocaleSlugSettingsRouteRoute,
} as any)
const LocaleSlugSettingsLinksRoute = LocaleSlugSettingsLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => LocaleSlugSettingsRouteRoute,
} as any)
const LocaleSlugPageslugEditRoute = LocaleSlugPageslugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LocaleSlugPageslugRouteRoute,
} as any)
const LocaleSlugStoriesStoryslugRouteRoute =
  LocaleSlugStoriesStoryslugRouteRouteImport.update({
    id: '/$storyslug',
    path: '/$storyslug',
    getParentRoute: () => LocaleSlugStoriesRouteRoute,
  } as any)
const LocaleSlugStoriesStoryslugIndexRoute =
  LocaleSlugStoriesStoryslugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleSlugStoriesStoryslugRouteRoute,
  } as any)
const LocaleSlugSettingsPagesNewRoute =
  LocaleSlugSettingsPagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LocaleSlugSettingsPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$slug': typeof LocaleSlugRouteRouteWithChildren
  '/$locale/elements': typeof LocaleElementsRouteRouteWithChildren
  '/$locale/stories': typeof LocaleStoriesRouteRouteWithChildren
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/news': typeof LocaleNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$slug/$pageslug': typeof LocaleSlugPageslugRouteRouteWithChildren
  '/$locale/$slug/settings': typeof LocaleSlugSettingsRouteRouteWithChildren
  '/$locale/$slug/stories': typeof LocaleSlugStoriesRouteRouteWithChildren
  '/$locale/stories/$storyslug': typeof LocaleStoriesStoryslugRouteRouteWithChildren
  '/$locale/$slug/$': typeof LocaleSlugSplatRoute
  '/$locale/$slug/contributions': typeof LocaleSlugContributionsRoute
  '/$locale/$slug/members': typeof LocaleSlugMembersRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/stories/new': typeof LocaleStoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/$slug/': typeof LocaleSlugIndexRoute
  '/$locale/elements/': typeof LocaleElementsIndexRoute
  '/$locale/products': typeof LocaleProductsIndexRoute
  '/$locale/search': typeof LocaleSearchIndexRoute
  '/$locale/stories/': typeof LocaleStoriesIndexRoute
  '/$locale/$slug/stories/$storyslug': typeof LocaleSlugStoriesStoryslugRouteRouteWithChildren
  '/$locale/$slug/$pageslug/edit': typeof LocaleSlugPageslugEditRoute
  '/$locale/$slug/settings/links': typeof LocaleSlugSettingsLinksRoute
  '/$locale/$slug/settings/pages': typeof LocaleSlugSettingsPagesRouteWithChildren
  '/$locale/$slug/settings/stories': typeof LocaleSlugSettingsStoriesRoute
  '/$locale/stories/$storyslug/edit': typeof LocaleStoriesStoryslugEditRoute
  '/$locale/$slug/$pageslug/': typeof LocaleSlugPageslugIndexRoute
  '/$locale/$slug/settings/': typeof LocaleSlugSettingsIndexRoute
  '/$locale/$slug/stories/': typeof LocaleSlugStoriesIndexRoute
  '/$locale/stories/$storyslug/': typeof LocaleStoriesStoryslugIndexRoute
  '/$locale/$slug/settings/pages/new': typeof LocaleSlugSettingsPagesNewRoute
  '/$locale/$slug/stories/$storyslug/': typeof LocaleSlugStoriesStoryslugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/news': typeof LocaleNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$slug/$': typeof LocaleSlugSplatRoute
  '/$locale/$slug/contributions': typeof LocaleSlugContributionsRoute
  '/$locale/$slug/members': typeof LocaleSlugMembersRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/stories/new': typeof LocaleStoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/$slug': typeof LocaleSlugIndexRoute
  '/$locale/elements': typeof LocaleElementsIndexRoute
  '/$locale/products': typeof LocaleProductsIndexRoute
  '/$locale/search': typeof LocaleSearchIndexRoute
  '/$locale/stories': typeof LocaleStoriesIndexRoute
  '/$locale/$slug/$pageslug/edit': typeof LocaleSlugPageslugEditRoute
  '/$locale/$slug/settings/links': typeof LocaleSlugSettingsLinksRoute
  '/$locale/$slug/settings/pages': typeof LocaleSlugSettingsPagesRouteWithChildren
  '/$locale/$slug/settings/stories': typeof LocaleSlugSettingsStoriesRoute
  '/$locale/stories/$storyslug/edit': typeof LocaleStoriesStoryslugEditRoute
  '/$locale/$slug/$pageslug': typeof LocaleSlugPageslugIndexRoute
  '/$locale/$slug/settings': typeof LocaleSlugSettingsIndexRoute
  '/$locale/$slug/stories': typeof LocaleSlugStoriesIndexRoute
  '/$locale/stories/$storyslug': typeof LocaleStoriesStoryslugIndexRoute
  '/$locale/$slug/settings/pages/new': typeof LocaleSlugSettingsPagesNewRoute
  '/$locale/$slug/stories/$storyslug': typeof LocaleSlugStoriesStoryslugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$slug': typeof LocaleSlugRouteRouteWithChildren
  '/$locale/elements': typeof LocaleElementsRouteRouteWithChildren
  '/$locale/stories': typeof LocaleStoriesRouteRouteWithChildren
  '/$locale/events': typeof LocaleEventsRoute
  '/$locale/news': typeof LocaleNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$slug/$pageslug': typeof LocaleSlugPageslugRouteRouteWithChildren
  '/$locale/$slug/settings': typeof LocaleSlugSettingsRouteRouteWithChildren
  '/$locale/$slug/stories': typeof LocaleSlugStoriesRouteRouteWithChildren
  '/$locale/stories/$storyslug': typeof LocaleStoriesStoryslugRouteRouteWithChildren
  '/$locale/$slug/$': typeof LocaleSlugSplatRoute
  '/$locale/$slug/contributions': typeof LocaleSlugContributionsRoute
  '/$locale/$slug/members': typeof LocaleSlugMembersRoute
  '/$locale/auth/callback': typeof LocaleAuthCallbackRoute
  '/$locale/stories/new': typeof LocaleStoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/$slug/': typeof LocaleSlugIndexRoute
  '/$locale/elements/': typeof LocaleElementsIndexRoute
  '/$locale/products/': typeof LocaleProductsIndexRoute
  '/$locale/search/': typeof LocaleSearchIndexRoute
  '/$locale/stories/': typeof LocaleStoriesIndexRoute
  '/$locale/$slug/stories/$storyslug': typeof LocaleSlugStoriesStoryslugRouteRouteWithChildren
  '/$locale/$slug/$pageslug/edit': typeof LocaleSlugPageslugEditRoute
  '/$locale/$slug/settings/links': typeof LocaleSlugSettingsLinksRoute
  '/$locale/$slug/settings/pages': typeof LocaleSlugSettingsPagesRouteWithChildren
  '/$locale/$slug/settings/stories': typeof LocaleSlugSettingsStoriesRoute
  '/$locale/stories/$storyslug/edit': typeof LocaleStoriesStoryslugEditRoute
  '/$locale/$slug/$pageslug/': typeof LocaleSlugPageslugIndexRoute
  '/$locale/$slug/settings/': typeof LocaleSlugSettingsIndexRoute
  '/$locale/$slug/stories/': typeof LocaleSlugStoriesIndexRoute
  '/$locale/stories/$storyslug/': typeof LocaleStoriesStoryslugIndexRoute
  '/$locale/$slug/settings/pages/new': typeof LocaleSlugSettingsPagesNewRoute
  '/$locale/$slug/stories/$storyslug/': typeof LocaleSlugStoriesStoryslugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/$slug'
    | '/$locale/elements'
    | '/$locale/stories'
    | '/$locale/events'
    | '/$locale/news'
    | '/auth/callback'
    | '/$locale/'
    | '/$locale/$slug/$pageslug'
    | '/$locale/$slug/settings'
    | '/$locale/$slug/stories'
    | '/$locale/stories/$storyslug'
    | '/$locale/$slug/$'
    | '/$locale/$slug/contributions'
    | '/$locale/$slug/members'
    | '/$locale/auth/callback'
    | '/$locale/stories/new'
    | '/api/auth/$'
    | '/$locale/$slug/'
    | '/$locale/elements/'
    | '/$locale/products'
    | '/$locale/search'
    | '/$locale/stories/'
    | '/$locale/$slug/stories/$storyslug'
    | '/$locale/$slug/$pageslug/edit'
    | '/$locale/$slug/settings/links'
    | '/$locale/$slug/settings/pages'
    | '/$locale/$slug/settings/stories'
    | '/$locale/stories/$storyslug/edit'
    | '/$locale/$slug/$pageslug/'
    | '/$locale/$slug/settings/'
    | '/$locale/$slug/stories/'
    | '/$locale/stories/$storyslug/'
    | '/$locale/$slug/settings/pages/new'
    | '/$locale/$slug/stories/$storyslug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/events'
    | '/$locale/news'
    | '/auth/callback'
    | '/$locale'
    | '/$locale/$slug/$'
    | '/$locale/$slug/contributions'
    | '/$locale/$slug/members'
    | '/$locale/auth/callback'
    | '/$locale/stories/new'
    | '/api/auth/$'
    | '/$locale/$slug'
    | '/$locale/elements'
    | '/$locale/products'
    | '/$locale/search'
    | '/$locale/stories'
    | '/$locale/$slug/$pageslug/edit'
    | '/$locale/$slug/settings/links'
    | '/$locale/$slug/settings/pages'
    | '/$locale/$slug/settings/stories'
    | '/$locale/stories/$storyslug/edit'
    | '/$locale/$slug/$pageslug'
    | '/$locale/$slug/settings'
    | '/$locale/$slug/stories'
    | '/$locale/stories/$storyslug'
    | '/$locale/$slug/settings/pages/new'
    | '/$locale/$slug/stories/$storyslug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/$slug'
    | '/$locale/elements'
    | '/$locale/stories'
    | '/$locale/events'
    | '/$locale/news'
    | '/auth/callback'
    | '/$locale/'
    | '/$locale/$slug/$pageslug'
    | '/$locale/$slug/settings'
    | '/$locale/$slug/stories'
    | '/$locale/stories/$storyslug'
    | '/$locale/$slug/$'
    | '/$locale/$slug/contributions'
    | '/$locale/$slug/members'
    | '/$locale/auth/callback'
    | '/$locale/stories/new'
    | '/api/auth/$'
    | '/$locale/$slug/'
    | '/$locale/elements/'
    | '/$locale/products/'
    | '/$locale/search/'
    | '/$locale/stories/'
    | '/$locale/$slug/stories/$storyslug'
    | '/$locale/$slug/$pageslug/edit'
    | '/$locale/$slug/settings/links'
    | '/$locale/$slug/settings/pages'
    | '/$locale/$slug/settings/stories'
    | '/$locale/stories/$storyslug/edit'
    | '/$locale/$slug/$pageslug/'
    | '/$locale/$slug/settings/'
    | '/$locale/$slug/stories/'
    | '/$locale/stories/$storyslug/'
    | '/$locale/$slug/settings/pages/new'
    | '/$locale/$slug/stories/$storyslug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/news': {
      id: '/$locale/news'
      path: '/news'
      fullPath: '/$locale/news'
      preLoaderRoute: typeof LocaleNewsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events': {
      id: '/$locale/events'
      path: '/events'
      fullPath: '/$locale/events'
      preLoaderRoute: typeof LocaleEventsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/stories': {
      id: '/$locale/stories'
      path: '/stories'
      fullPath: '/$locale/stories'
      preLoaderRoute: typeof LocaleStoriesRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/elements': {
      id: '/$locale/elements'
      path: '/elements'
      fullPath: '/$locale/elements'
      preLoaderRoute: typeof LocaleElementsRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/stories/': {
      id: '/$locale/stories/'
      path: '/'
      fullPath: '/$locale/stories/'
      preLoaderRoute: typeof LocaleStoriesIndexRouteImport
      parentRoute: typeof LocaleStoriesRouteRoute
    }
    '/$locale/search/': {
      id: '/$locale/search/'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/products/': {
      id: '/$locale/products/'
      path: '/products'
      fullPath: '/$locale/products'
      preLoaderRoute: typeof LocaleProductsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/elements/': {
      id: '/$locale/elements/'
      path: '/'
      fullPath: '/$locale/elements/'
      preLoaderRoute: typeof LocaleElementsIndexRouteImport
      parentRoute: typeof LocaleElementsRouteRoute
    }
    '/$locale/$slug/': {
      id: '/$locale/$slug/'
      path: '/'
      fullPath: '/$locale/$slug/'
      preLoaderRoute: typeof LocaleSlugIndexRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/stories/new': {
      id: '/$locale/stories/new'
      path: '/new'
      fullPath: '/$locale/stories/new'
      preLoaderRoute: typeof LocaleStoriesNewRouteImport
      parentRoute: typeof LocaleStoriesRouteRoute
    }
    '/$locale/auth/callback': {
      id: '/$locale/auth/callback'
      path: '/auth/callback'
      fullPath: '/$locale/auth/callback'
      preLoaderRoute: typeof LocaleAuthCallbackRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$slug/members': {
      id: '/$locale/$slug/members'
      path: '/members'
      fullPath: '/$locale/$slug/members'
      preLoaderRoute: typeof LocaleSlugMembersRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/contributions': {
      id: '/$locale/$slug/contributions'
      path: '/contributions'
      fullPath: '/$locale/$slug/contributions'
      preLoaderRoute: typeof LocaleSlugContributionsRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/$': {
      id: '/$locale/$slug/$'
      path: '/$'
      fullPath: '/$locale/$slug/$'
      preLoaderRoute: typeof LocaleSlugSplatRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/stories/$storyslug': {
      id: '/$locale/stories/$storyslug'
      path: '/$storyslug'
      fullPath: '/$locale/stories/$storyslug'
      preLoaderRoute: typeof LocaleStoriesStoryslugRouteRouteImport
      parentRoute: typeof LocaleStoriesRouteRoute
    }
    '/$locale/$slug/stories': {
      id: '/$locale/$slug/stories'
      path: '/stories'
      fullPath: '/$locale/$slug/stories'
      preLoaderRoute: typeof LocaleSlugStoriesRouteRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/settings': {
      id: '/$locale/$slug/settings'
      path: '/settings'
      fullPath: '/$locale/$slug/settings'
      preLoaderRoute: typeof LocaleSlugSettingsRouteRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/$slug/$pageslug': {
      id: '/$locale/$slug/$pageslug'
      path: '/$pageslug'
      fullPath: '/$locale/$slug/$pageslug'
      preLoaderRoute: typeof LocaleSlugPageslugRouteRouteImport
      parentRoute: typeof LocaleSlugRouteRoute
    }
    '/$locale/stories/$storyslug/': {
      id: '/$locale/stories/$storyslug/'
      path: '/'
      fullPath: '/$locale/stories/$storyslug/'
      preLoaderRoute: typeof LocaleStoriesStoryslugIndexRouteImport
      parentRoute: typeof LocaleStoriesStoryslugRouteRoute
    }
    '/$locale/$slug/stories/': {
      id: '/$locale/$slug/stories/'
      path: '/'
      fullPath: '/$locale/$slug/stories/'
      preLoaderRoute: typeof LocaleSlugStoriesIndexRouteImport
      parentRoute: typeof LocaleSlugStoriesRouteRoute
    }
    '/$locale/$slug/settings/': {
      id: '/$locale/$slug/settings/'
      path: '/'
      fullPath: '/$locale/$slug/settings/'
      preLoaderRoute: typeof LocaleSlugSettingsIndexRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/$pageslug/': {
      id: '/$locale/$slug/$pageslug/'
      path: '/'
      fullPath: '/$locale/$slug/$pageslug/'
      preLoaderRoute: typeof LocaleSlugPageslugIndexRouteImport
      parentRoute: typeof LocaleSlugPageslugRouteRoute
    }
    '/$locale/stories/$storyslug/edit': {
      id: '/$locale/stories/$storyslug/edit'
      path: '/edit'
      fullPath: '/$locale/stories/$storyslug/edit'
      preLoaderRoute: typeof LocaleStoriesStoryslugEditRouteImport
      parentRoute: typeof LocaleStoriesStoryslugRouteRoute
    }
    '/$locale/$slug/settings/stories': {
      id: '/$locale/$slug/settings/stories'
      path: '/stories'
      fullPath: '/$locale/$slug/settings/stories'
      preLoaderRoute: typeof LocaleSlugSettingsStoriesRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/settings/pages': {
      id: '/$locale/$slug/settings/pages'
      path: '/pages'
      fullPath: '/$locale/$slug/settings/pages'
      preLoaderRoute: typeof LocaleSlugSettingsPagesRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/settings/links': {
      id: '/$locale/$slug/settings/links'
      path: '/links'
      fullPath: '/$locale/$slug/settings/links'
      preLoaderRoute: typeof LocaleSlugSettingsLinksRouteImport
      parentRoute: typeof LocaleSlugSettingsRouteRoute
    }
    '/$locale/$slug/$pageslug/edit': {
      id: '/$locale/$slug/$pageslug/edit'
      path: '/edit'
      fullPath: '/$locale/$slug/$pageslug/edit'
      preLoaderRoute: typeof LocaleSlugPageslugEditRouteImport
      parentRoute: typeof LocaleSlugPageslugRouteRoute
    }
    '/$locale/$slug/stories/$storyslug': {
      id: '/$locale/$slug/stories/$storyslug'
      path: '/$storyslug'
      fullPath: '/$locale/$slug/stories/$storyslug'
      preLoaderRoute: typeof LocaleSlugStoriesStoryslugRouteRouteImport
      parentRoute: typeof LocaleSlugStoriesRouteRoute
    }
    '/$locale/$slug/stories/$storyslug/': {
      id: '/$locale/$slug/stories/$storyslug/'
      path: '/'
      fullPath: '/$locale/$slug/stories/$storyslug/'
      preLoaderRoute: typeof LocaleSlugStoriesStoryslugIndexRouteImport
      parentRoute: typeof LocaleSlugStoriesStoryslugRouteRoute
    }
    '/$locale/$slug/settings/pages/new': {
      id: '/$locale/$slug/settings/pages/new'
      path: '/new'
      fullPath: '/$locale/$slug/settings/pages/new'
      preLoaderRoute: typeof LocaleSlugSettingsPagesNewRouteImport
      parentRoute: typeof LocaleSlugSettingsPagesRoute
    }
  }
}

interface LocaleSlugPageslugRouteRouteChildren {
  LocaleSlugPageslugEditRoute: typeof LocaleSlugPageslugEditRoute
  LocaleSlugPageslugIndexRoute: typeof LocaleSlugPageslugIndexRoute
}

const LocaleSlugPageslugRouteRouteChildren: LocaleSlugPageslugRouteRouteChildren =
  {
    LocaleSlugPageslugEditRoute: LocaleSlugPageslugEditRoute,
    LocaleSlugPageslugIndexRoute: LocaleSlugPageslugIndexRoute,
  }

const LocaleSlugPageslugRouteRouteWithChildren =
  LocaleSlugPageslugRouteRoute._addFileChildren(
    LocaleSlugPageslugRouteRouteChildren,
  )

interface LocaleSlugSettingsPagesRouteChildren {
  LocaleSlugSettingsPagesNewRoute: typeof LocaleSlugSettingsPagesNewRoute
}

const LocaleSlugSettingsPagesRouteChildren: LocaleSlugSettingsPagesRouteChildren =
  {
    LocaleSlugSettingsPagesNewRoute: LocaleSlugSettingsPagesNewRoute,
  }

const LocaleSlugSettingsPagesRouteWithChildren =
  LocaleSlugSettingsPagesRoute._addFileChildren(
    LocaleSlugSettingsPagesRouteChildren,
  )

interface LocaleSlugSettingsRouteRouteChildren {
  LocaleSlugSettingsLinksRoute: typeof LocaleSlugSettingsLinksRoute
  LocaleSlugSettingsPagesRoute: typeof LocaleSlugSettingsPagesRouteWithChildren
  LocaleSlugSettingsStoriesRoute: typeof LocaleSlugSettingsStoriesRoute
  LocaleSlugSettingsIndexRoute: typeof LocaleSlugSettingsIndexRoute
}

const LocaleSlugSettingsRouteRouteChildren: LocaleSlugSettingsRouteRouteChildren =
  {
    LocaleSlugSettingsLinksRoute: LocaleSlugSettingsLinksRoute,
    LocaleSlugSettingsPagesRoute: LocaleSlugSettingsPagesRouteWithChildren,
    LocaleSlugSettingsStoriesRoute: LocaleSlugSettingsStoriesRoute,
    LocaleSlugSettingsIndexRoute: LocaleSlugSettingsIndexRoute,
  }

const LocaleSlugSettingsRouteRouteWithChildren =
  LocaleSlugSettingsRouteRoute._addFileChildren(
    LocaleSlugSettingsRouteRouteChildren,
  )

interface LocaleSlugStoriesStoryslugRouteRouteChildren {
  LocaleSlugStoriesStoryslugIndexRoute: typeof LocaleSlugStoriesStoryslugIndexRoute
}

const LocaleSlugStoriesStoryslugRouteRouteChildren: LocaleSlugStoriesStoryslugRouteRouteChildren =
  {
    LocaleSlugStoriesStoryslugIndexRoute: LocaleSlugStoriesStoryslugIndexRoute,
  }

const LocaleSlugStoriesStoryslugRouteRouteWithChildren =
  LocaleSlugStoriesStoryslugRouteRoute._addFileChildren(
    LocaleSlugStoriesStoryslugRouteRouteChildren,
  )

interface LocaleSlugStoriesRouteRouteChildren {
  LocaleSlugStoriesStoryslugRouteRoute: typeof LocaleSlugStoriesStoryslugRouteRouteWithChildren
  LocaleSlugStoriesIndexRoute: typeof LocaleSlugStoriesIndexRoute
}

const LocaleSlugStoriesRouteRouteChildren: LocaleSlugStoriesRouteRouteChildren =
  {
    LocaleSlugStoriesStoryslugRouteRoute:
      LocaleSlugStoriesStoryslugRouteRouteWithChildren,
    LocaleSlugStoriesIndexRoute: LocaleSlugStoriesIndexRoute,
  }

const LocaleSlugStoriesRouteRouteWithChildren =
  LocaleSlugStoriesRouteRoute._addFileChildren(
    LocaleSlugStoriesRouteRouteChildren,
  )

interface LocaleSlugRouteRouteChildren {
  LocaleSlugPageslugRouteRoute: typeof LocaleSlugPageslugRouteRouteWithChildren
  LocaleSlugSettingsRouteRoute: typeof LocaleSlugSettingsRouteRouteWithChildren
  LocaleSlugStoriesRouteRoute: typeof LocaleSlugStoriesRouteRouteWithChildren
  LocaleSlugSplatRoute: typeof LocaleSlugSplatRoute
  LocaleSlugContributionsRoute: typeof LocaleSlugContributionsRoute
  LocaleSlugMembersRoute: typeof LocaleSlugMembersRoute
  LocaleSlugIndexRoute: typeof LocaleSlugIndexRoute
}

const LocaleSlugRouteRouteChildren: LocaleSlugRouteRouteChildren = {
  LocaleSlugPageslugRouteRoute: LocaleSlugPageslugRouteRouteWithChildren,
  LocaleSlugSettingsRouteRoute: LocaleSlugSettingsRouteRouteWithChildren,
  LocaleSlugStoriesRouteRoute: LocaleSlugStoriesRouteRouteWithChildren,
  LocaleSlugSplatRoute: LocaleSlugSplatRoute,
  LocaleSlugContributionsRoute: LocaleSlugContributionsRoute,
  LocaleSlugMembersRoute: LocaleSlugMembersRoute,
  LocaleSlugIndexRoute: LocaleSlugIndexRoute,
}

const LocaleSlugRouteRouteWithChildren = LocaleSlugRouteRoute._addFileChildren(
  LocaleSlugRouteRouteChildren,
)

interface LocaleElementsRouteRouteChildren {
  LocaleElementsIndexRoute: typeof LocaleElementsIndexRoute
}

const LocaleElementsRouteRouteChildren: LocaleElementsRouteRouteChildren = {
  LocaleElementsIndexRoute: LocaleElementsIndexRoute,
}

const LocaleElementsRouteRouteWithChildren =
  LocaleElementsRouteRoute._addFileChildren(LocaleElementsRouteRouteChildren)

interface LocaleStoriesStoryslugRouteRouteChildren {
  LocaleStoriesStoryslugEditRoute: typeof LocaleStoriesStoryslugEditRoute
  LocaleStoriesStoryslugIndexRoute: typeof LocaleStoriesStoryslugIndexRoute
}

const LocaleStoriesStoryslugRouteRouteChildren: LocaleStoriesStoryslugRouteRouteChildren =
  {
    LocaleStoriesStoryslugEditRoute: LocaleStoriesStoryslugEditRoute,
    LocaleStoriesStoryslugIndexRoute: LocaleStoriesStoryslugIndexRoute,
  }

const LocaleStoriesStoryslugRouteRouteWithChildren =
  LocaleStoriesStoryslugRouteRoute._addFileChildren(
    LocaleStoriesStoryslugRouteRouteChildren,
  )

interface LocaleStoriesRouteRouteChildren {
  LocaleStoriesStoryslugRouteRoute: typeof LocaleStoriesStoryslugRouteRouteWithChildren
  LocaleStoriesNewRoute: typeof LocaleStoriesNewRoute
  LocaleStoriesIndexRoute: typeof LocaleStoriesIndexRoute
}

const LocaleStoriesRouteRouteChildren: LocaleStoriesRouteRouteChildren = {
  LocaleStoriesStoryslugRouteRoute:
    LocaleStoriesStoryslugRouteRouteWithChildren,
  LocaleStoriesNewRoute: LocaleStoriesNewRoute,
  LocaleStoriesIndexRoute: LocaleStoriesIndexRoute,
}

const LocaleStoriesRouteRouteWithChildren =
  LocaleStoriesRouteRoute._addFileChildren(LocaleStoriesRouteRouteChildren)

interface LocaleRouteRouteChildren {
  LocaleSlugRouteRoute: typeof LocaleSlugRouteRouteWithChildren
  LocaleElementsRouteRoute: typeof LocaleElementsRouteRouteWithChildren
  LocaleStoriesRouteRoute: typeof LocaleStoriesRouteRouteWithChildren
  LocaleEventsRoute: typeof LocaleEventsRoute
  LocaleNewsRoute: typeof LocaleNewsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAuthCallbackRoute: typeof LocaleAuthCallbackRoute
  LocaleProductsIndexRoute: typeof LocaleProductsIndexRoute
  LocaleSearchIndexRoute: typeof LocaleSearchIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSlugRouteRoute: LocaleSlugRouteRouteWithChildren,
  LocaleElementsRouteRoute: LocaleElementsRouteRouteWithChildren,
  LocaleStoriesRouteRoute: LocaleStoriesRouteRouteWithChildren,
  LocaleEventsRoute: LocaleEventsRoute,
  LocaleNewsRoute: LocaleNewsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAuthCallbackRoute: LocaleAuthCallbackRoute,
  LocaleProductsIndexRoute: LocaleProductsIndexRoute,
  LocaleSearchIndexRoute: LocaleSearchIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
