name: AYA
options:
  bundleIdPrefix: is.aya
  deploymentTarget:
    iOS: "18.0"
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

packages:
  AYA:
    path: .

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:
  AYA-iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/App/iOS
      - path: Resources/iOS
        buildPhase: resources
    dependencies:
      - package: AYA
        product: AYA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: is.aya.app
        PRODUCT_NAME: AYA
        MARKETING_VERSION: "0.2.1"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_KEY_CFBundleDisplayName: AYA
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_STRICT_CONCURRENCY: complete
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO

  AYA-macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources/App/macOS
      - path: Resources/macOS
        buildPhase: resources
    dependencies:
      - package: AYA
        product: AYA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: is.aya.app.macos
        PRODUCT_NAME: AYA
        MARKETING_VERSION: "0.2.1"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_KEY_CFBundleDisplayName: AYA
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2026 AYA. MIT License. Implemented by Alp Özcan using Agentic Engineering for AYA community."
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_STRICT_CONCURRENCY: complete
