// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_audit.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const insertEventAudit = `-- name: InsertEventAudit :exec
INSERT INTO "event_audit" (
  id, event_type, entity_type, entity_id,
  actor_id, actor_kind, session_id, payload, created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  NOW()
)
`

type InsertEventAuditParams struct {
	ID         string                `db:"id" json:"id"`
	EventType  string                `db:"event_type" json:"event_type"`
	EntityType string                `db:"entity_type" json:"entity_type"`
	EntityID   sql.NullString        `db:"entity_id" json:"entity_id"`
	ActorID    sql.NullString        `db:"actor_id" json:"actor_id"`
	ActorKind  string                `db:"actor_kind" json:"actor_kind"`
	SessionID  sql.NullString        `db:"session_id" json:"session_id"`
	Payload    pqtype.NullRawMessage `db:"payload" json:"payload"`
}

// InsertEventAudit
//
//	INSERT INTO "event_audit" (
//	  id, event_type, entity_type, entity_id,
//	  actor_id, actor_kind, session_id, payload, created_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5,
//	  $6,
//	  $7,
//	  $8,
//	  NOW()
//	)
func (q *Queries) InsertEventAudit(ctx context.Context, arg InsertEventAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertEventAudit,
		arg.ID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.ActorKind,
		arg.SessionID,
		arg.Payload,
	)
	return err
}

const listEventAuditByEntity = `-- name: ListEventAuditByEntity :many
SELECT id, event_type, entity_type, entity_id, actor_id, actor_kind, session_id, payload, created_at
FROM "event_audit"
WHERE entity_type = $1
  AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListEventAuditByEntityParams struct {
	EntityType string         `db:"entity_type" json:"entity_type"`
	EntityID   sql.NullString `db:"entity_id" json:"entity_id"`
	LimitCount int32          `db:"limit_count" json:"limit_count"`
}

// ListEventAuditByEntity
//
//	SELECT id, event_type, entity_type, entity_id, actor_id, actor_kind, session_id, payload, created_at
//	FROM "event_audit"
//	WHERE entity_type = $1
//	  AND entity_id = $2
//	ORDER BY created_at DESC
//	LIMIT $3
func (q *Queries) ListEventAuditByEntity(ctx context.Context, arg ListEventAuditByEntityParams) ([]*EventAudit, error) {
	rows, err := q.db.QueryContext(ctx, listEventAuditByEntity, arg.EntityType, arg.EntityID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventAudit{}
	for rows.Next() {
		var i EventAudit
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.ActorKind,
			&i.SessionID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
