// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profile_teams.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const countProfileTeamMembers = `-- name: CountProfileTeamMembers :one
SELECT COUNT(*) FROM "profile_membership_team"
WHERE profile_team_id = $1 AND deleted_at IS NULL
`

type CountProfileTeamMembersParams struct {
	ProfileTeamID string `db:"profile_team_id" json:"profile_team_id"`
}

// CountProfileTeamMembers
//
//	SELECT COUNT(*) FROM "profile_membership_team"
//	WHERE profile_team_id = $1 AND deleted_at IS NULL
func (q *Queries) CountProfileTeamMembers(ctx context.Context, arg CountProfileTeamMembersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfileTeamMembers, arg.ProfileTeamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProfileTeamResources = `-- name: CountProfileTeamResources :one
SELECT COUNT(*) FROM "profile_resource_team"
WHERE profile_team_id = $1 AND deleted_at IS NULL
`

type CountProfileTeamResourcesParams struct {
	ProfileTeamID string `db:"profile_team_id" json:"profile_team_id"`
}

// CountProfileTeamResources
//
//	SELECT COUNT(*) FROM "profile_resource_team"
//	WHERE profile_team_id = $1 AND deleted_at IS NULL
func (q *Queries) CountProfileTeamResources(ctx context.Context, arg CountProfileTeamResourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfileTeamResources, arg.ProfileTeamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfileTeam = `-- name: CreateProfileTeam :one
INSERT INTO "profile_team" (id, profile_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, name, description, created_at, deleted_at
`

type CreateProfileTeamParams struct {
	ID          string         `db:"id" json:"id"`
	ProfileID   string         `db:"profile_id" json:"profile_id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
}

// CreateProfileTeam
//
//	INSERT INTO "profile_team" (id, profile_id, name, description)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, profile_id, name, description, created_at, deleted_at
func (q *Queries) CreateProfileTeam(ctx context.Context, arg CreateProfileTeamParams) (*ProfileTeam, error) {
	row := q.db.QueryRowContext(ctx, createProfileTeam,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.Description,
	)
	var i ProfileTeam
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteProfileTeam = `-- name: DeleteProfileTeam :execrows
UPDATE "profile_team"
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteProfileTeamParams struct {
	ID string `db:"id" json:"id"`
}

// DeleteProfileTeam
//
//	UPDATE "profile_team"
//	SET deleted_at = NOW()
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) DeleteProfileTeam(ctx context.Context, arg DeleteProfileTeamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfileTeam, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProfileTeamByID = `-- name: GetProfileTeamByID :one
SELECT id, profile_id, name, description, created_at, deleted_at FROM "profile_team"
WHERE id = $1 AND deleted_at IS NULL
`

type GetProfileTeamByIDParams struct {
	ID string `db:"id" json:"id"`
}

// GetProfileTeamByID
//
//	SELECT id, profile_id, name, description, created_at, deleted_at FROM "profile_team"
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) GetProfileTeamByID(ctx context.Context, arg GetProfileTeamByIDParams) (*ProfileTeam, error) {
	row := q.db.QueryRowContext(ctx, getProfileTeamByID, arg.ID)
	var i ProfileTeam
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listMembershipTeams = `-- name: ListMembershipTeams :many
SELECT pt.id, pt.profile_id, pt.name, pt.description, pt.created_at, pt.deleted_at FROM "profile_team" pt
JOIN "profile_membership_team" pmt ON pmt.profile_team_id = pt.id AND pmt.deleted_at IS NULL
WHERE pmt.profile_membership_id = $1 AND pt.deleted_at IS NULL
ORDER BY pt.name ASC
`

type ListMembershipTeamsParams struct {
	ProfileMembershipID string `db:"profile_membership_id" json:"profile_membership_id"`
}

// ListMembershipTeams
//
//	SELECT pt.id, pt.profile_id, pt.name, pt.description, pt.created_at, pt.deleted_at FROM "profile_team" pt
//	JOIN "profile_membership_team" pmt ON pmt.profile_team_id = pt.id AND pmt.deleted_at IS NULL
//	WHERE pmt.profile_membership_id = $1 AND pt.deleted_at IS NULL
//	ORDER BY pt.name ASC
func (q *Queries) ListMembershipTeams(ctx context.Context, arg ListMembershipTeamsParams) ([]*ProfileTeam, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipTeams, arg.ProfileMembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProfileTeam{}
	for rows.Next() {
		var i ProfileTeam
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileTeams = `-- name: ListProfileTeams :many
SELECT id, profile_id, name, description, created_at, deleted_at FROM "profile_team"
WHERE profile_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

type ListProfileTeamsParams struct {
	ProfileID string `db:"profile_id" json:"profile_id"`
}

// ListProfileTeams
//
//	SELECT id, profile_id, name, description, created_at, deleted_at FROM "profile_team"
//	WHERE profile_id = $1 AND deleted_at IS NULL
//	ORDER BY name ASC
func (q *Queries) ListProfileTeams(ctx context.Context, arg ListProfileTeamsParams) ([]*ProfileTeam, error) {
	rows, err := q.db.QueryContext(ctx, listProfileTeams, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProfileTeam{}
	for rows.Next() {
		var i ProfileTeam
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileTeamsWithMemberCount = `-- name: ListProfileTeamsWithMemberCount :many
SELECT pt.id, pt.profile_id, pt.name, pt.description, pt.created_at, pt.deleted_at,
  COUNT(DISTINCT pmt.id) AS member_count,
  COUNT(DISTINCT prt.id) AS resource_count
FROM "profile_team" pt
LEFT JOIN "profile_membership_team" pmt ON pmt.profile_team_id = pt.id AND pmt.deleted_at IS NULL
LEFT JOIN "profile_resource_team" prt ON prt.profile_team_id = pt.id AND prt.deleted_at IS NULL
WHERE pt.profile_id = $1 AND pt.deleted_at IS NULL
GROUP BY pt.id
ORDER BY pt.name ASC
`

type ListProfileTeamsWithMemberCountParams struct {
	ProfileID string `db:"profile_id" json:"profile_id"`
}

type ListProfileTeamsWithMemberCountRow struct {
	ID            string         `db:"id" json:"id"`
	ProfileID     string         `db:"profile_id" json:"profile_id"`
	Name          string         `db:"name" json:"name"`
	Description   sql.NullString `db:"description" json:"description"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	MemberCount   int64          `db:"member_count" json:"member_count"`
	ResourceCount int64          `db:"resource_count" json:"resource_count"`
}

// ListProfileTeamsWithMemberCount
//
//	SELECT pt.id, pt.profile_id, pt.name, pt.description, pt.created_at, pt.deleted_at,
//	  COUNT(DISTINCT pmt.id) AS member_count,
//	  COUNT(DISTINCT prt.id) AS resource_count
//	FROM "profile_team" pt
//	LEFT JOIN "profile_membership_team" pmt ON pmt.profile_team_id = pt.id AND pmt.deleted_at IS NULL
//	LEFT JOIN "profile_resource_team" prt ON prt.profile_team_id = pt.id AND prt.deleted_at IS NULL
//	WHERE pt.profile_id = $1 AND pt.deleted_at IS NULL
//	GROUP BY pt.id
//	ORDER BY pt.name ASC
func (q *Queries) ListProfileTeamsWithMemberCount(ctx context.Context, arg ListProfileTeamsWithMemberCountParams) ([]*ListProfileTeamsWithMemberCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileTeamsWithMemberCount, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListProfileTeamsWithMemberCountRow{}
	for rows.Next() {
		var i ListProfileTeamsWithMemberCountRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.MemberCount,
			&i.ResourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceTeams = `-- name: ListResourceTeams :many
SELECT pt.id, pt.profile_id, pt.name, pt.description, pt.created_at, pt.deleted_at FROM "profile_team" pt
JOIN "profile_resource_team" prt ON prt.profile_team_id = pt.id AND prt.deleted_at IS NULL
WHERE prt.profile_resource_id = $1 AND pt.deleted_at IS NULL
ORDER BY pt.name ASC
`

type ListResourceTeamsParams struct {
	ProfileResourceID string `db:"profile_resource_id" json:"profile_resource_id"`
}

// ListResourceTeams
//
//	SELECT pt.id, pt.profile_id, pt.name, pt.description, pt.created_at, pt.deleted_at FROM "profile_team" pt
//	JOIN "profile_resource_team" prt ON prt.profile_team_id = pt.id AND prt.deleted_at IS NULL
//	WHERE prt.profile_resource_id = $1 AND pt.deleted_at IS NULL
//	ORDER BY pt.name ASC
func (q *Queries) ListResourceTeams(ctx context.Context, arg ListResourceTeamsParams) ([]*ProfileTeam, error) {
	rows, err := q.db.QueryContext(ctx, listResourceTeams, arg.ProfileResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProfileTeam{}
	for rows.Next() {
		var i ProfileTeam
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMembershipTeams_Delete = `-- name: SetMembershipTeams_Delete :execrows
UPDATE "profile_membership_team"
SET deleted_at = NOW()
WHERE profile_membership_id = $1 AND deleted_at IS NULL
`

type SetMembershipTeams_DeleteParams struct {
	ProfileMembershipID string `db:"profile_membership_id" json:"profile_membership_id"`
}

// SetMembershipTeams_Delete
//
//	UPDATE "profile_membership_team"
//	SET deleted_at = NOW()
//	WHERE profile_membership_id = $1 AND deleted_at IS NULL
func (q *Queries) SetMembershipTeams_Delete(ctx context.Context, arg SetMembershipTeams_DeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMembershipTeams_Delete, arg.ProfileMembershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setMembershipTeams_Insert = `-- name: SetMembershipTeams_Insert :one
INSERT INTO "profile_membership_team" (id, profile_membership_id, profile_team_id)
VALUES ($1, $2, $3)
RETURNING id, profile_membership_id, profile_team_id, created_at, deleted_at
`

type SetMembershipTeams_InsertParams struct {
	ID                  string `db:"id" json:"id"`
	ProfileMembershipID string `db:"profile_membership_id" json:"profile_membership_id"`
	ProfileTeamID       string `db:"profile_team_id" json:"profile_team_id"`
}

// SetMembershipTeams_Insert
//
//	INSERT INTO "profile_membership_team" (id, profile_membership_id, profile_team_id)
//	VALUES ($1, $2, $3)
//	RETURNING id, profile_membership_id, profile_team_id, created_at, deleted_at
func (q *Queries) SetMembershipTeams_Insert(ctx context.Context, arg SetMembershipTeams_InsertParams) (*ProfileMembershipTeam, error) {
	row := q.db.QueryRowContext(ctx, setMembershipTeams_Insert, arg.ID, arg.ProfileMembershipID, arg.ProfileTeamID)
	var i ProfileMembershipTeam
	err := row.Scan(
		&i.ID,
		&i.ProfileMembershipID,
		&i.ProfileTeamID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const setResourceTeams_Delete = `-- name: SetResourceTeams_Delete :execrows
UPDATE "profile_resource_team"
SET deleted_at = NOW()
WHERE profile_resource_id = $1 AND deleted_at IS NULL
`

type SetResourceTeams_DeleteParams struct {
	ProfileResourceID string `db:"profile_resource_id" json:"profile_resource_id"`
}

// SetResourceTeams_Delete
//
//	UPDATE "profile_resource_team"
//	SET deleted_at = NOW()
//	WHERE profile_resource_id = $1 AND deleted_at IS NULL
func (q *Queries) SetResourceTeams_Delete(ctx context.Context, arg SetResourceTeams_DeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setResourceTeams_Delete, arg.ProfileResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setResourceTeams_Insert = `-- name: SetResourceTeams_Insert :one
INSERT INTO "profile_resource_team" (id, profile_resource_id, profile_team_id)
VALUES ($1, $2, $3)
RETURNING id, profile_resource_id, profile_team_id, created_at, deleted_at
`

type SetResourceTeams_InsertParams struct {
	ID                string `db:"id" json:"id"`
	ProfileResourceID string `db:"profile_resource_id" json:"profile_resource_id"`
	ProfileTeamID     string `db:"profile_team_id" json:"profile_team_id"`
}

// SetResourceTeams_Insert
//
//	INSERT INTO "profile_resource_team" (id, profile_resource_id, profile_team_id)
//	VALUES ($1, $2, $3)
//	RETURNING id, profile_resource_id, profile_team_id, created_at, deleted_at
func (q *Queries) SetResourceTeams_Insert(ctx context.Context, arg SetResourceTeams_InsertParams) (*ProfileResourceTeam, error) {
	row := q.db.QueryRowContext(ctx, setResourceTeams_Insert, arg.ID, arg.ProfileResourceID, arg.ProfileTeamID)
	var i ProfileResourceTeam
	err := row.Scan(
		&i.ID,
		&i.ProfileResourceID,
		&i.ProfileTeamID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateProfileTeam = `-- name: UpdateProfileTeam :execrows
UPDATE "profile_team"
SET name = $1, description = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateProfileTeamParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	ID          string         `db:"id" json:"id"`
}

// UpdateProfileTeam
//
//	UPDATE "profile_team"
//	SET name = $1, description = $2
//	WHERE id = $3 AND deleted_at IS NULL
func (q *Queries) UpdateProfileTeam(ctx context.Context, arg UpdateProfileTeamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProfileTeam, arg.Name, arg.Description, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
