// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_points.sql

package storage

import (
	"context"
	"database/sql"
)

const addPointsToProfile = `-- name: AddPointsToProfile :execrows
UPDATE "profile"
SET
  points = points + $1,
  updated_at = NOW()
WHERE id = $2
  AND deleted_at IS NULL
`

type AddPointsToProfileParams struct {
	Amount int32  `db:"amount" json:"amount"`
	ID     string `db:"id" json:"id"`
}

// AddPointsToProfile
//
//	UPDATE "profile"
//	SET
//	  points = points + $1,
//	  updated_at = NOW()
//	WHERE id = $2
//	  AND deleted_at IS NULL
func (q *Queries) AddPointsToProfile(ctx context.Context, arg AddPointsToProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addPointsToProfile, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deductPointsFromProfile = `-- name: DeductPointsFromProfile :execrows
UPDATE "profile"
SET
  points = points - $1,
  updated_at = NOW()
WHERE id = $2
  AND deleted_at IS NULL
  AND points >= $1
`

type DeductPointsFromProfileParams struct {
	Amount int32  `db:"amount" json:"amount"`
	ID     string `db:"id" json:"id"`
}

// DeductPointsFromProfile
//
//	UPDATE "profile"
//	SET
//	  points = points - $1,
//	  updated_at = NOW()
//	WHERE id = $2
//	  AND deleted_at IS NULL
//	  AND points >= $1
func (q *Queries) DeductPointsFromProfile(ctx context.Context, arg DeductPointsFromProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deductPointsFromProfile, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProfilePointTransactionByID = `-- name: GetProfilePointTransactionByID :one
SELECT id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
FROM "profile_point_transaction"
WHERE id = $1
`

type GetProfilePointTransactionByIDParams struct {
	ID string `db:"id" json:"id"`
}

// GetProfilePointTransactionByID
//
//	SELECT id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
//	FROM "profile_point_transaction"
//	WHERE id = $1
func (q *Queries) GetProfilePointTransactionByID(ctx context.Context, arg GetProfilePointTransactionByIDParams) (*ProfilePointTransaction, error) {
	row := q.db.QueryRowContext(ctx, getProfilePointTransactionByID, arg.ID)
	var i ProfilePointTransaction
	err := row.Scan(
		&i.ID,
		&i.TargetProfileID,
		&i.OriginProfileID,
		&i.TransactionType,
		&i.TriggeringEvent,
		&i.Description,
		&i.Amount,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return &i, err
}

const getProfilePoints = `-- name: GetProfilePoints :one
SELECT points
FROM "profile"
WHERE id = $1
  AND deleted_at IS NULL
`

type GetProfilePointsParams struct {
	ProfileID string `db:"profile_id" json:"profile_id"`
}

// GetProfilePoints
//
//	SELECT points
//	FROM "profile"
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetProfilePoints(ctx context.Context, arg GetProfilePointsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getProfilePoints, arg.ProfileID)
	var points int32
	err := row.Scan(&points)
	return points, err
}

const listProfilePointTransactionsByProfileID = `-- name: ListProfilePointTransactionsByProfileID :many
SELECT id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
FROM "profile_point_transaction"
WHERE target_profile_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListProfilePointTransactionsByProfileIDParams struct {
	ProfileID  string `db:"profile_id" json:"profile_id"`
	LimitCount int32  `db:"limit_count" json:"limit_count"`
}

// ListProfilePointTransactionsByProfileID
//
//	SELECT id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
//	FROM "profile_point_transaction"
//	WHERE target_profile_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2
func (q *Queries) ListProfilePointTransactionsByProfileID(ctx context.Context, arg ListProfilePointTransactionsByProfileIDParams) ([]*ProfilePointTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listProfilePointTransactionsByProfileID, arg.ProfileID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProfilePointTransaction{}
	for rows.Next() {
		var i ProfilePointTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TargetProfileID,
			&i.OriginProfileID,
			&i.TransactionType,
			&i.TriggeringEvent,
			&i.Description,
			&i.Amount,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProfilePointTransaction = `-- name: RecordProfilePointTransaction :one
INSERT INTO "profile_point_transaction" (
  id,
  target_profile_id,
  origin_profile_id,
  transaction_type,
  triggering_event,
  description,
  amount,
  balance_after,
  created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  NOW()
) RETURNING id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
`

type RecordProfilePointTransactionParams struct {
	ID              string         `db:"id" json:"id"`
	TargetProfileID string         `db:"target_profile_id" json:"target_profile_id"`
	OriginProfileID sql.NullString `db:"origin_profile_id" json:"origin_profile_id"`
	TransactionType string         `db:"transaction_type" json:"transaction_type"`
	TriggeringEvent sql.NullString `db:"triggering_event" json:"triggering_event"`
	Description     string         `db:"description" json:"description"`
	Amount          int32          `db:"amount" json:"amount"`
	BalanceAfter    int32          `db:"balance_after" json:"balance_after"`
}

// RecordProfilePointTransaction
//
//	INSERT INTO "profile_point_transaction" (
//	  id,
//	  target_profile_id,
//	  origin_profile_id,
//	  transaction_type,
//	  triggering_event,
//	  description,
//	  amount,
//	  balance_after,
//	  created_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5,
//	  $6,
//	  $7,
//	  $8,
//	  NOW()
//	) RETURNING id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
func (q *Queries) RecordProfilePointTransaction(ctx context.Context, arg RecordProfilePointTransactionParams) (*ProfilePointTransaction, error) {
	row := q.db.QueryRowContext(ctx, recordProfilePointTransaction,
		arg.ID,
		arg.TargetProfileID,
		arg.OriginProfileID,
		arg.TransactionType,
		arg.TriggeringEvent,
		arg.Description,
		arg.Amount,
		arg.BalanceAfter,
	)
	var i ProfilePointTransaction
	err := row.Scan(
		&i.ID,
		&i.TargetProfileID,
		&i.OriginProfileID,
		&i.TransactionType,
		&i.TriggeringEvent,
		&i.Description,
		&i.Amount,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return &i, err
}
