// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"context"
)

type Querier interface {
	//AddPointsToProfile
	//
	//  UPDATE "profile"
	//  SET
	//    points = points + $1,
	//    updated_at = NOW()
	//  WHERE id = $2
	//    AND deleted_at IS NULL
	AddPointsToProfile(ctx context.Context, arg AddPointsToProfileParams) (int64, error)
	//ApprovePendingAward
	//
	//  UPDATE "profile_point_pending_award"
	//  SET
	//    status = 'approved',
	//    reviewed_by = $1,
	//    reviewed_at = NOW()
	//  WHERE id = $2
	//    AND status = 'pending'
	ApprovePendingAward(ctx context.Context, arg ApprovePendingAwardParams) error
	//BulkAddPointsToProfiles
	//
	//  UPDATE "profile" p
	//  SET
	//    points = p.points + a.amount,
	//    updated_at = NOW()
	//  FROM (
	//    SELECT target_profile_id, amount
	//    FROM "profile_point_pending_award"
	//    WHERE id = ANY($1::TEXT[])
	//      AND status = 'pending'
	//  ) a
	//  WHERE p.id = a.target_profile_id
	//    AND p.deleted_at IS NULL
	BulkAddPointsToProfiles(ctx context.Context, arg BulkAddPointsToProfilesParams) error
	//BulkApprovePendingAwards
	//
	//  UPDATE "profile_point_pending_award"
	//  SET
	//    status = 'approved',
	//    reviewed_by = $1,
	//    reviewed_at = NOW()
	//  WHERE id = ANY($2::TEXT[])
	//    AND status = 'pending'
	BulkApprovePendingAwards(ctx context.Context, arg BulkApprovePendingAwardsParams) error
	//BulkRejectPendingAwards
	//
	//  UPDATE "profile_point_pending_award"
	//  SET
	//    status = 'rejected',
	//    reviewed_by = $1,
	//    reviewed_at = NOW(),
	//    rejection_reason = $2
	//  WHERE id = ANY($3::TEXT[])
	//    AND status = 'pending'
	BulkRejectPendingAwards(ctx context.Context, arg BulkRejectPendingAwardsParams) error
	//CheckPageSlugExistsIncludingDeleted
	//
	//  SELECT EXISTS(
	//    SELECT 1 FROM "profile_page"
	//    WHERE profile_id = $1
	//      AND slug = $2
	//  ) AS exists
	CheckPageSlugExistsIncludingDeleted(ctx context.Context, arg CheckPageSlugExistsIncludingDeletedParams) (bool, error)
	//CheckProfileSlugExists
	//
	//  SELECT EXISTS(
	//    SELECT 1 FROM "profile"
	//    WHERE slug = $1
	//      AND deleted_at IS NULL
	//  ) AS exists
	CheckProfileSlugExists(ctx context.Context, arg CheckProfileSlugExistsParams) (bool, error)
	//CheckProfileSlugExistsIncludingDeleted
	//
	//  SELECT EXISTS(
	//    SELECT 1 FROM "profile"
	//    WHERE slug = $1
	//  ) AS exists
	CheckProfileSlugExistsIncludingDeleted(ctx context.Context, arg CheckProfileSlugExistsIncludingDeletedParams) (bool, error)
	// CTE-based claim: atomically selects + locks + updates.
	// Picks up both pending events that are due AND stale processing events
	// past their visibility timeout (crash recovery built into the claim).
	// Increments retry_count at claim time for crash safety.
	//
	//  WITH claimable AS (
	//    SELECT id FROM "event_queue"
	//    WHERE (
	//      (status = 'pending' AND visible_at <= NOW())
	//      OR (status = 'processing' AND visible_at <= NOW())
	//    )
	//    AND retry_count <= max_retries
	//    ORDER BY visible_at ASC
	//    LIMIT 1
	//    FOR UPDATE SKIP LOCKED
	//  )
	//  UPDATE "event_queue"
	//  SET
	//    status = 'processing',
	//    started_at = NOW(),
	//    visible_at = NOW() + visibility_timeout_secs * INTERVAL '1 second',
	//    retry_count = retry_count + 1,
	//    worker_id = $1,
	//    updated_at = NOW()
	//  FROM claimable
	//  WHERE "event_queue".id = claimable.id
	//  RETURNING event_queue.id, event_queue.type, event_queue.payload, event_queue.status, event_queue.retry_count, event_queue.max_retries, event_queue.visible_at, event_queue.visibility_timeout_secs, event_queue.started_at, event_queue.completed_at, event_queue.failed_at, event_queue.created_at, event_queue.updated_at, event_queue.error_message, event_queue.worker_id
	ClaimNextEvent(ctx context.Context, arg ClaimNextEventParams) (*EventQueue, error)
	//CleanupExpiredSessionRateLimits
	//
	//  DELETE FROM session_rate_limit
	//  WHERE
	//    window_start < NOW() - INTERVAL '2 hours'
	CleanupExpiredSessionRateLimits(ctx context.Context) error
	// Worker ID check prevents a timed-out worker from completing
	// a job that was already re-claimed by another worker.
	//
	//  UPDATE "event_queue"
	//  SET
	//    status = 'completed',
	//    completed_at = NOW(),
	//    updated_at = NOW()
	//  WHERE id = $1
	//    AND status = 'processing'
	//    AND worker_id = $2
	CompleteEvent(ctx context.Context, arg CompleteEventParams) (int64, error)
	//CopySessionPreferences
	//
	//  INSERT INTO
	//    session_preference (session_id, key, value, updated_at)
	//  SELECT
	//    $1,
	//    sp.key,
	//    sp.value,
	//    NOW()
	//  FROM
	//    session_preference sp
	//  WHERE
	//    sp.session_id = $2
	//  ON CONFLICT (session_id, key) DO UPDATE
	//  SET
	//    value = EXCLUDED.value,
	//    updated_at = NOW()
	CopySessionPreferences(ctx context.Context, arg CopySessionPreferencesParams) error
	//CountAllProfilesForAdmin
	//
	//  SELECT COUNT(*) as count
	//  FROM "profile" p
	//  WHERE p.deleted_at IS NULL
	//    AND ($1::TEXT IS NULL OR p.kind = ANY(string_to_array($1::TEXT, ',')))
	CountAllProfilesForAdmin(ctx context.Context, arg CountAllProfilesForAdminParams) (int64, error)
	//CountPOWChallengesByIPHash
	//
	//  SELECT
	//    COUNT(*) AS count
	//  FROM
	//    protection_pow_challenge
	//  WHERE
	//    ip_hash = $1
	//    AND created_at > NOW() - INTERVAL '1 hour'
	//    AND used = FALSE
	CountPOWChallengesByIPHash(ctx context.Context, arg CountPOWChallengesByIPHashParams) (int64, error)
	//CreateLinkImport
	//
	//  INSERT INTO "profile_link_import" (id, profile_link_id, remote_id, properties, created_at)
	//  VALUES ($1, $2, $3, $4, NOW())
	CreateLinkImport(ctx context.Context, arg CreateLinkImportParams) error
	// PoW Challenges
	//
	//
	//  INSERT INTO
	//    protection_pow_challenge (
	//      id,
	//      prefix,
	//      difficulty,
	//      ip_hash,
	//      used,
	//      expires_at,
	//      created_at
	//    )
	//  VALUES
	//    (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//    )
	CreatePOWChallenge(ctx context.Context, arg CreatePOWChallengeParams) error
	// Pending Award Queries
	//
	//
	//  INSERT INTO "profile_point_pending_award" (
	//    id,
	//    target_profile_id,
	//    triggering_event,
	//    description,
	//    amount,
	//    status,
	//    metadata,
	//    created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5,
	//    'pending',
	//    $6,
	//    NOW()
	//  ) RETURNING id, target_profile_id, triggering_event, description, amount, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
	CreatePendingAward(ctx context.Context, arg CreatePendingAwardParams) (*ProfilePointPendingAward, error)
	//CreateProfile
	//
	//  INSERT INTO "profile" (id, slug, kind, custom_domain, profile_picture_uri, pronouns, properties)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7)
	CreateProfile(ctx context.Context, arg CreateProfileParams) error
	//CreateProfileLink
	//
	//  INSERT INTO "profile_link" (
	//    id,
	//    kind,
	//    profile_id,
	//    "order",
	//    is_managed,
	//    is_verified,
	//    is_hidden,
	//    is_featured,
	//    visibility,
	//    remote_id,
	//    public_id,
	//    uri,
	//    title,
	//    auth_provider,
	//    auth_access_token_scope,
	//    auth_access_token,
	//    auth_access_token_expires_at,
	//    auth_refresh_token,
	//    auth_refresh_token_expires_at,
	//    created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5,
	//    $6,
	//    $7,
	//    $8,
	//    $9,
	//    $10,
	//    $11,
	//    $12,
	//    $13,
	//    $14,
	//    $15,
	//    $16,
	//    $17,
	//    $18,
	//    $19,
	//    NOW()
	//  ) RETURNING id, profile_id, kind, "order", is_managed, is_verified, is_hidden, remote_id, public_id, uri, title, auth_provider, auth_access_token_scope, auth_access_token, auth_access_token_expires_at, auth_refresh_token, auth_refresh_token_expires_at, properties, created_at, updated_at, deleted_at, visibility, is_featured
	CreateProfileLink(ctx context.Context, arg CreateProfileLinkParams) (*ProfileLink, error)
	//CreateProfileLinkTx
	//
	//  INSERT INTO "profile_link_tx" (
	//    profile_link_id,
	//    locale_code,
	//    title,
	//    "group",
	//    description
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5
	//  )
	CreateProfileLinkTx(ctx context.Context, arg CreateProfileLinkTxParams) error
	//CreateProfilePage
	//
	//  INSERT INTO "profile_page" (
	//    id,
	//    slug,
	//    profile_id,
	//    "order",
	//    cover_picture_uri,
	//    published_at,
	//    created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5,
	//    $6,
	//    NOW()
	//  ) RETURNING id, profile_id, slug, "order", cover_picture_uri, published_at, created_at, updated_at, deleted_at
	CreateProfilePage(ctx context.Context, arg CreateProfilePageParams) (*ProfilePage, error)
	//CreateProfilePageTx
	//
	//  INSERT INTO "profile_page_tx" (
	//    profile_page_id,
	//    locale_code,
	//    title,
	//    summary,
	//    content
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5
	//  )
	CreateProfilePageTx(ctx context.Context, arg CreateProfilePageTxParams) error
	//CreateProfileTx
	//
	//  INSERT INTO "profile_tx" (profile_id, locale_code, title, description, properties)
	//  VALUES ($1, $2, $3, $4, $5)
	CreateProfileTx(ctx context.Context, arg CreateProfileTxParams) error
	//CreateSession
	//
	//  INSERT INTO
	//    session (
	//      id,
	//      status,
	//      oauth_request_state,
	//      oauth_request_code_verifier,
	//      oauth_redirect_uri,
	//      logged_in_user_id,
	//      logged_in_at,
	//      last_activity_at,
	//      user_agent,
	//      expires_at,
	//      created_at,
	//      updated_at
	//    )
	//  VALUES
	//    (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12
	//    )
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	//CreateUser
	//
	//  INSERT INTO "user" (
	//      id,
	//      kind,
	//      NAME,
	//      email,
	//      phone,
	//      github_handle,
	//      github_remote_id,
	//      bsky_handle,
	//      bsky_remote_id,
	//      x_handle,
	//      x_remote_id,
	//      individual_profile_id,
	//      created_at,
	//      updated_at,
	//      deleted_at
	//    )
	//  VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      $13,
	//      $14,
	//      $15
	//    )
	CreateUser(ctx context.Context, arg CreateUserParams) error
	//DeductPointsFromProfile
	//
	//  UPDATE "profile"
	//  SET
	//    points = points - $1,
	//    updated_at = NOW()
	//  WHERE id = $2
	//    AND deleted_at IS NULL
	//    AND points >= $1
	DeductPointsFromProfile(ctx context.Context, arg DeductPointsFromProfileParams) (int64, error)
	//DeleteAllSessionPreferences
	//
	//  DELETE FROM session_preference
	//  WHERE
	//    session_id = $1
	DeleteAllSessionPreferences(ctx context.Context, arg DeleteAllSessionPreferencesParams) error
	//DeleteExpiredPOWChallenges
	//
	//  DELETE FROM protection_pow_challenge
	//  WHERE
	//    expires_at < NOW()
	DeleteExpiredPOWChallenges(ctx context.Context) error
	//DeleteProfileLink
	//
	//  UPDATE "profile_link"
	//  SET deleted_at = NOW()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	DeleteProfileLink(ctx context.Context, arg DeleteProfileLinkParams) (int64, error)
	//DeleteProfilePage
	//
	//  UPDATE "profile_page"
	//  SET deleted_at = NOW()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	DeleteProfilePage(ctx context.Context, arg DeleteProfilePageParams) (int64, error)
	//DeleteSessionPreference
	//
	//  DELETE FROM session_preference
	//  WHERE
	//    session_id = $1
	//    AND key = $2
	DeleteSessionPreference(ctx context.Context, arg DeleteSessionPreferenceParams) error
	//EnqueueEvent
	//
	//  INSERT INTO "event_queue" (
	//    id, type, payload, status, max_retries,
	//    visibility_timeout_secs, visible_at, created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    'pending',
	//    $4,
	//    $5,
	//    $6,
	//    NOW()
	//  )
	EnqueueEvent(ctx context.Context, arg EnqueueEventParams) error
	// On failure: if retries exhausted -> dead, otherwise -> pending with backoff.
	// Worker ID check prevents stale workers from interfering.
	//
	//  UPDATE "event_queue"
	//  SET
	//    status = CASE
	//      WHEN retry_count >= max_retries THEN 'dead'
	//      ELSE 'pending'
	//    END,
	//    error_message = $1,
	//    failed_at = NOW(),
	//    visible_at = CASE
	//      WHEN retry_count >= max_retries THEN visible_at
	//      ELSE NOW() + $2::INTEGER * INTERVAL '1 second'
	//    END,
	//    worker_id = NULL,
	//    updated_at = NOW()
	//  WHERE id = $3
	//    AND status = 'processing'
	//    AND worker_id = $4
	FailEvent(ctx context.Context, arg FailEventParams) (int64, error)
	//GetAdminProfileBySlug
	//
	//  SELECT
	//    p.id,
	//    p.slug,
	//    p.kind,
	//    p.custom_domain,
	//    p.profile_picture_uri,
	//    p.pronouns,
	//    p.properties,
	//    p.created_at,
	//    p.updated_at,
	//    p.points,
	//    COALESCE(pt.title, '') as title,
	//    COALESCE(pt.description, '') as description,
	//    pt.profile_id IS NOT NULL as has_translation
	//  FROM "profile" p
	//    LEFT JOIN "profile_tx" pt ON pt.profile_id = p.id
	//    AND pt.locale_code = $1
	//  WHERE p.slug = $2
	//    AND p.deleted_at IS NULL
	//  LIMIT 1
	GetAdminProfileBySlug(ctx context.Context, arg GetAdminProfileBySlugParams) (*GetAdminProfileBySlugRow, error)
	//GetFromCache
	//
	//  SELECT value, updated_at
	//  FROM "cache"
	//  WHERE key = $1
	//  LIMIT 1
	GetFromCache(ctx context.Context, arg GetFromCacheParams) (*GetFromCacheRow, error)
	//GetFromCacheSince
	//
	//  SELECT value, updated_at
	//  FROM "cache"
	//  WHERE key = $1
	//    AND updated_at > $2
	//  LIMIT 1
	GetFromCacheSince(ctx context.Context, arg GetFromCacheSinceParams) (*GetFromCacheSinceRow, error)
	//GetLatestImportByLinkID
	//
	//  SELECT id, profile_link_id, remote_id, properties, created_at, updated_at, deleted_at
	//  FROM "profile_link_import"
	//  WHERE profile_link_id = $1
	//    AND deleted_at IS NULL
	//  ORDER BY created_at DESC
	//  LIMIT 1
	GetLatestImportByLinkID(ctx context.Context, arg GetLatestImportByLinkIDParams) (*ProfileLinkImport, error)
	//GetLinkImportByRemoteID
	//
	//  SELECT id, profile_link_id, remote_id, properties, created_at, updated_at, deleted_at
	//  FROM "profile_link_import"
	//  WHERE profile_link_id = $1
	//    AND remote_id = $2
	//  LIMIT 1
	GetLinkImportByRemoteID(ctx context.Context, arg GetLinkImportByRemoteIDParams) (*ProfileLinkImport, error)
	//GetMaxProfileLinkOrder
	//
	//  SELECT COALESCE(MAX("order"), 0) as max_order
	//  FROM "profile_link"
	//  WHERE profile_id = $1
	//    AND deleted_at IS NULL
	GetMaxProfileLinkOrder(ctx context.Context, arg GetMaxProfileLinkOrderParams) (interface{}, error)
	//GetMembershipBetweenProfiles
	//
	//  SELECT pm.kind
	//  FROM "profile_membership" pm
	//  WHERE pm.profile_id = $1
	//    AND pm.member_profile_id = $2
	//    AND pm.deleted_at IS NULL
	//    AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
	//  LIMIT 1
	GetMembershipBetweenProfiles(ctx context.Context, arg GetMembershipBetweenProfilesParams) (string, error)
	//GetPOWChallengeByID
	//
	//  SELECT
	//    id,
	//    prefix,
	//    difficulty,
	//    ip_hash,
	//    used,
	//    expires_at,
	//    created_at
	//  FROM
	//    protection_pow_challenge
	//  WHERE
	//    id = $1
	GetPOWChallengeByID(ctx context.Context, arg GetPOWChallengeByIDParams) (*ProtectionPowChallenge, error)
	//GetPendingAwardByID
	//
	//  SELECT id, target_profile_id, triggering_event, description, amount, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
	//  FROM "profile_point_pending_award"
	//  WHERE id = $1
	GetPendingAwardByID(ctx context.Context, arg GetPendingAwardByIDParams) (*ProfilePointPendingAward, error)
	//GetPendingAwardsByIDs
	//
	//  SELECT id, target_profile_id, triggering_event, description, amount, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
	//  FROM "profile_point_pending_award"
	//  WHERE id = ANY($1::TEXT[])
	//    AND status = 'pending'
	GetPendingAwardsByIDs(ctx context.Context, arg GetPendingAwardsByIDsParams) ([]*ProfilePointPendingAward, error)
	//GetPendingAwardsStats
	//
	//  SELECT
	//    COUNT(*) FILTER (WHERE status = 'pending') AS total_pending,
	//    COUNT(*) FILTER (WHERE status = 'approved') AS total_approved,
	//    COUNT(*) FILTER (WHERE status = 'rejected') AS total_rejected,
	//    COALESCE(SUM(amount) FILTER (WHERE status = 'approved'), 0) AS points_awarded
	//  FROM "profile_point_pending_award"
	GetPendingAwardsStats(ctx context.Context) (*GetPendingAwardsStatsRow, error)
	//GetPendingAwardsStatsByEventType
	//
	//  SELECT
	//    triggering_event,
	//    COUNT(*) AS count
	//  FROM "profile_point_pending_award"
	//  WHERE status = 'pending'
	//  GROUP BY triggering_event
	GetPendingAwardsStatsByEventType(ctx context.Context) ([]*GetPendingAwardsStatsByEventTypeRow, error)
	//GetProfileByID
	//
	//  SELECT p.id, p.slug, p.kind, p.custom_domain, p.profile_picture_uri, p.pronouns, p.properties, p.created_at, p.updated_at, p.deleted_at, p.approved_at, p.points, pt.profile_id, pt.locale_code, pt.title, pt.description, pt.properties, pt.search_vector
	//  FROM "profile" p
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//    AND pt.locale_code = $1
	//  WHERE p.id = $2
	//    AND p.deleted_at IS NULL
	//  LIMIT 1
	GetProfileByID(ctx context.Context, arg GetProfileByIDParams) (*GetProfileByIDRow, error)
	//GetProfileIDByCustomDomain
	//
	//  SELECT id
	//  FROM "profile"
	//  WHERE custom_domain = $1
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetProfileIDByCustomDomain(ctx context.Context, arg GetProfileIDByCustomDomainParams) (string, error)
	//GetProfileIDBySlug
	//
	//  SELECT id
	//  FROM "profile"
	//  WHERE slug = $1
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetProfileIDBySlug(ctx context.Context, arg GetProfileIDBySlugParams) (string, error)
	//GetProfileLink
	//
	//  SELECT id, profile_id, kind, "order", is_managed, is_verified, is_hidden, remote_id, public_id, uri, title, auth_provider, auth_access_token_scope, auth_access_token, auth_access_token_expires_at, auth_refresh_token, auth_refresh_token_expires_at, properties, created_at, updated_at, deleted_at, visibility, is_featured
	//  FROM "profile_link"
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetProfileLink(ctx context.Context, arg GetProfileLinkParams) (*ProfileLink, error)
	//GetProfileLinkByRemoteID
	//
	//  SELECT id, profile_id, kind, "order", is_managed, is_verified, is_hidden, remote_id, public_id, uri, title, auth_provider, auth_access_token_scope, auth_access_token, auth_access_token_expires_at, auth_refresh_token, auth_refresh_token_expires_at, properties, created_at, updated_at, deleted_at, visibility, is_featured
	//  FROM "profile_link"
	//  WHERE profile_id = $1
	//    AND kind = $2
	//    AND remote_id = $3
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetProfileLinkByRemoteID(ctx context.Context, arg GetProfileLinkByRemoteIDParams) (*ProfileLink, error)
	//GetProfileLinkTx
	//
	//  SELECT profile_link_id, locale_code, title, "group", description
	//  FROM "profile_link_tx"
	//  WHERE profile_link_id = $1
	//    AND locale_code = $2
	//  LIMIT 1
	GetProfileLinkTx(ctx context.Context, arg GetProfileLinkTxParams) (*ProfileLinkTx, error)
	//GetProfileMembershipsByMemberProfileID
	//
	//  SELECT
	//    pm.id as membership_id,
	//    pm.kind as membership_kind,
	//    pm.started_at,
	//    pm.finished_at,
	//    pm.properties as membership_properties,
	//    pm.created_at as membership_created_at,
	//    p.id, p.slug, p.kind, p.custom_domain, p.profile_picture_uri, p.pronouns, p.properties, p.created_at, p.updated_at, p.deleted_at, p.approved_at, p.points,
	//    pt.profile_id, pt.locale_code, pt.title, pt.description, pt.properties, pt.search_vector
	//  FROM
	//    "profile_membership" pm
	//    INNER JOIN "profile" p ON p.id = pm.profile_id
	//      AND p.approved_at IS NOT NULL
	//      AND p.deleted_at IS NULL
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//      AND pt.locale_code = $1
	//  WHERE
	//    pm.deleted_at IS NULL
	//    AND pm.member_profile_id = $2
	//    AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
	//  ORDER BY pm.created_at DESC
	GetProfileMembershipsByMemberProfileID(ctx context.Context, arg GetProfileMembershipsByMemberProfileIDParams) ([]*GetProfileMembershipsByMemberProfileIDRow, error)
	//GetProfileOwnershipForUser
	//
	//  SELECT
	//    p.id,
	//    p.slug,
	//    p.kind as profile_kind,
	//    u.kind as user_kind,
	//    CASE
	//      WHEN u.kind = 'admin' THEN true
	//      WHEN p.kind = 'individual' AND u.individual_profile_id = p.id THEN true
	//      WHEN pm.kind IN ('owner', 'lead') THEN true
	//      ELSE false
	//    END as can_edit
	//  FROM "profile" p
	//  LEFT JOIN "profile_membership" pm ON p.id = pm.profile_id
	//    AND pm.deleted_at IS NULL
	//    AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
	//  LEFT JOIN "profile" up ON pm.member_profile_id = up.id AND up.deleted_at IS NULL
	//  LEFT JOIN "user" u ON up.id = u.individual_profile_id
	//  WHERE u.id = $1
	//    AND p.slug = $2
	//    AND p.deleted_at IS NULL
	//  LIMIT 1
	GetProfileOwnershipForUser(ctx context.Context, arg GetProfileOwnershipForUserParams) (*GetProfileOwnershipForUserRow, error)
	//GetProfilePage
	//
	//  SELECT id, profile_id, slug, "order", cover_picture_uri, published_at, created_at, updated_at, deleted_at
	//  FROM "profile_page"
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetProfilePage(ctx context.Context, arg GetProfilePageParams) (*ProfilePage, error)
	//GetProfilePageByProfileIDAndSlug
	//
	//  SELECT pp.id, pp.profile_id, pp.slug, pp."order", pp.cover_picture_uri, pp.published_at, pp.created_at, pp.updated_at, pp.deleted_at, ppt.profile_page_id, ppt.locale_code, ppt.title, ppt.summary, ppt.content, ppt.search_vector
	//  FROM "profile_page" pp
	//    INNER JOIN "profile_page_tx" ppt ON ppt.profile_page_id = pp.id
	//    AND ppt.locale_code = $1
	//  WHERE pp.profile_id = $2 AND pp.slug = $3 AND pp.deleted_at IS NULL
	//  ORDER BY pp."order"
	GetProfilePageByProfileIDAndSlug(ctx context.Context, arg GetProfilePageByProfileIDAndSlugParams) (*GetProfilePageByProfileIDAndSlugRow, error)
	//GetProfilePointTransactionByID
	//
	//  SELECT id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
	//  FROM "profile_point_transaction"
	//  WHERE id = $1
	GetProfilePointTransactionByID(ctx context.Context, arg GetProfilePointTransactionByIDParams) (*ProfilePointTransaction, error)
	//GetProfilePoints
	//
	//  SELECT points
	//  FROM "profile"
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetProfilePoints(ctx context.Context, arg GetProfilePointsParams) (int32, error)
	//GetProfileTxByID
	//
	//  SELECT pt.profile_id, pt.locale_code, pt.title, pt.description, pt.properties, pt.search_vector
	//  FROM "profile_tx" pt
	//  WHERE pt.profile_id = $1
	GetProfileTxByID(ctx context.Context, arg GetProfileTxByIDParams) ([]*GetProfileTxByIDRow, error)
	//GetProfilesByIDs
	//
	//  SELECT p.id, p.slug, p.kind, p.custom_domain, p.profile_picture_uri, p.pronouns, p.properties, p.created_at, p.updated_at, p.deleted_at, p.approved_at, p.points, pt.profile_id, pt.locale_code, pt.title, pt.description, pt.properties, pt.search_vector
	//  FROM "profile" p
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//    AND pt.locale_code = $1
	//  WHERE p.id = ANY($2::TEXT[])
	//    AND p.deleted_at IS NULL
	GetProfilesByIDs(ctx context.Context, arg GetProfilesByIDsParams) ([]*GetProfilesByIDsRow, error)
	//GetRuntimeState
	//
	//  SELECT key, value, updated_at
	//  FROM "runtime_state"
	//  WHERE key = $1
	//  LIMIT 1
	GetRuntimeState(ctx context.Context, arg GetRuntimeStateParams) (*RuntimeState, error)
	//GetSessionByID
	//
	//  SELECT
	//    id,
	//    status,
	//    oauth_request_state,
	//    oauth_request_code_verifier,
	//    oauth_redirect_uri,
	//    logged_in_user_id,
	//    logged_in_at,
	//    last_activity_at,
	//    user_agent,
	//    expires_at,
	//    created_at,
	//    updated_at
	//  FROM
	//    session
	//  WHERE
	//    id = $1
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (*GetSessionByIDRow, error)
	//GetSessionPreference
	//
	//  SELECT
	//    session_id,
	//    key,
	//    value,
	//    updated_at
	//  FROM
	//    session_preference
	//  WHERE
	//    session_id = $1
	//    AND key = $2
	GetSessionPreference(ctx context.Context, arg GetSessionPreferenceParams) (*SessionPreference, error)
	// Session Preferences
	//
	//
	//  SELECT
	//    session_id,
	//    key,
	//    value,
	//    updated_at
	//  FROM
	//    session_preference
	//  WHERE
	//    session_id = $1
	GetSessionPreferences(ctx context.Context, arg GetSessionPreferencesParams) ([]*SessionPreference, error)
	// Session Rate Limiting
	//
	//
	//  SELECT
	//    ip_hash,
	//    count,
	//    window_start
	//  FROM
	//    session_rate_limit
	//  WHERE
	//    ip_hash = $1
	GetSessionRateLimit(ctx context.Context, arg GetSessionRateLimitParams) (*SessionRateLimit, error)
	//GetStoryByID
	//
	//  SELECT
	//    s.id, s.author_profile_id, s.slug, s.kind, s.status, s.is_featured, s.story_picture_uri, s.properties, s.created_at, s.updated_at, s.deleted_at, s.published_at,
	//    st.story_id, st.locale_code, st.title, st.summary, st.content, st.search_vector,
	//    p.id, p.slug, p.kind, p.custom_domain, p.profile_picture_uri, p.pronouns, p.properties, p.created_at, p.updated_at, p.deleted_at, p.approved_at, p.points,
	//    pt.profile_id, pt.locale_code, pt.title, pt.description, pt.properties, pt.search_vector,
	//    pb.publications
	//  FROM "story" s
	//    INNER JOIN "story_tx" st ON st.story_id = s.id
	//    AND st.locale_code = $1
	//    LEFT JOIN "profile" p ON p.id = s.author_profile_id
	//    AND p.approved_at IS NOT NULL
	//    AND p.deleted_at IS NULL
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//    AND pt.locale_code = $1
	//    LEFT JOIN LATERAL (
	//      SELECT JSONB_AGG(
	//        JSONB_BUILD_OBJECT('profile', row_to_json(p2), 'profile_tx', row_to_json(p2t))
	//      ) AS "publications"
	//      FROM story_publication sp
	//        INNER JOIN "profile" p2 ON p2.id = sp.profile_id
	//        AND p2.deleted_at IS NULL
	//        INNER JOIN "profile_tx" p2t ON p2t.profile_id = p2.id
	//        AND p2t.locale_code = $1
	//      WHERE sp.story_id = s.id
	//        AND ($2::CHAR(26) IS NULL OR sp.profile_id = $2::CHAR(26))
	//        AND sp.deleted_at IS NULL
	//    ) pb ON TRUE
	//  WHERE s.id = $3
	//    AND ($4::CHAR(26) IS NULL OR s.author_profile_id = $4::CHAR(26))
	//    AND s.deleted_at IS NULL
	//  LIMIT 1
	GetStoryByID(ctx context.Context, arg GetStoryByIDParams) (*GetStoryByIDRow, error)
	//GetStoryForEdit
	//
	//  SELECT
	//    s.id, s.author_profile_id, s.slug, s.kind, s.status, s.is_featured, s.story_picture_uri, s.properties, s.created_at, s.updated_at, s.deleted_at, s.published_at,
	//    st.locale_code,
	//    st.title,
	//    st.summary,
	//    st.content
	//  FROM "story" s
	//    INNER JOIN "story_tx" st ON st.story_id = s.id
	//    AND st.locale_code = $1
	//  WHERE s.id = $2
	//    AND s.deleted_at IS NULL
	//  LIMIT 1
	GetStoryForEdit(ctx context.Context, arg GetStoryForEditParams) (*GetStoryForEditRow, error)
	//GetStoryIDBySlug
	//
	//  SELECT id
	//  FROM "story"
	//  WHERE slug = $1
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetStoryIDBySlug(ctx context.Context, arg GetStoryIDBySlugParams) (string, error)
	//GetStoryIDBySlugIncludingDeleted
	//
	//  SELECT id
	//  FROM "story"
	//  WHERE slug = $1
	//  LIMIT 1
	GetStoryIDBySlugIncludingDeleted(ctx context.Context, arg GetStoryIDBySlugIncludingDeletedParams) (string, error)
	//GetStoryOwnershipForUser
	//
	//  SELECT
	//    s.id,
	//    s.slug,
	//    s.author_profile_id,
	//    u.kind as user_kind,
	//    CASE
	//      WHEN u.kind = 'admin' THEN true
	//      WHEN s.author_profile_id = u.individual_profile_id THEN true
	//      WHEN pm.kind IN ('owner', 'lead', 'editor') THEN true
	//      ELSE false
	//    END as can_edit
	//  FROM "story" s
	//  LEFT JOIN "user" u ON u.id = $1
	//  LEFT JOIN "profile_membership" pm ON s.author_profile_id = pm.profile_id
	//    AND pm.member_profile_id = u.individual_profile_id
	//    AND pm.deleted_at IS NULL
	//    AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
	//  WHERE s.id = $2
	//    AND s.deleted_at IS NULL
	//  LIMIT 1
	GetStoryOwnershipForUser(ctx context.Context, arg GetStoryOwnershipForUserParams) (*GetStoryOwnershipForUserRow, error)
	//GetUserByEmail
	//
	//  SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
	//  FROM "user"
	//  WHERE email = $1
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (*User, error)
	//GetUserByGitHubRemoteID
	//
	//  SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
	//  FROM "user"
	//  WHERE github_remote_id = $1
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetUserByGitHubRemoteID(ctx context.Context, arg GetUserByGitHubRemoteIDParams) (*User, error)
	//GetUserByID
	//
	//  SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
	//  FROM "user"
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//  LIMIT 1
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (*User, error)
	//GetUserProfilePermissions
	//
	//  SELECT
	//    p.id,
	//    p.slug,
	//    p.kind as profile_kind,
	//    COALESCE(pm.kind, '') as membership_kind,
	//    u.kind as user_kind
	//  FROM "profile" p
	//  LEFT JOIN "profile_membership" pm ON p.id = pm.profile_id AND pm.deleted_at IS NULL
	//  LEFT JOIN "profile" up ON pm.member_profile_id = up.id AND up.deleted_at IS NULL
	//  LEFT JOIN "user" u ON up.id = u.individual_profile_id
	//  WHERE u.id = $1
	//    AND p.deleted_at IS NULL
	//    AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
	GetUserProfilePermissions(ctx context.Context, arg GetUserProfilePermissionsParams) ([]*GetUserProfilePermissionsRow, error)
	// -- name: ListStories :many
	// SELECT sqlc.embed(s), sqlc.embed(st), sqlc.embed(p), sqlc.embed(pt)
	// FROM "story" s
	//   INNER JOIN "story_tx" st ON st.story_id = s.id
	//   AND (sqlc.narg(filter_kind)::TEXT IS NULL OR s.kind = ANY(string_to_array(sqlc.narg(filter_kind)::TEXT, ',')))
	//   AND (sqlc.narg(filter_author_profile_id)::CHAR(26) IS NULL OR s.author_profile_id = sqlc.narg(filter_author_profile_id)::CHAR(26))
	//   AND st.locale_code = sqlc.arg(locale_code)
	//   LEFT JOIN "profile" p ON p.id = s.author_profile_id AND p.deleted_at IS NULL
	//   INNER JOIN "profile_tx" pt ON pt.profile_id = p.id AND pt.locale_code = sqlc.arg(locale_code)
	// WHERE s.deleted_at IS NULL
	// ORDER BY s.created_at DESC;
	//
	//
	//  INSERT INTO "story" (
	//    id,
	//    author_profile_id,
	//    slug,
	//    kind,
	//    status,
	//    is_featured,
	//    story_picture_uri,
	//    properties,
	//    published_at,
	//    created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5,
	//    $6,
	//    $7,
	//    $8,
	//    $9,
	//    NOW()
	//  ) RETURNING id, author_profile_id, slug, kind, status, is_featured, story_picture_uri, properties, created_at, updated_at, deleted_at, published_at
	InsertStory(ctx context.Context, arg InsertStoryParams) (*Story, error)
	//InsertStoryPublication
	//
	//  INSERT INTO "story_publication" (
	//    id,
	//    story_id,
	//    profile_id,
	//    kind,
	//    properties,
	//    created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5,
	//    NOW()
	//  ) RETURNING id, story_id, profile_id, kind, properties, created_at, updated_at, deleted_at
	InsertStoryPublication(ctx context.Context, arg InsertStoryPublicationParams) (*StoryPublication, error)
	//InsertStoryTx
	//
	//  INSERT INTO "story_tx" (
	//    story_id,
	//    locale_code,
	//    title,
	//    summary,
	//    content
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5
	//  )
	InsertStoryTx(ctx context.Context, arg InsertStoryTxParams) error
	//ListAllProfileLinksByProfileID
	//
	//  SELECT
	//    pl.id,
	//    pl.kind,
	//    pl.public_id,
	//    pl.uri,
	//    pl.is_verified,
	//    pl.is_hidden,
	//    pl.is_featured,
	//    pl.visibility,
	//    COALESCE(plt.title, pl.title) as title,
	//    COALESCE(plt.group, '') as "group",
	//    COALESCE(plt.description, '') as description
	//  FROM "profile_link" pl
	//    LEFT JOIN "profile_link_tx" plt ON plt.profile_link_id = pl.id
	//      AND plt.locale_code = $1
	//  WHERE pl.profile_id = $2
	//    AND pl.is_hidden = FALSE
	//    AND pl.deleted_at IS NULL
	//  ORDER BY pl."order"
	ListAllProfileLinksByProfileID(ctx context.Context, arg ListAllProfileLinksByProfileIDParams) ([]*ListAllProfileLinksByProfileIDRow, error)
	//ListAllProfilesForAdmin
	//
	//  SELECT
	//    p.id,
	//    p.slug,
	//    p.kind,
	//    p.custom_domain,
	//    p.profile_picture_uri,
	//    p.pronouns,
	//    p.properties,
	//    p.created_at,
	//    p.updated_at,
	//    p.points,
	//    COALESCE(pt.title, '') as title,
	//    COALESCE(pt.description, '') as description,
	//    pt.profile_id IS NOT NULL as has_translation
	//  FROM "profile" p
	//    LEFT JOIN "profile_tx" pt ON pt.profile_id = p.id
	//    AND pt.locale_code = $1
	//  WHERE p.deleted_at IS NULL
	//    AND ($2::TEXT IS NULL OR p.kind = ANY(string_to_array($2::TEXT, ',')))
	//  ORDER BY p.created_at DESC
	//  LIMIT $4
	//  OFFSET $3
	ListAllProfilesForAdmin(ctx context.Context, arg ListAllProfilesForAdminParams) ([]*ListAllProfilesForAdminRow, error)
	//ListEventsByType
	//
	//  SELECT id, type, payload, status, retry_count, max_retries, visible_at, visibility_timeout_secs, started_at, completed_at, failed_at, created_at, updated_at, error_message, worker_id
	//  FROM "event_queue"
	//  WHERE type = $1
	//  ORDER BY created_at DESC
	//  LIMIT $2
	ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]*EventQueue, error)
	//ListFeaturedProfileLinksByProfileID
	//
	//  SELECT
	//    pl.id,
	//    pl.kind,
	//    pl.public_id,
	//    pl.uri,
	//    pl.is_verified,
	//    pl.is_hidden,
	//    pl.is_featured,
	//    pl.visibility,
	//    COALESCE(plt.title, pl.title) as title,
	//    COALESCE(plt.group, '') as "group",
	//    COALESCE(plt.description, '') as description
	//  FROM "profile_link" pl
	//    LEFT JOIN "profile_link_tx" plt ON plt.profile_link_id = pl.id
	//      AND plt.locale_code = $1
	//  WHERE pl.profile_id = $2
	//    AND pl.is_featured = TRUE
	//    AND pl.is_hidden = FALSE
	//    AND pl.deleted_at IS NULL
	//  ORDER BY pl."order"
	ListFeaturedProfileLinksByProfileID(ctx context.Context, arg ListFeaturedProfileLinksByProfileIDParams) ([]*ListFeaturedProfileLinksByProfileIDRow, error)
	//ListManagedLinksForKind
	//
	//  SELECT
	//    pl.id,
	//    pl.profile_id,
	//    pl.kind,
	//    pl.remote_id,
	//    pl.auth_access_token,
	//    pl.auth_access_token_expires_at,
	//    pl.auth_refresh_token
	//  FROM "profile_link" pl
	//    INNER JOIN "profile" p ON p.id = pl.profile_id
	//      AND p.deleted_at IS NULL
	//  WHERE pl.kind = $1
	//    AND pl.is_managed = TRUE
	//    AND pl.auth_access_token IS NOT NULL
	//    AND pl.deleted_at IS NULL
	//  ORDER BY pl.updated_at ASC NULLS FIRST
	//  LIMIT $2
	ListManagedLinksForKind(ctx context.Context, arg ListManagedLinksForKindParams) ([]*ListManagedLinksForKindRow, error)
	//ListPendingAwards
	//
	//  SELECT id, target_profile_id, triggering_event, description, amount, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
	//  FROM "profile_point_pending_award"
	//  WHERE ($1::text IS NULL OR status = $1)
	//  ORDER BY created_at DESC
	//  LIMIT $2
	ListPendingAwards(ctx context.Context, arg ListPendingAwardsParams) ([]*ProfilePointPendingAward, error)
	//ListPendingAwardsByStatus
	//
	//  SELECT id, target_profile_id, triggering_event, description, amount, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
	//  FROM "profile_point_pending_award"
	//  WHERE status = $1
	//  ORDER BY created_at DESC
	//  LIMIT $2
	ListPendingAwardsByStatus(ctx context.Context, arg ListPendingAwardsByStatusParams) ([]*ProfilePointPendingAward, error)
	//ListProfileLinksByProfileID
	//
	//  SELECT id, profile_id, kind, "order", is_managed, is_verified, is_hidden, remote_id, public_id, uri, title, auth_provider, auth_access_token_scope, auth_access_token, auth_access_token_expires_at, auth_refresh_token, auth_refresh_token_expires_at, properties, created_at, updated_at, deleted_at, visibility, is_featured
	//  FROM "profile_link"
	//  WHERE profile_id = $1
	//    AND is_hidden = FALSE
	//    AND deleted_at IS NULL
	//  ORDER BY "order"
	ListProfileLinksByProfileID(ctx context.Context, arg ListProfileLinksByProfileIDParams) ([]*ProfileLink, error)
	//ListProfileLinksByProfileIDIncludingHidden
	//
	//  SELECT id, profile_id, kind, "order", is_managed, is_verified, is_hidden, remote_id, public_id, uri, title, auth_provider, auth_access_token_scope, auth_access_token, auth_access_token_expires_at, auth_refresh_token, auth_refresh_token_expires_at, properties, created_at, updated_at, deleted_at, visibility, is_featured
	//  FROM "profile_link"
	//  WHERE profile_id = $1
	//    AND deleted_at IS NULL
	//  ORDER BY "order"
	ListProfileLinksByProfileIDIncludingHidden(ctx context.Context, arg ListProfileLinksByProfileIDIncludingHiddenParams) ([]*ProfileLink, error)
	//ListProfileLinksForKind
	//
	//  SELECT pl.id, pl.profile_id, pl.kind, pl."order", pl.is_managed, pl.is_verified, pl.is_hidden, pl.remote_id, pl.public_id, pl.uri, pl.title, pl.auth_provider, pl.auth_access_token_scope, pl.auth_access_token, pl.auth_access_token_expires_at, pl.auth_refresh_token, pl.auth_refresh_token_expires_at, pl.properties, pl.created_at, pl.updated_at, pl.deleted_at, pl.visibility, pl.is_featured
	//  FROM "profile_link" pl
	//    INNER JOIN "profile" p ON p.id = pl.profile_id
	//    AND p.deleted_at IS NULL
	//  WHERE pl.kind = $1
	//    AND pl.deleted_at IS NULL
	//  ORDER BY pl."order"
	ListProfileLinksForKind(ctx context.Context, arg ListProfileLinksForKindParams) ([]*ProfileLink, error)
	//ListProfileMemberships
	//
	//  SELECT
	//    pm.id, pm.profile_id, pm.member_profile_id, pm.kind, pm.properties, pm.started_at, pm.finished_at, pm.created_at, pm.updated_at, pm.deleted_at,
	//    p1.id, p1.slug, p1.kind, p1.custom_domain, p1.profile_picture_uri, p1.pronouns, p1.properties, p1.created_at, p1.updated_at, p1.deleted_at, p1.approved_at, p1.points,
	//    p1t.profile_id, p1t.locale_code, p1t.title, p1t.description, p1t.properties, p1t.search_vector,
	//    p2.id, p2.slug, p2.kind, p2.custom_domain, p2.profile_picture_uri, p2.pronouns, p2.properties, p2.created_at, p2.updated_at, p2.deleted_at, p2.approved_at, p2.points,
	//    p2t.profile_id, p2t.locale_code, p2t.title, p2t.description, p2t.properties, p2t.search_vector
	//  FROM
	//  	"profile_membership" pm
	//    INNER JOIN "profile" p1 ON p1.id = pm.profile_id
	//      AND ($1::TEXT IS NULL OR p1.kind = ANY(string_to_array($1::TEXT, ',')))
	//      AND p1.approved_at IS NOT NULL
	//      AND p1.deleted_at IS NULL
	//    INNER JOIN "profile_tx" p1t ON p1t.profile_id = p1.id
	//  	  AND p1t.locale_code = $2
	//    INNER JOIN "profile" p2 ON p2.id = pm.member_profile_id
	//      AND ($3::TEXT IS NULL OR p2.kind = ANY(string_to_array($3::TEXT, ',')))
	//      AND p2.approved_at IS NOT NULL
	//      AND p2.deleted_at IS NULL
	//    INNER JOIN "profile_tx" p2t ON p2t.profile_id = p2.id
	//  	  AND p2t.locale_code = $2
	//  WHERE pm.deleted_at IS NULL
	//      AND ($4::TEXT IS NULL OR pm.profile_id = $4::TEXT)
	//      AND ($5::TEXT IS NULL OR pm.member_profile_id = $5::TEXT)
	ListProfileMemberships(ctx context.Context, arg ListProfileMembershipsParams) ([]*ListProfileMembershipsRow, error)
	//ListProfilePagesByProfileID
	//
	//  SELECT pp.id, pp.profile_id, pp.slug, pp."order", pp.cover_picture_uri, pp.published_at, pp.created_at, pp.updated_at, pp.deleted_at, ppt.profile_page_id, ppt.locale_code, ppt.title, ppt.summary, ppt.content, ppt.search_vector
	//  FROM "profile_page" pp
	//    INNER JOIN "profile_page_tx" ppt ON ppt.profile_page_id = pp.id
	//    AND ppt.locale_code = $1
	//  WHERE pp.profile_id = $2
	//    AND pp.deleted_at IS NULL
	//  ORDER BY pp."order"
	ListProfilePagesByProfileID(ctx context.Context, arg ListProfilePagesByProfileIDParams) ([]*ListProfilePagesByProfileIDRow, error)
	//ListProfilePointTransactionsByProfileID
	//
	//  SELECT id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
	//  FROM "profile_point_transaction"
	//  WHERE target_profile_id = $1
	//  ORDER BY created_at DESC
	//  LIMIT $2
	ListProfilePointTransactionsByProfileID(ctx context.Context, arg ListProfilePointTransactionsByProfileIDParams) ([]*ProfilePointTransaction, error)
	//ListProfiles
	//
	//  SELECT p.id, p.slug, p.kind, p.custom_domain, p.profile_picture_uri, p.pronouns, p.properties, p.created_at, p.updated_at, p.deleted_at, p.approved_at, p.points, pt.profile_id, pt.locale_code, pt.title, pt.description, pt.properties, pt.search_vector
	//  FROM "profile" p
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//    AND pt.locale_code = $1
	//  WHERE ($2::TEXT IS NULL OR p.kind = ANY(string_to_array($2::TEXT, ',')))
	//    AND p.approved_at IS NOT NULL
	//    AND p.deleted_at IS NULL
	ListProfiles(ctx context.Context, arg ListProfilesParams) ([]*ListProfilesRow, error)
	//ListSessionsByUserID
	//
	//  SELECT
	//    id,
	//    status,
	//    oauth_request_state,
	//    oauth_request_code_verifier,
	//    oauth_redirect_uri,
	//    logged_in_user_id,
	//    logged_in_at,
	//    last_activity_at,
	//    user_agent,
	//    expires_at,
	//    created_at,
	//    updated_at
	//  FROM
	//    session
	//  WHERE
	//    logged_in_user_id = $1
	//  ORDER BY
	//    last_activity_at DESC NULLS LAST,
	//    created_at DESC
	ListSessionsByUserID(ctx context.Context, arg ListSessionsByUserIDParams) ([]*ListSessionsByUserIDRow, error)
	//ListStoriesOfPublication
	//
	//  SELECT
	//    s.id, s.author_profile_id, s.slug, s.kind, s.status, s.is_featured, s.story_picture_uri, s.properties, s.created_at, s.updated_at, s.deleted_at, s.published_at,
	//    st.story_id, st.locale_code, st.title, st.summary, st.content, st.search_vector,
	//    p1.id, p1.slug, p1.kind, p1.custom_domain, p1.profile_picture_uri, p1.pronouns, p1.properties, p1.created_at, p1.updated_at, p1.deleted_at, p1.approved_at, p1.points,
	//    p1t.profile_id, p1t.locale_code, p1t.title, p1t.description, p1t.properties, p1t.search_vector,
	//    pb.publications
	//  FROM "story" s
	//    INNER JOIN "story_tx" st ON st.story_id = s.id
	//    AND st.locale_code = $1
	//    LEFT JOIN "profile" p1 ON p1.id = s.author_profile_id
	//    AND p1.approved_at IS NOT NULL
	//    AND p1.deleted_at IS NULL
	//    INNER JOIN "profile_tx" p1t ON p1t.profile_id = p1.id
	//    AND p1t.locale_code = $1
	//    LEFT JOIN LATERAL (
	//      SELECT JSONB_AGG(
	//        JSONB_BUILD_OBJECT('profile', row_to_json(p2), 'profile_tx', row_to_json(p2t))
	//      ) AS "publications"
	//      FROM story_publication sp
	//        INNER JOIN "profile" p2 ON p2.id = sp.profile_id
	//        AND p2.approved_at IS NOT NULL
	//        AND p2.deleted_at IS NULL
	//        INNER JOIN "profile_tx" p2t ON p2t.profile_id = p2.id
	//        AND p2t.locale_code = $1
	//      WHERE sp.story_id = s.id
	//        AND ($2::CHAR(26) IS NULL OR sp.profile_id = $2::CHAR(26))
	//        AND sp.deleted_at IS NULL
	//    ) pb ON TRUE
	//  WHERE
	//    pb.publications IS NOT NULL
	//    AND ($3::TEXT IS NULL OR s.kind = ANY(string_to_array($3::TEXT, ',')))
	//    AND ($4::CHAR(26) IS NULL OR s.author_profile_id = $4::CHAR(26))
	//    AND s.deleted_at IS NULL
	//  ORDER BY s.created_at DESC
	ListStoriesOfPublication(ctx context.Context, arg ListStoriesOfPublicationParams) ([]*ListStoriesOfPublicationRow, error)
	//ListUsers
	//
	//  SELECT id, kind, name, email, phone, github_handle, github_remote_id, bsky_handle, bsky_remote_id, x_handle, x_remote_id, individual_profile_id, created_at, updated_at, deleted_at
	//  FROM "user"
	//  WHERE ($1::TEXT IS NULL OR kind = ANY(string_to_array($1::TEXT, ',')))
	//    AND deleted_at IS NULL
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error)
	//MarkLinkImportsDeletedExcept
	//
	//  UPDATE "profile_link_import"
	//  SET deleted_at = NOW()
	//  WHERE profile_link_id = $1
	//    AND deleted_at IS NULL
	//    AND remote_id IS NOT NULL
	//    AND remote_id != ALL($2::TEXT[])
	MarkLinkImportsDeletedExcept(ctx context.Context, arg MarkLinkImportsDeletedExceptParams) (int64, error)
	//MarkPOWChallengeUsed
	//
	//  UPDATE protection_pow_challenge
	//  SET
	//    used = TRUE
	//  WHERE
	//    id = $1
	MarkPOWChallengeUsed(ctx context.Context, arg MarkPOWChallengeUsedParams) error
	//RecordProfilePointTransaction
	//
	//  INSERT INTO "profile_point_transaction" (
	//    id,
	//    target_profile_id,
	//    origin_profile_id,
	//    transaction_type,
	//    triggering_event,
	//    description,
	//    amount,
	//    balance_after,
	//    created_at
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5,
	//    $6,
	//    $7,
	//    $8,
	//    NOW()
	//  ) RETURNING id, target_profile_id, origin_profile_id, transaction_type, triggering_event, description, amount, balance_after, created_at
	RecordProfilePointTransaction(ctx context.Context, arg RecordProfilePointTransactionParams) (*ProfilePointTransaction, error)
	//RejectPendingAward
	//
	//  UPDATE "profile_point_pending_award"
	//  SET
	//    status = 'rejected',
	//    reviewed_by = $1,
	//    reviewed_at = NOW(),
	//    rejection_reason = $2
	//  WHERE id = $3
	//    AND status = 'pending'
	RejectPendingAward(ctx context.Context, arg RejectPendingAwardParams) error
	//ReleaseAdvisoryLock
	//
	//  SELECT pg_advisory_unlock($1::BIGINT) AS released
	ReleaseAdvisoryLock(ctx context.Context, arg ReleaseAdvisoryLockParams) (bool, error)
	//RemoveAllFromCache
	//
	//  DELETE FROM "cache"
	RemoveAllFromCache(ctx context.Context) (int64, error)
	//RemoveExpiredFromCache
	//
	//  DELETE FROM "cache"
	//  WHERE updated_at < $1
	RemoveExpiredFromCache(ctx context.Context, arg RemoveExpiredFromCacheParams) (int64, error)
	//RemoveFromCache
	//
	//  DELETE FROM "cache"
	//  WHERE key = $1
	RemoveFromCache(ctx context.Context, arg RemoveFromCacheParams) (int64, error)
	//RemoveProfile
	//
	//  UPDATE "profile"
	//  SET deleted_at = NOW()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	RemoveProfile(ctx context.Context, arg RemoveProfileParams) (int64, error)
	//RemoveRuntimeState
	//
	//  DELETE FROM "runtime_state"
	//  WHERE key = $1
	RemoveRuntimeState(ctx context.Context, arg RemoveRuntimeStateParams) (int64, error)
	//RemoveStory
	//
	//  UPDATE "story"
	//  SET deleted_at = NOW()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	RemoveStory(ctx context.Context, arg RemoveStoryParams) (int64, error)
	//RemoveUser
	//
	//  UPDATE "user"
	//  SET deleted_at = NOW()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	RemoveUser(ctx context.Context, arg RemoveUserParams) (int64, error)
	//SearchProfilePages
	//
	//  SELECT
	//    pp.id,
	//    pp.slug,
	//    pp.profile_id,
	//    pp.cover_picture_uri,
	//    ppt.title,
	//    ppt.summary,
	//    p.slug as profile_slug,
	//    pt.title as profile_title,
	//    ts_rank(ppt.search_vector, plainto_tsquery(locale_to_regconfig($1), $2)) as rank
	//  FROM "profile_page" pp
	//    INNER JOIN "profile_page_tx" ppt ON ppt.profile_page_id = pp.id
	//      AND ppt.locale_code = $1
	//    INNER JOIN "profile" p ON p.id = pp.profile_id AND p.deleted_at IS NULL
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//      AND pt.locale_code = $1
	//  WHERE ppt.search_vector @@ plainto_tsquery(locale_to_regconfig($1), $2)
	//    AND pp.deleted_at IS NULL
	//    AND p.approved_at IS NOT NULL
	//    AND ($3::TEXT IS NULL OR p.slug = $3::TEXT)
	//  ORDER BY rank DESC
	//  LIMIT $4
	SearchProfilePages(ctx context.Context, arg SearchProfilePagesParams) ([]*SearchProfilePagesRow, error)
	//SearchProfiles
	//
	//  SELECT
	//    p.id,
	//    p.slug,
	//    p.kind,
	//    p.profile_picture_uri,
	//    pt.title,
	//    pt.description,
	//    ts_rank(pt.search_vector, plainto_tsquery(locale_to_regconfig($1), $2)) as rank
	//  FROM "profile" p
	//    INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
	//      AND pt.locale_code = $1
	//  WHERE pt.search_vector @@ plainto_tsquery(locale_to_regconfig($1), $2)
	//    AND p.approved_at IS NOT NULL
	//    AND p.deleted_at IS NULL
	//    AND ($3::TEXT IS NULL OR p.slug = $3::TEXT)
	//  ORDER BY rank DESC
	//  LIMIT $4
	SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]*SearchProfilesRow, error)
	//SearchStories
	//
	//  SELECT
	//    s.id,
	//    s.slug,
	//    s.kind,
	//    s.story_picture_uri,
	//    s.author_profile_id,
	//    st.title,
	//    st.summary,
	//    p.slug as author_slug,
	//    pt.title as author_title,
	//    ts_rank(st.search_vector, plainto_tsquery(locale_to_regconfig($1), $2)) as rank
	//  FROM "story" s
	//    INNER JOIN "story_tx" st ON st.story_id = s.id
	//      AND st.locale_code = $1
	//    LEFT JOIN "profile" p ON p.id = s.author_profile_id AND p.deleted_at IS NULL
	//    LEFT JOIN "profile_tx" pt ON pt.profile_id = p.id
	//      AND pt.locale_code = $1
	//  WHERE st.search_vector @@ plainto_tsquery(locale_to_regconfig($1), $2)
	//    AND s.deleted_at IS NULL
	//    AND s.status = 'published'
	//    AND ($3::TEXT IS NULL OR p.slug = $3::TEXT)
	//  ORDER BY rank DESC
	//  LIMIT $4
	SearchStories(ctx context.Context, arg SearchStoriesParams) ([]*SearchStoriesRow, error)
	//SetInCache
	//
	//  INSERT INTO "cache" (key, value, updated_at)
	//  VALUES ($1, $2, NOW())
	//  ON CONFLICT ("key") DO UPDATE SET value = $2, updated_at = NOW()
	SetInCache(ctx context.Context, arg SetInCacheParams) (int64, error)
	//SetRuntimeState
	//
	//  INSERT INTO "runtime_state" (key, value, updated_at)
	//  VALUES ($1, $2, NOW())
	//  ON CONFLICT ("key") DO UPDATE SET value = $2, updated_at = NOW()
	SetRuntimeState(ctx context.Context, arg SetRuntimeStateParams) error
	//SetSessionPreference
	//
	//  INSERT INTO
	//    session_preference (session_id, key, value, updated_at)
	//  VALUES
	//    (
	//      $1,
	//      $2,
	//      $3,
	//      NOW()
	//    )
	//  ON CONFLICT (session_id, key) DO UPDATE
	//  SET
	//    value = $3,
	//    updated_at = NOW()
	SetSessionPreference(ctx context.Context, arg SetSessionPreferenceParams) error
	//SetUserIndividualProfileID
	//
	//  UPDATE "user"
	//  SET individual_profile_id = $1
	//  WHERE id = $2
	//    AND deleted_at IS NULL
	SetUserIndividualProfileID(ctx context.Context, arg SetUserIndividualProfileIDParams) (int64, error)
	//TerminateSession
	//
	//  UPDATE
	//    session
	//  SET
	//    status = 'terminated',
	//    updated_at = NOW()
	//  WHERE
	//    id = $1
	//    AND logged_in_user_id = $2
	TerminateSession(ctx context.Context, arg TerminateSessionParams) error
	//TryAdvisoryLock
	//
	//  SELECT pg_try_advisory_lock($1::BIGINT) AS acquired
	TryAdvisoryLock(ctx context.Context, arg TryAdvisoryLockParams) (bool, error)
	//UpdateLinkImport
	//
	//  UPDATE "profile_link_import"
	//  SET
	//    properties = $1,
	//    updated_at = NOW(),
	//    deleted_at = NULL
	//  WHERE id = $2
	UpdateLinkImport(ctx context.Context, arg UpdateLinkImportParams) (int64, error)
	//UpdateProfile
	//
	//  UPDATE "profile"
	//  SET
	//    profile_picture_uri = COALESCE($1, profile_picture_uri),
	//    pronouns = COALESCE($2, pronouns),
	//    properties = COALESCE($3, properties),
	//    updated_at = NOW()
	//  WHERE id = $4
	//    AND deleted_at IS NULL
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (int64, error)
	//UpdateProfileLink
	//
	//  UPDATE "profile_link"
	//  SET
	//    kind = $1,
	//    "order" = $2,
	//    uri = $3,
	//    title = $4,
	//    is_hidden = $5,
	//    is_featured = $6,
	//    visibility = $7,
	//    updated_at = NOW()
	//  WHERE id = $8
	//    AND deleted_at IS NULL
	UpdateProfileLink(ctx context.Context, arg UpdateProfileLinkParams) (int64, error)
	//UpdateProfileLinkOAuthTokens
	//
	//  UPDATE "profile_link"
	//  SET
	//    public_id = $1,
	//    uri = $2,
	//    title = $3,
	//    auth_access_token = $4,
	//    auth_access_token_expires_at = $5,
	//    auth_refresh_token = $6,
	//    auth_access_token_scope = $7,
	//    is_verified = TRUE,
	//    updated_at = NOW()
	//  WHERE id = $8
	//    AND deleted_at IS NULL
	UpdateProfileLinkOAuthTokens(ctx context.Context, arg UpdateProfileLinkOAuthTokensParams) (int64, error)
	//UpdateProfileLinkTokens
	//
	//  UPDATE "profile_link"
	//  SET
	//    auth_access_token = $1,
	//    auth_access_token_expires_at = $2,
	//    auth_refresh_token = $3,
	//    updated_at = NOW()
	//  WHERE id = $4
	//    AND deleted_at IS NULL
	UpdateProfileLinkTokens(ctx context.Context, arg UpdateProfileLinkTokensParams) (int64, error)
	//UpdateProfileLinkTx
	//
	//  UPDATE "profile_link_tx"
	//  SET
	//    title = $1,
	//    "group" = $2,
	//    description = $3
	//  WHERE profile_link_id = $4
	//    AND locale_code = $5
	UpdateProfileLinkTx(ctx context.Context, arg UpdateProfileLinkTxParams) (int64, error)
	//UpdateProfilePage
	//
	//  UPDATE "profile_page"
	//  SET
	//    slug = $1,
	//    "order" = $2,
	//    cover_picture_uri = $3,
	//    published_at = $4,
	//    updated_at = NOW()
	//  WHERE id = $5
	//    AND deleted_at IS NULL
	UpdateProfilePage(ctx context.Context, arg UpdateProfilePageParams) (int64, error)
	//UpdateProfilePageTx
	//
	//  UPDATE "profile_page_tx"
	//  SET
	//    title = $1,
	//    summary = $2,
	//    content = $3
	//  WHERE profile_page_id = $4
	//    AND locale_code = $5
	UpdateProfilePageTx(ctx context.Context, arg UpdateProfilePageTxParams) (int64, error)
	//UpdateProfileTx
	//
	//  UPDATE "profile_tx"
	//  SET
	//    title = $1,
	//    description = $2,
	//    properties = $3
	//  WHERE profile_id = $4
	//    AND locale_code = $5
	UpdateProfileTx(ctx context.Context, arg UpdateProfileTxParams) (int64, error)
	//UpdateSessionActivity
	//
	//  UPDATE
	//    session
	//  SET
	//    last_activity_at = NOW(),
	//    user_agent = COALESCE($1, user_agent),
	//    updated_at = NOW()
	//  WHERE
	//    id = $2
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	//UpdateSessionLoggedInAt
	//
	//  UPDATE
	//    session
	//  SET
	//    logged_in_at = $1,
	//    updated_at = NOW()
	//  WHERE
	//    id = $2
	UpdateSessionLoggedInAt(ctx context.Context, arg UpdateSessionLoggedInAtParams) error
	//UpdateSessionStatus
	//
	//  UPDATE
	//    session
	//  SET
	//    status = $1,
	//    updated_at = NOW()
	//  WHERE
	//    id = $2
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	//UpdateStory
	//
	//  UPDATE "story"
	//  SET
	//    slug = $1,
	//    status = $2,
	//    is_featured = $3,
	//    story_picture_uri = $4,
	//    published_at = $5,
	//    updated_at = NOW()
	//  WHERE id = $6
	//    AND deleted_at IS NULL
	UpdateStory(ctx context.Context, arg UpdateStoryParams) (int64, error)
	//UpdateStoryTx
	//
	//  UPDATE "story_tx"
	//  SET
	//    title = $1,
	//    summary = $2,
	//    content = $3
	//  WHERE story_id = $4
	//    AND locale_code = $5
	UpdateStoryTx(ctx context.Context, arg UpdateStoryTxParams) (int64, error)
	//UpdateUser
	//
	//  UPDATE "user"
	//  SET kind = $1,
	//    NAME = $2,
	//    email = $3,
	//    phone = $4,
	//    github_handle = $5,
	//    github_remote_id = $6,
	//    bsky_handle = $7,
	//    bsky_remote_id = $8,
	//    x_handle = $9,
	//    x_remote_id = $10,
	//    individual_profile_id = $11
	//  WHERE id = $12
	//    AND deleted_at IS NULL
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
	//UpsertProfileLinkTx
	//
	//  INSERT INTO "profile_link_tx" (
	//    profile_link_id,
	//    locale_code,
	//    title,
	//    "group",
	//    description
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5
	//  ) ON CONFLICT (profile_link_id, locale_code) DO UPDATE SET
	//    title = EXCLUDED.title,
	//    "group" = EXCLUDED."group",
	//    description = EXCLUDED.description
	UpsertProfileLinkTx(ctx context.Context, arg UpsertProfileLinkTxParams) error
	//UpsertProfilePageTx
	//
	//  INSERT INTO "profile_page_tx" (
	//    profile_page_id,
	//    locale_code,
	//    title,
	//    summary,
	//    content
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5
	//  ) ON CONFLICT (profile_page_id, locale_code) DO UPDATE SET
	//    title = EXCLUDED.title,
	//    summary = EXCLUDED.summary,
	//    content = EXCLUDED.content
	UpsertProfilePageTx(ctx context.Context, arg UpsertProfilePageTxParams) error
	//UpsertProfileTx
	//
	//  INSERT INTO "profile_tx" (profile_id, locale_code, title, description, properties)
	//  VALUES ($1, $2, $3, $4, $5)
	//  ON CONFLICT (profile_id, locale_code)
	//  DO UPDATE SET
	//    title = EXCLUDED.title,
	//    description = EXCLUDED.description,
	//    properties = EXCLUDED.properties
	UpsertProfileTx(ctx context.Context, arg UpsertProfileTxParams) error
	//UpsertSessionRateLimit
	//
	//  INSERT INTO
	//    session_rate_limit (ip_hash, count, window_start)
	//  VALUES
	//    ($1, 1, NOW())
	//  ON CONFLICT (ip_hash) DO UPDATE
	//  SET
	//    count = CASE
	//      WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
	//      THEN 1
	//      ELSE session_rate_limit.count + 1
	//    END,
	//    window_start = CASE
	//      WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
	//      THEN NOW()
	//      ELSE session_rate_limit.window_start
	//    END
	UpsertSessionRateLimit(ctx context.Context, arg UpsertSessionRateLimitParams) error
	//UpsertStoryTx
	//
	//  INSERT INTO "story_tx" (
	//    story_id,
	//    locale_code,
	//    title,
	//    summary,
	//    content
	//  ) VALUES (
	//    $1,
	//    $2,
	//    $3,
	//    $4,
	//    $5
	//  ) ON CONFLICT (story_id, locale_code) DO UPDATE SET
	//    title = EXCLUDED.title,
	//    summary = EXCLUDED.summary,
	//    content = EXCLUDED.content
	UpsertStoryTx(ctx context.Context, arg UpsertStoryTxParams) error
}

var _ Querier = (*Queries)(nil)
