// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredSessionRateLimits = `-- name: CleanupExpiredSessionRateLimits :exec
DELETE FROM session_rate_limit
WHERE
  window_start < NOW() - INTERVAL '2 hours'
`

// CleanupExpiredSessionRateLimits
//
//	DELETE FROM session_rate_limit
//	WHERE
//	  window_start < NOW() - INTERVAL '2 hours'
func (q *Queries) CleanupExpiredSessionRateLimits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessionRateLimits)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO
  session (
    id,
    status,
    oauth_request_state,
    oauth_request_code_verifier,
    oauth_redirect_uri,
    logged_in_user_id,
    logged_in_at,
    expires_at,
    created_at,
    updated_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
  )
`

type CreateSessionParams struct {
	ID                       string         `db:"id" json:"id"`
	Status                   string         `db:"status" json:"status"`
	OauthRequestState        string         `db:"oauth_request_state" json:"oauth_request_state"`
	OauthRequestCodeVerifier string         `db:"oauth_request_code_verifier" json:"oauth_request_code_verifier"`
	OauthRedirectURI         sql.NullString `db:"oauth_redirect_uri" json:"oauth_redirect_uri"`
	LoggedInUserID           sql.NullString `db:"logged_in_user_id" json:"logged_in_user_id"`
	LoggedInAt               sql.NullTime   `db:"logged_in_at" json:"logged_in_at"`
	ExpiresAt                sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt                time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                sql.NullTime   `db:"updated_at" json:"updated_at"`
}

// CreateSession
//
//	INSERT INTO
//	  session (
//	    id,
//	    status,
//	    oauth_request_state,
//	    oauth_request_code_verifier,
//	    oauth_redirect_uri,
//	    logged_in_user_id,
//	    logged_in_at,
//	    expires_at,
//	    created_at,
//	    updated_at
//	  )
//	VALUES
//	  (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10
//	  )
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Status,
		arg.OauthRequestState,
		arg.OauthRequestCodeVerifier,
		arg.OauthRedirectURI,
		arg.LoggedInUserID,
		arg.LoggedInAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAllSessionPreferences = `-- name: DeleteAllSessionPreferences :exec
DELETE FROM session_preference
WHERE
  session_id = $1
`

type DeleteAllSessionPreferencesParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

// DeleteAllSessionPreferences
//
//	DELETE FROM session_preference
//	WHERE
//	  session_id = $1
func (q *Queries) DeleteAllSessionPreferences(ctx context.Context, arg DeleteAllSessionPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionPreferences, arg.SessionID)
	return err
}

const deleteSessionPreference = `-- name: DeleteSessionPreference :exec
DELETE FROM session_preference
WHERE
  session_id = $1
  AND key = $2
`

type DeleteSessionPreferenceParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Key       string `db:"key" json:"key"`
}

// DeleteSessionPreference
//
//	DELETE FROM session_preference
//	WHERE
//	  session_id = $1
//	  AND key = $2
func (q *Queries) DeleteSessionPreference(ctx context.Context, arg DeleteSessionPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPreference, arg.SessionID, arg.Key)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id,
  status,
  oauth_request_state,
  oauth_request_code_verifier,
  oauth_redirect_uri,
  logged_in_user_id,
  logged_in_at,
  expires_at,
  created_at,
  updated_at
FROM
  session
WHERE
  id = $1
`

type GetSessionByIDParams struct {
	ID string `db:"id" json:"id"`
}

// GetSessionByID
//
//	SELECT
//	  id,
//	  status,
//	  oauth_request_state,
//	  oauth_request_code_verifier,
//	  oauth_redirect_uri,
//	  logged_in_user_id,
//	  logged_in_at,
//	  expires_at,
//	  created_at,
//	  updated_at
//	FROM
//	  session
//	WHERE
//	  id = $1
func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (*Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OauthRequestState,
		&i.OauthRequestCodeVerifier,
		&i.OauthRedirectURI,
		&i.LoggedInUserID,
		&i.LoggedInAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSessionPreference = `-- name: GetSessionPreference :one
SELECT
  session_id,
  key,
  value,
  updated_at
FROM
  session_preference
WHERE
  session_id = $1
  AND key = $2
`

type GetSessionPreferenceParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Key       string `db:"key" json:"key"`
}

// GetSessionPreference
//
//	SELECT
//	  session_id,
//	  key,
//	  value,
//	  updated_at
//	FROM
//	  session_preference
//	WHERE
//	  session_id = $1
//	  AND key = $2
func (q *Queries) GetSessionPreference(ctx context.Context, arg GetSessionPreferenceParams) (*SessionPreference, error) {
	row := q.db.QueryRowContext(ctx, getSessionPreference, arg.SessionID, arg.Key)
	var i SessionPreference
	err := row.Scan(
		&i.SessionID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSessionPreferences = `-- name: GetSessionPreferences :many

SELECT
  session_id,
  key,
  value,
  updated_at
FROM
  session_preference
WHERE
  session_id = $1
`

type GetSessionPreferencesParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

// Session Preferences
//
//	SELECT
//	  session_id,
//	  key,
//	  value,
//	  updated_at
//	FROM
//	  session_preference
//	WHERE
//	  session_id = $1
func (q *Queries) GetSessionPreferences(ctx context.Context, arg GetSessionPreferencesParams) ([]*SessionPreference, error) {
	rows, err := q.db.QueryContext(ctx, getSessionPreferences, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SessionPreference{}
	for rows.Next() {
		var i SessionPreference
		if err := rows.Scan(
			&i.SessionID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionRateLimit = `-- name: GetSessionRateLimit :one

SELECT
  ip_hash,
  count,
  window_start
FROM
  session_rate_limit
WHERE
  ip_hash = $1
`

type GetSessionRateLimitParams struct {
	IpHash string `db:"ip_hash" json:"ip_hash"`
}

// Session Rate Limiting
//
//	SELECT
//	  ip_hash,
//	  count,
//	  window_start
//	FROM
//	  session_rate_limit
//	WHERE
//	  ip_hash = $1
func (q *Queries) GetSessionRateLimit(ctx context.Context, arg GetSessionRateLimitParams) (*SessionRateLimit, error) {
	row := q.db.QueryRowContext(ctx, getSessionRateLimit, arg.IpHash)
	var i SessionRateLimit
	err := row.Scan(&i.IpHash, &i.Count, &i.WindowStart)
	return &i, err
}

const setSessionPreference = `-- name: SetSessionPreference :exec
INSERT INTO
  session_preference (session_id, key, value, updated_at)
VALUES
  (
    $1,
    $2,
    $3,
    NOW()
  )
ON CONFLICT (session_id, key) DO UPDATE
SET
  value = $3,
  updated_at = NOW()
`

type SetSessionPreferenceParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Key       string `db:"key" json:"key"`
	Value     string `db:"value" json:"value"`
}

// SetSessionPreference
//
//	INSERT INTO
//	  session_preference (session_id, key, value, updated_at)
//	VALUES
//	  (
//	    $1,
//	    $2,
//	    $3,
//	    NOW()
//	  )
//	ON CONFLICT (session_id, key) DO UPDATE
//	SET
//	  value = $3,
//	  updated_at = NOW()
func (q *Queries) SetSessionPreference(ctx context.Context, arg SetSessionPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, setSessionPreference, arg.SessionID, arg.Key, arg.Value)
	return err
}

const updateSessionLoggedInAt = `-- name: UpdateSessionLoggedInAt :exec
UPDATE
  session
SET
  logged_in_at = $1,
  updated_at = NOW()
WHERE
  id = $2
`

type UpdateSessionLoggedInAtParams struct {
	LoggedInAt sql.NullTime `db:"logged_in_at" json:"logged_in_at"`
	ID         string       `db:"id" json:"id"`
}

// UpdateSessionLoggedInAt
//
//	UPDATE
//	  session
//	SET
//	  logged_in_at = $1,
//	  updated_at = NOW()
//	WHERE
//	  id = $2
func (q *Queries) UpdateSessionLoggedInAt(ctx context.Context, arg UpdateSessionLoggedInAtParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLoggedInAt, arg.LoggedInAt, arg.ID)
	return err
}

const upsertSessionRateLimit = `-- name: UpsertSessionRateLimit :exec
INSERT INTO
  session_rate_limit (ip_hash, count, window_start)
VALUES
  ($1, 1, NOW())
ON CONFLICT (ip_hash) DO UPDATE
SET
  count = CASE
    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
    THEN 1
    ELSE session_rate_limit.count + 1
  END,
  window_start = CASE
    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
    THEN NOW()
    ELSE session_rate_limit.window_start
  END
`

type UpsertSessionRateLimitParams struct {
	IpHash string `db:"ip_hash" json:"ip_hash"`
}

// UpsertSessionRateLimit
//
//	INSERT INTO
//	  session_rate_limit (ip_hash, count, window_start)
//	VALUES
//	  ($1, 1, NOW())
//	ON CONFLICT (ip_hash) DO UPDATE
//	SET
//	  count = CASE
//	    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
//	    THEN 1
//	    ELSE session_rate_limit.count + 1
//	  END,
//	  window_start = CASE
//	    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
//	    THEN NOW()
//	    ELSE session_rate_limit.window_start
//	  END
func (q *Queries) UpsertSessionRateLimit(ctx context.Context, arg UpsertSessionRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionRateLimit, arg.IpHash)
	return err
}
