// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredSessionRateLimits = `-- name: CleanupExpiredSessionRateLimits :exec
DELETE FROM session_rate_limit
WHERE
  window_start < NOW() - INTERVAL '2 hours'
`

// CleanupExpiredSessionRateLimits
//
//	DELETE FROM session_rate_limit
//	WHERE
//	  window_start < NOW() - INTERVAL '2 hours'
func (q *Queries) CleanupExpiredSessionRateLimits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessionRateLimits)
	return err
}

const copySessionPreferences = `-- name: CopySessionPreferences :exec
INSERT INTO
  session_preference (session_id, key, value, updated_at)
SELECT
  $1,
  sp.key,
  sp.value,
  NOW()
FROM
  session_preference sp
WHERE
  sp.session_id = $2
ON CONFLICT (session_id, key) DO UPDATE
SET
  value = EXCLUDED.value,
  updated_at = NOW()
`

type CopySessionPreferencesParams struct {
	NewSessionID string `db:"new_session_id" json:"new_session_id"`
	OldSessionID string `db:"old_session_id" json:"old_session_id"`
}

// CopySessionPreferences
//
//	INSERT INTO
//	  session_preference (session_id, key, value, updated_at)
//	SELECT
//	  $1,
//	  sp.key,
//	  sp.value,
//	  NOW()
//	FROM
//	  session_preference sp
//	WHERE
//	  sp.session_id = $2
//	ON CONFLICT (session_id, key) DO UPDATE
//	SET
//	  value = EXCLUDED.value,
//	  updated_at = NOW()
func (q *Queries) CopySessionPreferences(ctx context.Context, arg CopySessionPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, copySessionPreferences, arg.NewSessionID, arg.OldSessionID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO
  session (
    id,
    status,
    oauth_request_state,
    oauth_request_code_verifier,
    oauth_redirect_uri,
    logged_in_user_id,
    logged_in_at,
    last_activity_at,
    user_agent,
    expires_at,
    created_at,
    updated_at,
    oauth_provider,
    oauth_access_token,
    oauth_token_scope
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
  )
`

type CreateSessionParams struct {
	ID                       string         `db:"id" json:"id"`
	Status                   string         `db:"status" json:"status"`
	OauthRequestState        string         `db:"oauth_request_state" json:"oauth_request_state"`
	OauthRequestCodeVerifier string         `db:"oauth_request_code_verifier" json:"oauth_request_code_verifier"`
	OauthRedirectURI         sql.NullString `db:"oauth_redirect_uri" json:"oauth_redirect_uri"`
	LoggedInUserID           sql.NullString `db:"logged_in_user_id" json:"logged_in_user_id"`
	LoggedInAt               sql.NullTime   `db:"logged_in_at" json:"logged_in_at"`
	LastActivityAt           sql.NullTime   `db:"last_activity_at" json:"last_activity_at"`
	UserAgent                sql.NullString `db:"user_agent" json:"user_agent"`
	ExpiresAt                sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt                time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                sql.NullTime   `db:"updated_at" json:"updated_at"`
	OauthProvider            sql.NullString `db:"oauth_provider" json:"oauth_provider"`
	OauthAccessToken         sql.NullString `db:"oauth_access_token" json:"oauth_access_token"`
	OauthTokenScope          sql.NullString `db:"oauth_token_scope" json:"oauth_token_scope"`
}

// CreateSession
//
//	INSERT INTO
//	  session (
//	    id,
//	    status,
//	    oauth_request_state,
//	    oauth_request_code_verifier,
//	    oauth_redirect_uri,
//	    logged_in_user_id,
//	    logged_in_at,
//	    last_activity_at,
//	    user_agent,
//	    expires_at,
//	    created_at,
//	    updated_at,
//	    oauth_provider,
//	    oauth_access_token,
//	    oauth_token_scope
//	  )
//	VALUES
//	  (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14,
//	    $15
//	  )
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Status,
		arg.OauthRequestState,
		arg.OauthRequestCodeVerifier,
		arg.OauthRedirectURI,
		arg.LoggedInUserID,
		arg.LoggedInAt,
		arg.LastActivityAt,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OauthProvider,
		arg.OauthAccessToken,
		arg.OauthTokenScope,
	)
	return err
}

const deleteAllSessionPreferences = `-- name: DeleteAllSessionPreferences :exec
DELETE FROM session_preference
WHERE
  session_id = $1
`

type DeleteAllSessionPreferencesParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

// DeleteAllSessionPreferences
//
//	DELETE FROM session_preference
//	WHERE
//	  session_id = $1
func (q *Queries) DeleteAllSessionPreferences(ctx context.Context, arg DeleteAllSessionPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionPreferences, arg.SessionID)
	return err
}

const deleteSessionPreference = `-- name: DeleteSessionPreference :exec
DELETE FROM session_preference
WHERE
  session_id = $1
  AND key = $2
`

type DeleteSessionPreferenceParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Key       string `db:"key" json:"key"`
}

// DeleteSessionPreference
//
//	DELETE FROM session_preference
//	WHERE
//	  session_id = $1
//	  AND key = $2
func (q *Queries) DeleteSessionPreference(ctx context.Context, arg DeleteSessionPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPreference, arg.SessionID, arg.Key)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id,
  status,
  oauth_request_state,
  oauth_request_code_verifier,
  oauth_redirect_uri,
  logged_in_user_id,
  logged_in_at,
  last_activity_at,
  user_agent,
  expires_at,
  created_at,
  updated_at,
  oauth_provider,
  oauth_access_token,
  oauth_token_scope
FROM
  session
WHERE
  id = $1
`

type GetSessionByIDParams struct {
	ID string `db:"id" json:"id"`
}

type GetSessionByIDRow struct {
	ID                       string         `db:"id" json:"id"`
	Status                   string         `db:"status" json:"status"`
	OauthRequestState        string         `db:"oauth_request_state" json:"oauth_request_state"`
	OauthRequestCodeVerifier string         `db:"oauth_request_code_verifier" json:"oauth_request_code_verifier"`
	OauthRedirectURI         sql.NullString `db:"oauth_redirect_uri" json:"oauth_redirect_uri"`
	LoggedInUserID           sql.NullString `db:"logged_in_user_id" json:"logged_in_user_id"`
	LoggedInAt               sql.NullTime   `db:"logged_in_at" json:"logged_in_at"`
	LastActivityAt           sql.NullTime   `db:"last_activity_at" json:"last_activity_at"`
	UserAgent                sql.NullString `db:"user_agent" json:"user_agent"`
	ExpiresAt                sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt                time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                sql.NullTime   `db:"updated_at" json:"updated_at"`
	OauthProvider            sql.NullString `db:"oauth_provider" json:"oauth_provider"`
	OauthAccessToken         sql.NullString `db:"oauth_access_token" json:"oauth_access_token"`
	OauthTokenScope          sql.NullString `db:"oauth_token_scope" json:"oauth_token_scope"`
}

// GetSessionByID
//
//	SELECT
//	  id,
//	  status,
//	  oauth_request_state,
//	  oauth_request_code_verifier,
//	  oauth_redirect_uri,
//	  logged_in_user_id,
//	  logged_in_at,
//	  last_activity_at,
//	  user_agent,
//	  expires_at,
//	  created_at,
//	  updated_at,
//	  oauth_provider,
//	  oauth_access_token,
//	  oauth_token_scope
//	FROM
//	  session
//	WHERE
//	  id = $1
func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (*GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, arg.ID)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OauthRequestState,
		&i.OauthRequestCodeVerifier,
		&i.OauthRedirectURI,
		&i.LoggedInUserID,
		&i.LoggedInAt,
		&i.LastActivityAt,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthProvider,
		&i.OauthAccessToken,
		&i.OauthTokenScope,
	)
	return &i, err
}

const getSessionPreference = `-- name: GetSessionPreference :one
SELECT
  session_id,
  key,
  value,
  updated_at
FROM
  session_preference
WHERE
  session_id = $1
  AND key = $2
`

type GetSessionPreferenceParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Key       string `db:"key" json:"key"`
}

// GetSessionPreference
//
//	SELECT
//	  session_id,
//	  key,
//	  value,
//	  updated_at
//	FROM
//	  session_preference
//	WHERE
//	  session_id = $1
//	  AND key = $2
func (q *Queries) GetSessionPreference(ctx context.Context, arg GetSessionPreferenceParams) (*SessionPreference, error) {
	row := q.db.QueryRowContext(ctx, getSessionPreference, arg.SessionID, arg.Key)
	var i SessionPreference
	err := row.Scan(
		&i.SessionID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSessionPreferences = `-- name: GetSessionPreferences :many

SELECT
  session_id,
  key,
  value,
  updated_at
FROM
  session_preference
WHERE
  session_id = $1
`

type GetSessionPreferencesParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

// Session Preferences
//
//	SELECT
//	  session_id,
//	  key,
//	  value,
//	  updated_at
//	FROM
//	  session_preference
//	WHERE
//	  session_id = $1
func (q *Queries) GetSessionPreferences(ctx context.Context, arg GetSessionPreferencesParams) ([]*SessionPreference, error) {
	rows, err := q.db.QueryContext(ctx, getSessionPreferences, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SessionPreference{}
	for rows.Next() {
		var i SessionPreference
		if err := rows.Scan(
			&i.SessionID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionRateLimit = `-- name: GetSessionRateLimit :one

SELECT
  ip_hash,
  count,
  window_start
FROM
  session_rate_limit
WHERE
  ip_hash = $1
`

type GetSessionRateLimitParams struct {
	IpHash string `db:"ip_hash" json:"ip_hash"`
}

// Session Rate Limiting
//
//	SELECT
//	  ip_hash,
//	  count,
//	  window_start
//	FROM
//	  session_rate_limit
//	WHERE
//	  ip_hash = $1
func (q *Queries) GetSessionRateLimit(ctx context.Context, arg GetSessionRateLimitParams) (*SessionRateLimit, error) {
	row := q.db.QueryRowContext(ctx, getSessionRateLimit, arg.IpHash)
	var i SessionRateLimit
	err := row.Scan(&i.IpHash, &i.Count, &i.WindowStart)
	return &i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT
  id,
  status,
  oauth_request_state,
  oauth_request_code_verifier,
  oauth_redirect_uri,
  logged_in_user_id,
  logged_in_at,
  last_activity_at,
  user_agent,
  expires_at,
  created_at,
  updated_at,
  oauth_provider,
  oauth_access_token,
  oauth_token_scope
FROM
  session
WHERE
  logged_in_user_id = $1
ORDER BY
  last_activity_at DESC NULLS LAST,
  created_at DESC
`

type ListSessionsByUserIDParams struct {
	UserID sql.NullString `db:"user_id" json:"user_id"`
}

type ListSessionsByUserIDRow struct {
	ID                       string         `db:"id" json:"id"`
	Status                   string         `db:"status" json:"status"`
	OauthRequestState        string         `db:"oauth_request_state" json:"oauth_request_state"`
	OauthRequestCodeVerifier string         `db:"oauth_request_code_verifier" json:"oauth_request_code_verifier"`
	OauthRedirectURI         sql.NullString `db:"oauth_redirect_uri" json:"oauth_redirect_uri"`
	LoggedInUserID           sql.NullString `db:"logged_in_user_id" json:"logged_in_user_id"`
	LoggedInAt               sql.NullTime   `db:"logged_in_at" json:"logged_in_at"`
	LastActivityAt           sql.NullTime   `db:"last_activity_at" json:"last_activity_at"`
	UserAgent                sql.NullString `db:"user_agent" json:"user_agent"`
	ExpiresAt                sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt                time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                sql.NullTime   `db:"updated_at" json:"updated_at"`
	OauthProvider            sql.NullString `db:"oauth_provider" json:"oauth_provider"`
	OauthAccessToken         sql.NullString `db:"oauth_access_token" json:"oauth_access_token"`
	OauthTokenScope          sql.NullString `db:"oauth_token_scope" json:"oauth_token_scope"`
}

// ListSessionsByUserID
//
//	SELECT
//	  id,
//	  status,
//	  oauth_request_state,
//	  oauth_request_code_verifier,
//	  oauth_redirect_uri,
//	  logged_in_user_id,
//	  logged_in_at,
//	  last_activity_at,
//	  user_agent,
//	  expires_at,
//	  created_at,
//	  updated_at,
//	  oauth_provider,
//	  oauth_access_token,
//	  oauth_token_scope
//	FROM
//	  session
//	WHERE
//	  logged_in_user_id = $1
//	ORDER BY
//	  last_activity_at DESC NULLS LAST,
//	  created_at DESC
func (q *Queries) ListSessionsByUserID(ctx context.Context, arg ListSessionsByUserIDParams) ([]*ListSessionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListSessionsByUserIDRow{}
	for rows.Next() {
		var i ListSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.OauthRequestState,
			&i.OauthRequestCodeVerifier,
			&i.OauthRedirectURI,
			&i.LoggedInUserID,
			&i.LoggedInAt,
			&i.LastActivityAt,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OauthProvider,
			&i.OauthAccessToken,
			&i.OauthTokenScope,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionPreference = `-- name: SetSessionPreference :exec
INSERT INTO
  session_preference (session_id, key, value, updated_at)
VALUES
  (
    $1,
    $2,
    $3,
    NOW()
  )
ON CONFLICT (session_id, key) DO UPDATE
SET
  value = $3,
  updated_at = NOW()
`

type SetSessionPreferenceParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Key       string `db:"key" json:"key"`
	Value     string `db:"value" json:"value"`
}

// SetSessionPreference
//
//	INSERT INTO
//	  session_preference (session_id, key, value, updated_at)
//	VALUES
//	  (
//	    $1,
//	    $2,
//	    $3,
//	    NOW()
//	  )
//	ON CONFLICT (session_id, key) DO UPDATE
//	SET
//	  value = $3,
//	  updated_at = NOW()
func (q *Queries) SetSessionPreference(ctx context.Context, arg SetSessionPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, setSessionPreference, arg.SessionID, arg.Key, arg.Value)
	return err
}

const terminateSession = `-- name: TerminateSession :exec
UPDATE
  session
SET
  status = 'terminated',
  updated_at = NOW()
WHERE
  id = $1
  AND logged_in_user_id = $2
`

type TerminateSessionParams struct {
	ID     string         `db:"id" json:"id"`
	UserID sql.NullString `db:"user_id" json:"user_id"`
}

// TerminateSession
//
//	UPDATE
//	  session
//	SET
//	  status = 'terminated',
//	  updated_at = NOW()
//	WHERE
//	  id = $1
//	  AND logged_in_user_id = $2
func (q *Queries) TerminateSession(ctx context.Context, arg TerminateSessionParams) error {
	_, err := q.db.ExecContext(ctx, terminateSession, arg.ID, arg.UserID)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE
  session
SET
  last_activity_at = NOW(),
  user_agent = COALESCE($1, user_agent),
  updated_at = NOW()
WHERE
  id = $2
`

type UpdateSessionActivityParams struct {
	UserAgent sql.NullString `db:"user_agent" json:"user_agent"`
	ID        string         `db:"id" json:"id"`
}

// UpdateSessionActivity
//
//	UPDATE
//	  session
//	SET
//	  last_activity_at = NOW(),
//	  user_agent = COALESCE($1, user_agent),
//	  updated_at = NOW()
//	WHERE
//	  id = $2
func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, arg.UserAgent, arg.ID)
	return err
}

const updateSessionLoggedInAt = `-- name: UpdateSessionLoggedInAt :exec
UPDATE
  session
SET
  logged_in_at = $1,
  updated_at = NOW()
WHERE
  id = $2
`

type UpdateSessionLoggedInAtParams struct {
	LoggedInAt sql.NullTime `db:"logged_in_at" json:"logged_in_at"`
	ID         string       `db:"id" json:"id"`
}

// UpdateSessionLoggedInAt
//
//	UPDATE
//	  session
//	SET
//	  logged_in_at = $1,
//	  updated_at = NOW()
//	WHERE
//	  id = $2
func (q *Queries) UpdateSessionLoggedInAt(ctx context.Context, arg UpdateSessionLoggedInAtParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLoggedInAt, arg.LoggedInAt, arg.ID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE
  session
SET
  status = $1,
  updated_at = NOW()
WHERE
  id = $2
`

type UpdateSessionStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

// UpdateSessionStatus
//
//	UPDATE
//	  session
//	SET
//	  status = $1,
//	  updated_at = NOW()
//	WHERE
//	  id = $2
func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}

const upsertSessionRateLimit = `-- name: UpsertSessionRateLimit :exec
INSERT INTO
  session_rate_limit (ip_hash, count, window_start)
VALUES
  ($1, 1, NOW())
ON CONFLICT (ip_hash) DO UPDATE
SET
  count = CASE
    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
    THEN 1
    ELSE session_rate_limit.count + 1
  END,
  window_start = CASE
    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
    THEN NOW()
    ELSE session_rate_limit.window_start
  END
`

type UpsertSessionRateLimitParams struct {
	IpHash string `db:"ip_hash" json:"ip_hash"`
}

// UpsertSessionRateLimit
//
//	INSERT INTO
//	  session_rate_limit (ip_hash, count, window_start)
//	VALUES
//	  ($1, 1, NOW())
//	ON CONFLICT (ip_hash) DO UPDATE
//	SET
//	  count = CASE
//	    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
//	    THEN 1
//	    ELSE session_rate_limit.count + 1
//	  END,
//	  window_start = CASE
//	    WHEN session_rate_limit.window_start < NOW() - INTERVAL '1 hour'
//	    THEN NOW()
//	    ELSE session_rate_limit.window_start
//	  END
func (q *Queries) UpsertSessionRateLimit(ctx context.Context, arg UpsertSessionRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionRateLimit, arg.IpHash)
	return err
}
