// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: story_date_proposals.sql

package storage

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const adjustStoryDateProposalVoteScore = `-- name: AdjustStoryDateProposalVoteScore :exec
UPDATE "story_date_proposal"
SET
  vote_score = vote_score + $1::INTEGER,
  upvote_count = GREATEST(upvote_count + $2::INTEGER, 0),
  downvote_count = GREATEST(downvote_count + $3::INTEGER, 0),
  updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type AdjustStoryDateProposalVoteScoreParams struct {
	ScoreDelta    int32  `db:"score_delta" json:"score_delta"`
	UpvoteDelta   int32  `db:"upvote_delta" json:"upvote_delta"`
	DownvoteDelta int32  `db:"downvote_delta" json:"downvote_delta"`
	ID            string `db:"id" json:"id"`
}

// AdjustStoryDateProposalVoteScore
//
//	UPDATE "story_date_proposal"
//	SET
//	  vote_score = vote_score + $1::INTEGER,
//	  upvote_count = GREATEST(upvote_count + $2::INTEGER, 0),
//	  downvote_count = GREATEST(downvote_count + $3::INTEGER, 0),
//	  updated_at = NOW()
//	WHERE id = $4 AND deleted_at IS NULL
func (q *Queries) AdjustStoryDateProposalVoteScore(ctx context.Context, arg AdjustStoryDateProposalVoteScoreParams) error {
	_, err := q.db.ExecContext(ctx, adjustStoryDateProposalVoteScore,
		arg.ScoreDelta,
		arg.UpvoteDelta,
		arg.DownvoteDelta,
		arg.ID,
	)
	return err
}

const deleteStoryDateProposalVote = `-- name: DeleteStoryDateProposalVote :exec
DELETE FROM "story_date_proposal_vote"
WHERE proposal_id = $1
  AND voter_profile_id = $2
`

type DeleteStoryDateProposalVoteParams struct {
	ProposalID     string `db:"proposal_id" json:"proposal_id"`
	VoterProfileID string `db:"voter_profile_id" json:"voter_profile_id"`
}

// DeleteStoryDateProposalVote
//
//	DELETE FROM "story_date_proposal_vote"
//	WHERE proposal_id = $1
//	  AND voter_profile_id = $2
func (q *Queries) DeleteStoryDateProposalVote(ctx context.Context, arg DeleteStoryDateProposalVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteStoryDateProposalVote, arg.ProposalID, arg.VoterProfileID)
	return err
}

const getStoryDateProposal = `-- name: GetStoryDateProposal :one
SELECT id, story_id, proposer_profile_id, datetime_start, datetime_end, is_finalized, vote_score, upvote_count, downvote_count, created_at, updated_at, deleted_at FROM "story_date_proposal"
WHERE id = $1 AND deleted_at IS NULL
`

type GetStoryDateProposalParams struct {
	ID string `db:"id" json:"id"`
}

// GetStoryDateProposal
//
//	SELECT id, story_id, proposer_profile_id, datetime_start, datetime_end, is_finalized, vote_score, upvote_count, downvote_count, created_at, updated_at, deleted_at FROM "story_date_proposal"
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) GetStoryDateProposal(ctx context.Context, arg GetStoryDateProposalParams) (*StoryDateProposal, error) {
	row := q.db.QueryRowContext(ctx, getStoryDateProposal, arg.ID)
	var i StoryDateProposal
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ProposerProfileID,
		&i.DatetimeStart,
		&i.DatetimeEnd,
		&i.IsFinalized,
		&i.VoteScore,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getStoryDateProposalVote = `-- name: GetStoryDateProposalVote :one
SELECT id, proposal_id, voter_profile_id, direction, created_at, updated_at FROM "story_date_proposal_vote"
WHERE proposal_id = $1
  AND voter_profile_id = $2
`

type GetStoryDateProposalVoteParams struct {
	ProposalID     string `db:"proposal_id" json:"proposal_id"`
	VoterProfileID string `db:"voter_profile_id" json:"voter_profile_id"`
}

// GetStoryDateProposalVote
//
//	SELECT id, proposal_id, voter_profile_id, direction, created_at, updated_at FROM "story_date_proposal_vote"
//	WHERE proposal_id = $1
//	  AND voter_profile_id = $2
func (q *Queries) GetStoryDateProposalVote(ctx context.Context, arg GetStoryDateProposalVoteParams) (*StoryDateProposalVote, error) {
	row := q.db.QueryRowContext(ctx, getStoryDateProposalVote, arg.ProposalID, arg.VoterProfileID)
	var i StoryDateProposalVote
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.VoterProfileID,
		&i.Direction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getStoryKindAndProperties = `-- name: GetStoryKindAndProperties :one
SELECT kind, properties, author_profile_id FROM "story"
WHERE id = $1 AND deleted_at IS NULL
`

type GetStoryKindAndPropertiesParams struct {
	ID string `db:"id" json:"id"`
}

type GetStoryKindAndPropertiesRow struct {
	Kind            string                `db:"kind" json:"kind"`
	Properties      pqtype.NullRawMessage `db:"properties" json:"properties"`
	AuthorProfileID sql.NullString        `db:"author_profile_id" json:"author_profile_id"`
}

// GetStoryKindAndProperties
//
//	SELECT kind, properties, author_profile_id FROM "story"
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) GetStoryKindAndProperties(ctx context.Context, arg GetStoryKindAndPropertiesParams) (*GetStoryKindAndPropertiesRow, error) {
	row := q.db.QueryRowContext(ctx, getStoryKindAndProperties, arg.ID)
	var i GetStoryKindAndPropertiesRow
	err := row.Scan(&i.Kind, &i.Properties, &i.AuthorProfileID)
	return &i, err
}

const insertStoryDateProposal = `-- name: InsertStoryDateProposal :one
INSERT INTO "story_date_proposal" (
  id, story_id, proposer_profile_id, datetime_start, datetime_end, created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  NOW()
) RETURNING id, story_id, proposer_profile_id, datetime_start, datetime_end, is_finalized, vote_score, upvote_count, downvote_count, created_at, updated_at, deleted_at
`

type InsertStoryDateProposalParams struct {
	ID                string       `db:"id" json:"id"`
	StoryID           string       `db:"story_id" json:"story_id"`
	ProposerProfileID string       `db:"proposer_profile_id" json:"proposer_profile_id"`
	DatetimeStart     time.Time    `db:"datetime_start" json:"datetime_start"`
	DatetimeEnd       sql.NullTime `db:"datetime_end" json:"datetime_end"`
}

// InsertStoryDateProposal
//
//	INSERT INTO "story_date_proposal" (
//	  id, story_id, proposer_profile_id, datetime_start, datetime_end, created_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5,
//	  NOW()
//	) RETURNING id, story_id, proposer_profile_id, datetime_start, datetime_end, is_finalized, vote_score, upvote_count, downvote_count, created_at, updated_at, deleted_at
func (q *Queries) InsertStoryDateProposal(ctx context.Context, arg InsertStoryDateProposalParams) (*StoryDateProposal, error) {
	row := q.db.QueryRowContext(ctx, insertStoryDateProposal,
		arg.ID,
		arg.StoryID,
		arg.ProposerProfileID,
		arg.DatetimeStart,
		arg.DatetimeEnd,
	)
	var i StoryDateProposal
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ProposerProfileID,
		&i.DatetimeStart,
		&i.DatetimeEnd,
		&i.IsFinalized,
		&i.VoteScore,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insertStoryDateProposalVote = `-- name: InsertStoryDateProposalVote :one
INSERT INTO "story_date_proposal_vote" (
  id, proposal_id, voter_profile_id, direction, created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  NOW()
) RETURNING id, proposal_id, voter_profile_id, direction, created_at, updated_at
`

type InsertStoryDateProposalVoteParams struct {
	ID             string `db:"id" json:"id"`
	ProposalID     string `db:"proposal_id" json:"proposal_id"`
	VoterProfileID string `db:"voter_profile_id" json:"voter_profile_id"`
	Direction      int16  `db:"direction" json:"direction"`
}

// InsertStoryDateProposalVote
//
//	INSERT INTO "story_date_proposal_vote" (
//	  id, proposal_id, voter_profile_id, direction, created_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  NOW()
//	) RETURNING id, proposal_id, voter_profile_id, direction, created_at, updated_at
func (q *Queries) InsertStoryDateProposalVote(ctx context.Context, arg InsertStoryDateProposalVoteParams) (*StoryDateProposalVote, error) {
	row := q.db.QueryRowContext(ctx, insertStoryDateProposalVote,
		arg.ID,
		arg.ProposalID,
		arg.VoterProfileID,
		arg.Direction,
	)
	var i StoryDateProposalVote
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.VoterProfileID,
		&i.Direction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listStoryDateProposals = `-- name: ListStoryDateProposals :many
SELECT
  sdp.id,
  sdp.story_id,
  sdp.proposer_profile_id,
  sdp.datetime_start,
  sdp.datetime_end,
  sdp.is_finalized,
  sdp.vote_score,
  sdp.upvote_count,
  sdp.downvote_count,
  sdp.created_at,
  sdp.updated_at,
  p.slug AS proposer_profile_slug,
  pt.title AS proposer_profile_title,
  p.profile_picture_uri AS proposer_profile_picture_uri,
  p.kind AS proposer_profile_kind,
  CASE
    WHEN $1::TEXT IS NOT NULL THEN
      COALESCE(
        (SELECT sdpv.direction FROM "story_date_proposal_vote" sdpv
         WHERE sdpv.proposal_id = sdp.id
           AND sdpv.voter_profile_id = $1::TEXT),
        0
      )::SMALLINT
    ELSE 0::SMALLINT
  END AS viewer_vote_direction
FROM "story_date_proposal" sdp
  INNER JOIN "profile" p ON p.id = sdp.proposer_profile_id AND p.deleted_at IS NULL
  INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
    AND pt.locale_code = (
      SELECT ptx.locale_code FROM "profile_tx" ptx
      WHERE ptx.profile_id = p.id
      ORDER BY CASE
        WHEN ptx.locale_code = $2 THEN 0
        WHEN ptx.locale_code = p.default_locale THEN 1
        ELSE 2
      END
      LIMIT 1
    )
WHERE sdp.story_id = $3
  AND sdp.deleted_at IS NULL
ORDER BY sdp.vote_score DESC, sdp.created_at ASC
`

type ListStoryDateProposalsParams struct {
	ViewerProfileID sql.NullString `db:"viewer_profile_id" json:"viewer_profile_id"`
	LocaleCode      string         `db:"locale_code" json:"locale_code"`
	StoryID         string         `db:"story_id" json:"story_id"`
}

type ListStoryDateProposalsRow struct {
	ID                        string         `db:"id" json:"id"`
	StoryID                   string         `db:"story_id" json:"story_id"`
	ProposerProfileID         string         `db:"proposer_profile_id" json:"proposer_profile_id"`
	DatetimeStart             time.Time      `db:"datetime_start" json:"datetime_start"`
	DatetimeEnd               sql.NullTime   `db:"datetime_end" json:"datetime_end"`
	IsFinalized               bool           `db:"is_finalized" json:"is_finalized"`
	VoteScore                 int32          `db:"vote_score" json:"vote_score"`
	UpvoteCount               int32          `db:"upvote_count" json:"upvote_count"`
	DownvoteCount             int32          `db:"downvote_count" json:"downvote_count"`
	CreatedAt                 time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                 sql.NullTime   `db:"updated_at" json:"updated_at"`
	ProposerProfileSlug       string         `db:"proposer_profile_slug" json:"proposer_profile_slug"`
	ProposerProfileTitle      string         `db:"proposer_profile_title" json:"proposer_profile_title"`
	ProposerProfilePictureURI sql.NullString `db:"proposer_profile_picture_uri" json:"proposer_profile_picture_uri"`
	ProposerProfileKind       string         `db:"proposer_profile_kind" json:"proposer_profile_kind"`
	ViewerVoteDirection       int16          `db:"viewer_vote_direction" json:"viewer_vote_direction"`
}

// Lists proposals for a story with proposer profile info and viewer's vote direction.
//
//	SELECT
//	  sdp.id,
//	  sdp.story_id,
//	  sdp.proposer_profile_id,
//	  sdp.datetime_start,
//	  sdp.datetime_end,
//	  sdp.is_finalized,
//	  sdp.vote_score,
//	  sdp.upvote_count,
//	  sdp.downvote_count,
//	  sdp.created_at,
//	  sdp.updated_at,
//	  p.slug AS proposer_profile_slug,
//	  pt.title AS proposer_profile_title,
//	  p.profile_picture_uri AS proposer_profile_picture_uri,
//	  p.kind AS proposer_profile_kind,
//	  CASE
//	    WHEN $1::TEXT IS NOT NULL THEN
//	      COALESCE(
//	        (SELECT sdpv.direction FROM "story_date_proposal_vote" sdpv
//	         WHERE sdpv.proposal_id = sdp.id
//	           AND sdpv.voter_profile_id = $1::TEXT),
//	        0
//	      )::SMALLINT
//	    ELSE 0::SMALLINT
//	  END AS viewer_vote_direction
//	FROM "story_date_proposal" sdp
//	  INNER JOIN "profile" p ON p.id = sdp.proposer_profile_id AND p.deleted_at IS NULL
//	  INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
//	    AND pt.locale_code = (
//	      SELECT ptx.locale_code FROM "profile_tx" ptx
//	      WHERE ptx.profile_id = p.id
//	      ORDER BY CASE
//	        WHEN ptx.locale_code = $2 THEN 0
//	        WHEN ptx.locale_code = p.default_locale THEN 1
//	        ELSE 2
//	      END
//	      LIMIT 1
//	    )
//	WHERE sdp.story_id = $3
//	  AND sdp.deleted_at IS NULL
//	ORDER BY sdp.vote_score DESC, sdp.created_at ASC
func (q *Queries) ListStoryDateProposals(ctx context.Context, arg ListStoryDateProposalsParams) ([]*ListStoryDateProposalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStoryDateProposals, arg.ViewerProfileID, arg.LocaleCode, arg.StoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListStoryDateProposalsRow{}
	for rows.Next() {
		var i ListStoryDateProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ProposerProfileID,
			&i.DatetimeStart,
			&i.DatetimeEnd,
			&i.IsFinalized,
			&i.VoteScore,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProposerProfileSlug,
			&i.ProposerProfileTitle,
			&i.ProposerProfilePictureURI,
			&i.ProposerProfileKind,
			&i.ViewerVoteDirection,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoryDateProposalFinalized = `-- name: MarkStoryDateProposalFinalized :exec
UPDATE "story_date_proposal"
SET is_finalized = TRUE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type MarkStoryDateProposalFinalizedParams struct {
	ID string `db:"id" json:"id"`
}

// MarkStoryDateProposalFinalized
//
//	UPDATE "story_date_proposal"
//	SET is_finalized = TRUE, updated_at = NOW()
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) MarkStoryDateProposalFinalized(ctx context.Context, arg MarkStoryDateProposalFinalizedParams) error {
	_, err := q.db.ExecContext(ctx, markStoryDateProposalFinalized, arg.ID)
	return err
}

const softDeleteStoryDateProposal = `-- name: SoftDeleteStoryDateProposal :exec
UPDATE "story_date_proposal"
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteStoryDateProposalParams struct {
	ID string `db:"id" json:"id"`
}

// SoftDeleteStoryDateProposal
//
//	UPDATE "story_date_proposal"
//	SET deleted_at = NOW(), updated_at = NOW()
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) SoftDeleteStoryDateProposal(ctx context.Context, arg SoftDeleteStoryDateProposalParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteStoryDateProposal, arg.ID)
	return err
}

const updateStoryDateProposalVoteDirection = `-- name: UpdateStoryDateProposalVoteDirection :exec
UPDATE "story_date_proposal_vote"
SET direction = $1, updated_at = NOW()
WHERE proposal_id = $2
  AND voter_profile_id = $3
`

type UpdateStoryDateProposalVoteDirectionParams struct {
	Direction      int16  `db:"direction" json:"direction"`
	ProposalID     string `db:"proposal_id" json:"proposal_id"`
	VoterProfileID string `db:"voter_profile_id" json:"voter_profile_id"`
}

// UpdateStoryDateProposalVoteDirection
//
//	UPDATE "story_date_proposal_vote"
//	SET direction = $1, updated_at = NOW()
//	WHERE proposal_id = $2
//	  AND voter_profile_id = $3
func (q *Queries) UpdateStoryDateProposalVoteDirection(ctx context.Context, arg UpdateStoryDateProposalVoteDirectionParams) error {
	_, err := q.db.ExecContext(ctx, updateStoryDateProposalVoteDirection, arg.Direction, arg.ProposalID, arg.VoterProfileID)
	return err
}

const updateStoryPropertiesForDateFinalization = `-- name: UpdateStoryPropertiesForDateFinalization :exec
UPDATE "story"
SET properties = $1::JSONB, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateStoryPropertiesForDateFinalizationParams struct {
	Properties pqtype.NullRawMessage `db:"properties" json:"properties"`
	ID         string                `db:"id" json:"id"`
}

// UpdateStoryPropertiesForDateFinalization
//
//	UPDATE "story"
//	SET properties = $1::JSONB, updated_at = NOW()
//	WHERE id = $2 AND deleted_at IS NULL
func (q *Queries) UpdateStoryPropertiesForDateFinalization(ctx context.Context, arg UpdateStoryPropertiesForDateFinalizationParams) error {
	_, err := q.db.ExecContext(ctx, updateStoryPropertiesForDateFinalization, arg.Properties, arg.ID)
	return err
}
