// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telegram.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredTelegramVerificationCodes = `-- name: CleanupExpiredTelegramVerificationCodes :execrows
DELETE FROM "telegram_verification_code"
WHERE expires_at < NOW() - INTERVAL '1 hour'
`

// CleanupExpiredTelegramVerificationCodes
//
//	DELETE FROM "telegram_verification_code"
//	WHERE expires_at < NOW() - INTERVAL '1 hour'
func (q *Queries) CleanupExpiredTelegramVerificationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupExpiredTelegramVerificationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeTelegramVerificationCode = `-- name: ConsumeTelegramVerificationCode :execrows
UPDATE "telegram_verification_code"
SET consumed_at = NOW()
WHERE code = $1
  AND consumed_at IS NULL
`

type ConsumeTelegramVerificationCodeParams struct {
	Code string `db:"code" json:"code"`
}

// ConsumeTelegramVerificationCode
//
//	UPDATE "telegram_verification_code"
//	SET consumed_at = NOW()
//	WHERE code = $1
//	  AND consumed_at IS NULL
func (q *Queries) ConsumeTelegramVerificationCode(ctx context.Context, arg ConsumeTelegramVerificationCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeTelegramVerificationCode, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTelegramVerificationCode = `-- name: CreateTelegramVerificationCode :exec
INSERT INTO "telegram_verification_code" (id, code, telegram_user_id, telegram_username, created_at, expires_at)
VALUES ($1, $2, $3, $4, NOW(), $5)
`

type CreateTelegramVerificationCodeParams struct {
	ID               string    `db:"id" json:"id"`
	Code             string    `db:"code" json:"code"`
	TelegramUserID   int64     `db:"telegram_user_id" json:"telegram_user_id"`
	TelegramUsername string    `db:"telegram_username" json:"telegram_username"`
	ExpiresAt        time.Time `db:"expires_at" json:"expires_at"`
}

// CreateTelegramVerificationCode
//
//	INSERT INTO "telegram_verification_code" (id, code, telegram_user_id, telegram_username, created_at, expires_at)
//	VALUES ($1, $2, $3, $4, NOW(), $5)
func (q *Queries) CreateTelegramVerificationCode(ctx context.Context, arg CreateTelegramVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createTelegramVerificationCode,
		arg.ID,
		arg.Code,
		arg.TelegramUserID,
		arg.TelegramUsername,
		arg.ExpiresAt,
	)
	return err
}

const getProfileLinkByProfileIDAndTelegram = `-- name: GetProfileLinkByProfileIDAndTelegram :one
SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
FROM "profile_link" pl
WHERE pl.profile_id = $1
  AND pl.kind = 'telegram'
  AND pl.is_managed = TRUE
  AND pl.deleted_at IS NULL
LIMIT 1
`

type GetProfileLinkByProfileIDAndTelegramParams struct {
	ProfileID string `db:"profile_id" json:"profile_id"`
}

type GetProfileLinkByProfileIDAndTelegramRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// GetProfileLinkByProfileIDAndTelegram
//
//	SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
//	FROM "profile_link" pl
//	WHERE pl.profile_id = $1
//	  AND pl.kind = 'telegram'
//	  AND pl.is_managed = TRUE
//	  AND pl.deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileLinkByProfileIDAndTelegram(ctx context.Context, arg GetProfileLinkByProfileIDAndTelegramParams) (*GetProfileLinkByProfileIDAndTelegramRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileLinkByProfileIDAndTelegram, arg.ProfileID)
	var i GetProfileLinkByProfileIDAndTelegramRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RemoteID,
		&i.PublicID,
	)
	return &i, err
}

const getProfileLinkByTelegramRemoteID = `-- name: GetProfileLinkByTelegramRemoteID :one
SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
FROM "profile_link" pl
WHERE pl.kind = 'telegram'
  AND pl.remote_id = $1
  AND pl.deleted_at IS NULL
LIMIT 1
`

type GetProfileLinkByTelegramRemoteIDParams struct {
	RemoteID sql.NullString `db:"remote_id" json:"remote_id"`
}

type GetProfileLinkByTelegramRemoteIDRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// GetProfileLinkByTelegramRemoteID
//
//	SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
//	FROM "profile_link" pl
//	WHERE pl.kind = 'telegram'
//	  AND pl.remote_id = $1
//	  AND pl.deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileLinkByTelegramRemoteID(ctx context.Context, arg GetProfileLinkByTelegramRemoteIDParams) (*GetProfileLinkByTelegramRemoteIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileLinkByTelegramRemoteID, arg.RemoteID)
	var i GetProfileLinkByTelegramRemoteIDRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RemoteID,
		&i.PublicID,
	)
	return &i, err
}

const getProfileSlugByIDForTelegram = `-- name: GetProfileSlugByIDForTelegram :one
SELECT slug
FROM "profile"
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetProfileSlugByIDForTelegramParams struct {
	ID string `db:"id" json:"id"`
}

// GetProfileSlugByIDForTelegram
//
//	SELECT slug
//	FROM "profile"
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileSlugByIDForTelegram(ctx context.Context, arg GetProfileSlugByIDForTelegramParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProfileSlugByIDForTelegram, arg.ID)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getTelegramVerificationCodeByCode = `-- name: GetTelegramVerificationCodeByCode :one
SELECT id, code, telegram_user_id, telegram_username, created_at, expires_at, consumed_at
FROM "telegram_verification_code"
WHERE code = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetTelegramVerificationCodeByCodeParams struct {
	Code string `db:"code" json:"code"`
}

// GetTelegramVerificationCodeByCode
//
//	SELECT id, code, telegram_user_id, telegram_username, created_at, expires_at, consumed_at
//	FROM "telegram_verification_code"
//	WHERE code = $1
//	  AND consumed_at IS NULL
//	  AND expires_at > NOW()
//	LIMIT 1
func (q *Queries) GetTelegramVerificationCodeByCode(ctx context.Context, arg GetTelegramVerificationCodeByCodeParams) (*TelegramVerificationCode, error) {
	row := q.db.QueryRowContext(ctx, getTelegramVerificationCodeByCode, arg.Code)
	var i TelegramVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const listManagedTelegramLinks = `-- name: ListManagedTelegramLinks :many
SELECT
  pl.id,
  pl.profile_id,
  pl.remote_id,
  pl.public_id
FROM "profile_link" pl
  INNER JOIN "profile" p ON p.id = pl.profile_id
    AND p.deleted_at IS NULL
WHERE pl.kind = 'telegram'
  AND pl.is_managed = TRUE
  AND pl.deleted_at IS NULL
ORDER BY pl.updated_at ASC NULLS FIRST
LIMIT $1
`

type ListManagedTelegramLinksParams struct {
	LimitCount int32 `db:"limit_count" json:"limit_count"`
}

type ListManagedTelegramLinksRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// ListManagedTelegramLinks
//
//	SELECT
//	  pl.id,
//	  pl.profile_id,
//	  pl.remote_id,
//	  pl.public_id
//	FROM "profile_link" pl
//	  INNER JOIN "profile" p ON p.id = pl.profile_id
//	    AND p.deleted_at IS NULL
//	WHERE pl.kind = 'telegram'
//	  AND pl.is_managed = TRUE
//	  AND pl.deleted_at IS NULL
//	ORDER BY pl.updated_at ASC NULLS FIRST
//	LIMIT $1
func (q *Queries) ListManagedTelegramLinks(ctx context.Context, arg ListManagedTelegramLinksParams) ([]*ListManagedTelegramLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listManagedTelegramLinks, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListManagedTelegramLinksRow{}
	for rows.Next() {
		var i ListManagedTelegramLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.RemoteID,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTelegramProfileLink = `-- name: SoftDeleteTelegramProfileLink :execrows
UPDATE "profile_link"
SET deleted_at = NOW()
WHERE kind = 'telegram'
  AND remote_id = $1
  AND deleted_at IS NULL
`

type SoftDeleteTelegramProfileLinkParams struct {
	RemoteID sql.NullString `db:"remote_id" json:"remote_id"`
}

// SoftDeleteTelegramProfileLink
//
//	UPDATE "profile_link"
//	SET deleted_at = NOW()
//	WHERE kind = 'telegram'
//	  AND remote_id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteTelegramProfileLink(ctx context.Context, arg SoftDeleteTelegramProfileLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTelegramProfileLink, arg.RemoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
