// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telegram.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredTelegramVerificationCodes = `-- name: CleanupExpiredTelegramVerificationCodes :execrows
DELETE FROM "telegram_verification_code"
WHERE expires_at < NOW() - INTERVAL '1 hour'
`

// CleanupExpiredTelegramVerificationCodes
//
//	DELETE FROM "telegram_verification_code"
//	WHERE expires_at < NOW() - INTERVAL '1 hour'
func (q *Queries) CleanupExpiredTelegramVerificationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupExpiredTelegramVerificationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeTelegramGroupInviteCode = `-- name: ConsumeTelegramGroupInviteCode :execrows
UPDATE "telegram_group_invite_code"
SET consumed_at = NOW()
WHERE code = $1
  AND consumed_at IS NULL
`

type ConsumeTelegramGroupInviteCodeParams struct {
	Code string `db:"code" json:"code"`
}

// ConsumeTelegramGroupInviteCode
//
//	UPDATE "telegram_group_invite_code"
//	SET consumed_at = NOW()
//	WHERE code = $1
//	  AND consumed_at IS NULL
func (q *Queries) ConsumeTelegramGroupInviteCode(ctx context.Context, arg ConsumeTelegramGroupInviteCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeTelegramGroupInviteCode, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeTelegramVerificationCode = `-- name: ConsumeTelegramVerificationCode :execrows
UPDATE "telegram_verification_code"
SET consumed_at = NOW()
WHERE code = $1
  AND consumed_at IS NULL
`

type ConsumeTelegramVerificationCodeParams struct {
	Code string `db:"code" json:"code"`
}

// ConsumeTelegramVerificationCode
//
//	UPDATE "telegram_verification_code"
//	SET consumed_at = NOW()
//	WHERE code = $1
//	  AND consumed_at IS NULL
func (q *Queries) ConsumeTelegramVerificationCode(ctx context.Context, arg ConsumeTelegramVerificationCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeTelegramVerificationCode, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTelegramGroupInviteCode = `-- name: CreateTelegramGroupInviteCode :exec
INSERT INTO "telegram_group_invite_code" (id, code, telegram_chat_id, telegram_chat_title, created_by_telegram_user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, NOW(), $6)
`

type CreateTelegramGroupInviteCodeParams struct {
	ID                      string    `db:"id" json:"id"`
	Code                    string    `db:"code" json:"code"`
	TelegramChatID          int64     `db:"telegram_chat_id" json:"telegram_chat_id"`
	TelegramChatTitle       string    `db:"telegram_chat_title" json:"telegram_chat_title"`
	CreatedByTelegramUserID int64     `db:"created_by_telegram_user_id" json:"created_by_telegram_user_id"`
	ExpiresAt               time.Time `db:"expires_at" json:"expires_at"`
}

// CreateTelegramGroupInviteCode
//
//	INSERT INTO "telegram_group_invite_code" (id, code, telegram_chat_id, telegram_chat_title, created_by_telegram_user_id, created_at, expires_at)
//	VALUES ($1, $2, $3, $4, $5, NOW(), $6)
func (q *Queries) CreateTelegramGroupInviteCode(ctx context.Context, arg CreateTelegramGroupInviteCodeParams) error {
	_, err := q.db.ExecContext(ctx, createTelegramGroupInviteCode,
		arg.ID,
		arg.Code,
		arg.TelegramChatID,
		arg.TelegramChatTitle,
		arg.CreatedByTelegramUserID,
		arg.ExpiresAt,
	)
	return err
}

const createTelegramVerificationCode = `-- name: CreateTelegramVerificationCode :exec
INSERT INTO "telegram_verification_code" (id, code, telegram_user_id, telegram_username, created_at, expires_at)
VALUES ($1, $2, $3, $4, NOW(), $5)
`

type CreateTelegramVerificationCodeParams struct {
	ID               string    `db:"id" json:"id"`
	Code             string    `db:"code" json:"code"`
	TelegramUserID   int64     `db:"telegram_user_id" json:"telegram_user_id"`
	TelegramUsername string    `db:"telegram_username" json:"telegram_username"`
	ExpiresAt        time.Time `db:"expires_at" json:"expires_at"`
}

// CreateTelegramVerificationCode
//
//	INSERT INTO "telegram_verification_code" (id, code, telegram_user_id, telegram_username, created_at, expires_at)
//	VALUES ($1, $2, $3, $4, NOW(), $5)
func (q *Queries) CreateTelegramVerificationCode(ctx context.Context, arg CreateTelegramVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createTelegramVerificationCode,
		arg.ID,
		arg.Code,
		arg.TelegramUserID,
		arg.TelegramUsername,
		arg.ExpiresAt,
	)
	return err
}

const getMemberProfileTelegramLinks = `-- name: GetMemberProfileTelegramLinks :many
SELECT
  p.id as profile_id,
  p.slug as profile_slug,
  pt.title as profile_title,
  pm.kind as membership_kind,
  pl.id as link_id,
  pl.uri,
  pl.public_id as link_public_id,
  pl.visibility as link_visibility,
  COALESCE(plt.title, '') as link_title
FROM "profile_membership" pm
  INNER JOIN "profile" p ON p.id = pm.profile_id
    AND p.kind != 'individual'
    AND p.approved_at IS NOT NULL
    AND p.deleted_at IS NULL
  INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
    AND pt.locale_code = (
      SELECT ptf.locale_code FROM "profile_tx" ptf
      WHERE ptf.profile_id = p.id
      ORDER BY CASE WHEN ptf.locale_code = p.default_locale THEN 0 ELSE 1 END
      LIMIT 1
    )
  INNER JOIN "profile_link" pl ON pl.profile_id = p.id
    AND pl.kind = 'telegram'
    AND pl.deleted_at IS NULL
  LEFT JOIN "profile_link_tx" plt ON plt.profile_link_id = pl.id
    AND plt.locale_code = pt.locale_code
WHERE pm.member_profile_id = $1
  AND pm.deleted_at IS NULL
  AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
ORDER BY p.slug, pl."order"
`

type GetMemberProfileTelegramLinksParams struct {
	MemberProfileID sql.NullString `db:"member_profile_id" json:"member_profile_id"`
}

type GetMemberProfileTelegramLinksRow struct {
	ProfileID      string         `db:"profile_id" json:"profile_id"`
	ProfileSlug    string         `db:"profile_slug" json:"profile_slug"`
	ProfileTitle   string         `db:"profile_title" json:"profile_title"`
	MembershipKind string         `db:"membership_kind" json:"membership_kind"`
	LinkID         string         `db:"link_id" json:"link_id"`
	URI            sql.NullString `db:"uri" json:"uri"`
	LinkPublicID   sql.NullString `db:"link_public_id" json:"link_public_id"`
	LinkVisibility string         `db:"link_visibility" json:"link_visibility"`
	LinkTitle      string         `db:"link_title" json:"link_title"`
}

// For a given member profile, find all non-individual profiles they belong to
// and return the telegram links on those profiles (visibility filtering happens in Go).
//
//	SELECT
//	  p.id as profile_id,
//	  p.slug as profile_slug,
//	  pt.title as profile_title,
//	  pm.kind as membership_kind,
//	  pl.id as link_id,
//	  pl.uri,
//	  pl.public_id as link_public_id,
//	  pl.visibility as link_visibility,
//	  COALESCE(plt.title, '') as link_title
//	FROM "profile_membership" pm
//	  INNER JOIN "profile" p ON p.id = pm.profile_id
//	    AND p.kind != 'individual'
//	    AND p.approved_at IS NOT NULL
//	    AND p.deleted_at IS NULL
//	  INNER JOIN "profile_tx" pt ON pt.profile_id = p.id
//	    AND pt.locale_code = (
//	      SELECT ptf.locale_code FROM "profile_tx" ptf
//	      WHERE ptf.profile_id = p.id
//	      ORDER BY CASE WHEN ptf.locale_code = p.default_locale THEN 0 ELSE 1 END
//	      LIMIT 1
//	    )
//	  INNER JOIN "profile_link" pl ON pl.profile_id = p.id
//	    AND pl.kind = 'telegram'
//	    AND pl.deleted_at IS NULL
//	  LEFT JOIN "profile_link_tx" plt ON plt.profile_link_id = pl.id
//	    AND plt.locale_code = pt.locale_code
//	WHERE pm.member_profile_id = $1
//	  AND pm.deleted_at IS NULL
//	  AND (pm.finished_at IS NULL OR pm.finished_at > NOW())
//	ORDER BY p.slug, pl."order"
func (q *Queries) GetMemberProfileTelegramLinks(ctx context.Context, arg GetMemberProfileTelegramLinksParams) ([]*GetMemberProfileTelegramLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, getMemberProfileTelegramLinks, arg.MemberProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMemberProfileTelegramLinksRow{}
	for rows.Next() {
		var i GetMemberProfileTelegramLinksRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.ProfileSlug,
			&i.ProfileTitle,
			&i.MembershipKind,
			&i.LinkID,
			&i.URI,
			&i.LinkPublicID,
			&i.LinkVisibility,
			&i.LinkTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileLinkByProfileIDAndTelegram = `-- name: GetProfileLinkByProfileIDAndTelegram :one
SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
FROM "profile_link" pl
WHERE pl.profile_id = $1
  AND pl.kind = 'telegram'
  AND pl.is_managed = TRUE
  AND pl.deleted_at IS NULL
LIMIT 1
`

type GetProfileLinkByProfileIDAndTelegramParams struct {
	ProfileID string `db:"profile_id" json:"profile_id"`
}

type GetProfileLinkByProfileIDAndTelegramRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// GetProfileLinkByProfileIDAndTelegram
//
//	SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
//	FROM "profile_link" pl
//	WHERE pl.profile_id = $1
//	  AND pl.kind = 'telegram'
//	  AND pl.is_managed = TRUE
//	  AND pl.deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileLinkByProfileIDAndTelegram(ctx context.Context, arg GetProfileLinkByProfileIDAndTelegramParams) (*GetProfileLinkByProfileIDAndTelegramRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileLinkByProfileIDAndTelegram, arg.ProfileID)
	var i GetProfileLinkByProfileIDAndTelegramRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RemoteID,
		&i.PublicID,
	)
	return &i, err
}

const getProfileLinkByTelegramRemoteID = `-- name: GetProfileLinkByTelegramRemoteID :one
SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
FROM "profile_link" pl
WHERE pl.kind = 'telegram'
  AND pl.remote_id = $1
  AND pl.deleted_at IS NULL
LIMIT 1
`

type GetProfileLinkByTelegramRemoteIDParams struct {
	RemoteID sql.NullString `db:"remote_id" json:"remote_id"`
}

type GetProfileLinkByTelegramRemoteIDRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// GetProfileLinkByTelegramRemoteID
//
//	SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
//	FROM "profile_link" pl
//	WHERE pl.kind = 'telegram'
//	  AND pl.remote_id = $1
//	  AND pl.deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileLinkByTelegramRemoteID(ctx context.Context, arg GetProfileLinkByTelegramRemoteIDParams) (*GetProfileLinkByTelegramRemoteIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileLinkByTelegramRemoteID, arg.RemoteID)
	var i GetProfileLinkByTelegramRemoteIDRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RemoteID,
		&i.PublicID,
	)
	return &i, err
}

const getProfileSlugByIDForTelegram = `-- name: GetProfileSlugByIDForTelegram :one
SELECT slug
FROM "profile"
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetProfileSlugByIDForTelegramParams struct {
	ID string `db:"id" json:"id"`
}

// GetProfileSlugByIDForTelegram
//
//	SELECT slug
//	FROM "profile"
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileSlugByIDForTelegram(ctx context.Context, arg GetProfileSlugByIDForTelegramParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProfileSlugByIDForTelegram, arg.ID)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getTelegramGroupInviteCodeByCode = `-- name: GetTelegramGroupInviteCodeByCode :one
SELECT id, code, telegram_chat_id, telegram_chat_title, created_by_telegram_user_id, created_at, expires_at, consumed_at
FROM "telegram_group_invite_code"
WHERE code = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetTelegramGroupInviteCodeByCodeParams struct {
	Code string `db:"code" json:"code"`
}

// GetTelegramGroupInviteCodeByCode
//
//	SELECT id, code, telegram_chat_id, telegram_chat_title, created_by_telegram_user_id, created_at, expires_at, consumed_at
//	FROM "telegram_group_invite_code"
//	WHERE code = $1
//	  AND consumed_at IS NULL
//	  AND expires_at > NOW()
//	LIMIT 1
func (q *Queries) GetTelegramGroupInviteCodeByCode(ctx context.Context, arg GetTelegramGroupInviteCodeByCodeParams) (*TelegramGroupInviteCode, error) {
	row := q.db.QueryRowContext(ctx, getTelegramGroupInviteCodeByCode, arg.Code)
	var i TelegramGroupInviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TelegramChatID,
		&i.TelegramChatTitle,
		&i.CreatedByTelegramUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const getTelegramVerificationCodeByCode = `-- name: GetTelegramVerificationCodeByCode :one
SELECT id, code, telegram_user_id, telegram_username, created_at, expires_at, consumed_at
FROM "telegram_verification_code"
WHERE code = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetTelegramVerificationCodeByCodeParams struct {
	Code string `db:"code" json:"code"`
}

// GetTelegramVerificationCodeByCode
//
//	SELECT id, code, telegram_user_id, telegram_username, created_at, expires_at, consumed_at
//	FROM "telegram_verification_code"
//	WHERE code = $1
//	  AND consumed_at IS NULL
//	  AND expires_at > NOW()
//	LIMIT 1
func (q *Queries) GetTelegramVerificationCodeByCode(ctx context.Context, arg GetTelegramVerificationCodeByCodeParams) (*TelegramVerificationCode, error) {
	row := q.db.QueryRowContext(ctx, getTelegramVerificationCodeByCode, arg.Code)
	var i TelegramVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const listManagedTelegramLinks = `-- name: ListManagedTelegramLinks :many
SELECT
  pl.id,
  pl.profile_id,
  pl.remote_id,
  pl.public_id
FROM "profile_link" pl
  INNER JOIN "profile" p ON p.id = pl.profile_id
    AND p.deleted_at IS NULL
WHERE pl.kind = 'telegram'
  AND pl.is_managed = TRUE
  AND pl.deleted_at IS NULL
ORDER BY pl.updated_at ASC NULLS FIRST
LIMIT $1
`

type ListManagedTelegramLinksParams struct {
	LimitCount int32 `db:"limit_count" json:"limit_count"`
}

type ListManagedTelegramLinksRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// ListManagedTelegramLinks
//
//	SELECT
//	  pl.id,
//	  pl.profile_id,
//	  pl.remote_id,
//	  pl.public_id
//	FROM "profile_link" pl
//	  INNER JOIN "profile" p ON p.id = pl.profile_id
//	    AND p.deleted_at IS NULL
//	WHERE pl.kind = 'telegram'
//	  AND pl.is_managed = TRUE
//	  AND pl.deleted_at IS NULL
//	ORDER BY pl.updated_at ASC NULLS FIRST
//	LIMIT $1
func (q *Queries) ListManagedTelegramLinks(ctx context.Context, arg ListManagedTelegramLinksParams) ([]*ListManagedTelegramLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listManagedTelegramLinks, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListManagedTelegramLinksRow{}
	for rows.Next() {
		var i ListManagedTelegramLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.RemoteID,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTelegramProfileLink = `-- name: SoftDeleteTelegramProfileLink :execrows
UPDATE "profile_link"
SET deleted_at = NOW()
WHERE kind = 'telegram'
  AND remote_id = $1
  AND deleted_at IS NULL
`

type SoftDeleteTelegramProfileLinkParams struct {
	RemoteID sql.NullString `db:"remote_id" json:"remote_id"`
}

// SoftDeleteTelegramProfileLink
//
//	UPDATE "profile_link"
//	SET deleted_at = NOW()
//	WHERE kind = 'telegram'
//	  AND remote_id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteTelegramProfileLink(ctx context.Context, arg SoftDeleteTelegramProfileLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTelegramProfileLink, arg.RemoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
