// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telegram.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredTelegramLinkTokens = `-- name: CleanupExpiredTelegramLinkTokens :execrows
DELETE FROM "telegram_link_token"
WHERE expires_at < NOW() - INTERVAL '1 hour'
`

// CleanupExpiredTelegramLinkTokens
//
//	DELETE FROM "telegram_link_token"
//	WHERE expires_at < NOW() - INTERVAL '1 hour'
func (q *Queries) CleanupExpiredTelegramLinkTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupExpiredTelegramLinkTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeTelegramLinkToken = `-- name: ConsumeTelegramLinkToken :execrows
UPDATE "telegram_link_token"
SET consumed_at = NOW()
WHERE token = $1
  AND consumed_at IS NULL
`

type ConsumeTelegramLinkTokenParams struct {
	Token string `db:"token" json:"token"`
}

// ConsumeTelegramLinkToken
//
//	UPDATE "telegram_link_token"
//	SET consumed_at = NOW()
//	WHERE token = $1
//	  AND consumed_at IS NULL
func (q *Queries) ConsumeTelegramLinkToken(ctx context.Context, arg ConsumeTelegramLinkTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeTelegramLinkToken, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTelegramLinkToken = `-- name: CreateTelegramLinkToken :exec
INSERT INTO "telegram_link_token" (id, token, profile_id, profile_slug, created_by_user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, NOW(), $6)
`

type CreateTelegramLinkTokenParams struct {
	ID              string    `db:"id" json:"id"`
	Token           string    `db:"token" json:"token"`
	ProfileID       string    `db:"profile_id" json:"profile_id"`
	ProfileSlug     string    `db:"profile_slug" json:"profile_slug"`
	CreatedByUserID string    `db:"created_by_user_id" json:"created_by_user_id"`
	ExpiresAt       time.Time `db:"expires_at" json:"expires_at"`
}

// CreateTelegramLinkToken
//
//	INSERT INTO "telegram_link_token" (id, token, profile_id, profile_slug, created_by_user_id, created_at, expires_at)
//	VALUES ($1, $2, $3, $4, $5, NOW(), $6)
func (q *Queries) CreateTelegramLinkToken(ctx context.Context, arg CreateTelegramLinkTokenParams) error {
	_, err := q.db.ExecContext(ctx, createTelegramLinkToken,
		arg.ID,
		arg.Token,
		arg.ProfileID,
		arg.ProfileSlug,
		arg.CreatedByUserID,
		arg.ExpiresAt,
	)
	return err
}

const getProfileLinkByProfileIDAndTelegram = `-- name: GetProfileLinkByProfileIDAndTelegram :one
SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
FROM "profile_link" pl
WHERE pl.profile_id = $1
  AND pl.kind = 'telegram'
  AND pl.is_managed = TRUE
  AND pl.deleted_at IS NULL
LIMIT 1
`

type GetProfileLinkByProfileIDAndTelegramParams struct {
	ProfileID string `db:"profile_id" json:"profile_id"`
}

type GetProfileLinkByProfileIDAndTelegramRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// GetProfileLinkByProfileIDAndTelegram
//
//	SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
//	FROM "profile_link" pl
//	WHERE pl.profile_id = $1
//	  AND pl.kind = 'telegram'
//	  AND pl.is_managed = TRUE
//	  AND pl.deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileLinkByProfileIDAndTelegram(ctx context.Context, arg GetProfileLinkByProfileIDAndTelegramParams) (*GetProfileLinkByProfileIDAndTelegramRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileLinkByProfileIDAndTelegram, arg.ProfileID)
	var i GetProfileLinkByProfileIDAndTelegramRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RemoteID,
		&i.PublicID,
	)
	return &i, err
}

const getProfileLinkByTelegramRemoteID = `-- name: GetProfileLinkByTelegramRemoteID :one
SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
FROM "profile_link" pl
WHERE pl.kind = 'telegram'
  AND pl.remote_id = $1
  AND pl.deleted_at IS NULL
LIMIT 1
`

type GetProfileLinkByTelegramRemoteIDParams struct {
	RemoteID sql.NullString `db:"remote_id" json:"remote_id"`
}

type GetProfileLinkByTelegramRemoteIDRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// GetProfileLinkByTelegramRemoteID
//
//	SELECT pl.id, pl.profile_id, pl.remote_id, pl.public_id
//	FROM "profile_link" pl
//	WHERE pl.kind = 'telegram'
//	  AND pl.remote_id = $1
//	  AND pl.deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileLinkByTelegramRemoteID(ctx context.Context, arg GetProfileLinkByTelegramRemoteIDParams) (*GetProfileLinkByTelegramRemoteIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileLinkByTelegramRemoteID, arg.RemoteID)
	var i GetProfileLinkByTelegramRemoteIDRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RemoteID,
		&i.PublicID,
	)
	return &i, err
}

const getProfileSlugByIDForTelegram = `-- name: GetProfileSlugByIDForTelegram :one
SELECT slug
FROM "profile"
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetProfileSlugByIDForTelegramParams struct {
	ID string `db:"id" json:"id"`
}

// GetProfileSlugByIDForTelegram
//
//	SELECT slug
//	FROM "profile"
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetProfileSlugByIDForTelegram(ctx context.Context, arg GetProfileSlugByIDForTelegramParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProfileSlugByIDForTelegram, arg.ID)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getTelegramLinkTokenByToken = `-- name: GetTelegramLinkTokenByToken :one
SELECT id, token, profile_id, profile_slug, created_by_user_id, created_at, expires_at, consumed_at
FROM "telegram_link_token"
WHERE token = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetTelegramLinkTokenByTokenParams struct {
	Token string `db:"token" json:"token"`
}

// GetTelegramLinkTokenByToken
//
//	SELECT id, token, profile_id, profile_slug, created_by_user_id, created_at, expires_at, consumed_at
//	FROM "telegram_link_token"
//	WHERE token = $1
//	  AND consumed_at IS NULL
//	  AND expires_at > NOW()
//	LIMIT 1
func (q *Queries) GetTelegramLinkTokenByToken(ctx context.Context, arg GetTelegramLinkTokenByTokenParams) (*TelegramLinkToken, error) {
	row := q.db.QueryRowContext(ctx, getTelegramLinkTokenByToken, arg.Token)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ProfileID,
		&i.ProfileSlug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const listManagedTelegramLinks = `-- name: ListManagedTelegramLinks :many
SELECT
  pl.id,
  pl.profile_id,
  pl.remote_id,
  pl.public_id
FROM "profile_link" pl
  INNER JOIN "profile" p ON p.id = pl.profile_id
    AND p.deleted_at IS NULL
WHERE pl.kind = 'telegram'
  AND pl.is_managed = TRUE
  AND pl.deleted_at IS NULL
ORDER BY pl.updated_at ASC NULLS FIRST
LIMIT $1
`

type ListManagedTelegramLinksParams struct {
	LimitCount int32 `db:"limit_count" json:"limit_count"`
}

type ListManagedTelegramLinksRow struct {
	ID        string         `db:"id" json:"id"`
	ProfileID string         `db:"profile_id" json:"profile_id"`
	RemoteID  sql.NullString `db:"remote_id" json:"remote_id"`
	PublicID  sql.NullString `db:"public_id" json:"public_id"`
}

// ListManagedTelegramLinks
//
//	SELECT
//	  pl.id,
//	  pl.profile_id,
//	  pl.remote_id,
//	  pl.public_id
//	FROM "profile_link" pl
//	  INNER JOIN "profile" p ON p.id = pl.profile_id
//	    AND p.deleted_at IS NULL
//	WHERE pl.kind = 'telegram'
//	  AND pl.is_managed = TRUE
//	  AND pl.deleted_at IS NULL
//	ORDER BY pl.updated_at ASC NULLS FIRST
//	LIMIT $1
func (q *Queries) ListManagedTelegramLinks(ctx context.Context, arg ListManagedTelegramLinksParams) ([]*ListManagedTelegramLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listManagedTelegramLinks, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListManagedTelegramLinksRow{}
	for rows.Next() {
		var i ListManagedTelegramLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.RemoteID,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTelegramProfileLink = `-- name: SoftDeleteTelegramProfileLink :execrows
UPDATE "profile_link"
SET deleted_at = NOW()
WHERE kind = 'telegram'
  AND remote_id = $1
  AND deleted_at IS NULL
`

type SoftDeleteTelegramProfileLinkParams struct {
	RemoteID sql.NullString `db:"remote_id" json:"remote_id"`
}

// SoftDeleteTelegramProfileLink
//
//	UPDATE "profile_link"
//	SET deleted_at = NOW()
//	WHERE kind = 'telegram'
//	  AND remote_id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteTelegramProfileLink(ctx context.Context, arg SoftDeleteTelegramProfileLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTelegramProfileLink, arg.RemoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
