// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Activity struct {
	ID                 string         `db:"id" json:"id"`
	Slug               string         `db:"slug" json:"slug"`
	Kind               string         `db:"kind" json:"kind"`
	ActivityPictureURI sql.NullString `db:"activity_picture_uri" json:"activity_picture_uri"`
	Title              string         `db:"title" json:"title"`
	Description        string         `db:"description" json:"description"`
	TimeStart          time.Time      `db:"time_start" json:"time_start"`
	TimeEnd            time.Time      `db:"time_end" json:"time_end"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt          sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	SeriesID           sql.NullString `db:"series_id" json:"series_id"`
	Status             string         `db:"status" json:"status"`
	AttendanceURI      sql.NullString `db:"attendance_uri" json:"attendance_uri"`
	PublishedAt        sql.NullTime   `db:"published_at" json:"published_at"`
}

type ActivityAttendance struct {
	ID         string       `db:"id" json:"id"`
	ActivityID string       `db:"activity_id" json:"activity_id"`
	ProfileID  string       `db:"profile_id" json:"profile_id"`
	Kind       string       `db:"kind" json:"kind"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type ActivitySeries struct {
	ID                 string         `db:"id" json:"id"`
	Slug               string         `db:"slug" json:"slug"`
	ActivityPictureURI sql.NullString `db:"activity_picture_uri" json:"activity_picture_uri"`
	Title              string         `db:"title" json:"title"`
	Description        string         `db:"description" json:"description"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt          sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type Cache struct {
	Key       string                `db:"key" json:"key"`
	Value     pqtype.NullRawMessage `db:"value" json:"value"`
	UpdatedAt time.Time             `db:"updated_at" json:"updated_at"`
}

type DiscussionComment struct {
	ID            string         `db:"id" json:"id"`
	ThreadID      string         `db:"thread_id" json:"thread_id"`
	ParentID      sql.NullString `db:"parent_id" json:"parent_id"`
	AuthorUserID  string         `db:"author_user_id" json:"author_user_id"`
	Content       string         `db:"content" json:"content"`
	Depth         int32          `db:"depth" json:"depth"`
	VoteScore     int32          `db:"vote_score" json:"vote_score"`
	UpvoteCount   int32          `db:"upvote_count" json:"upvote_count"`
	DownvoteCount int32          `db:"downvote_count" json:"downvote_count"`
	ReplyCount    int32          `db:"reply_count" json:"reply_count"`
	IsPinned      bool           `db:"is_pinned" json:"is_pinned"`
	IsHidden      bool           `db:"is_hidden" json:"is_hidden"`
	IsEdited      bool           `db:"is_edited" json:"is_edited"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type DiscussionCommentVote struct {
	ID        string    `db:"id" json:"id"`
	CommentID string    `db:"comment_id" json:"comment_id"`
	UserID    string    `db:"user_id" json:"user_id"`
	Direction int16     `db:"direction" json:"direction"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type DiscussionThread struct {
	ID           string         `db:"id" json:"id"`
	StoryID      sql.NullString `db:"story_id" json:"story_id"`
	ProfileID    sql.NullString `db:"profile_id" json:"profile_id"`
	IsLocked     bool           `db:"is_locked" json:"is_locked"`
	CommentCount int32          `db:"comment_count" json:"comment_count"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type EventAudit struct {
	ID         string                `db:"id" json:"id"`
	EventType  string                `db:"event_type" json:"event_type"`
	EntityType string                `db:"entity_type" json:"entity_type"`
	EntityID   sql.NullString        `db:"entity_id" json:"entity_id"`
	ActorID    sql.NullString        `db:"actor_id" json:"actor_id"`
	ActorKind  string                `db:"actor_kind" json:"actor_kind"`
	SessionID  sql.NullString        `db:"session_id" json:"session_id"`
	Payload    pqtype.NullRawMessage `db:"payload" json:"payload"`
	CreatedAt  time.Time             `db:"created_at" json:"created_at"`
}

type EventQueue struct {
	ID                    string                `db:"id" json:"id"`
	Type                  string                `db:"type" json:"type"`
	Payload               pqtype.NullRawMessage `db:"payload" json:"payload"`
	Status                string                `db:"status" json:"status"`
	RetryCount            int32                 `db:"retry_count" json:"retry_count"`
	MaxRetries            int32                 `db:"max_retries" json:"max_retries"`
	VisibleAt             time.Time             `db:"visible_at" json:"visible_at"`
	VisibilityTimeoutSecs int32                 `db:"visibility_timeout_secs" json:"visibility_timeout_secs"`
	StartedAt             sql.NullTime          `db:"started_at" json:"started_at"`
	CompletedAt           sql.NullTime          `db:"completed_at" json:"completed_at"`
	FailedAt              sql.NullTime          `db:"failed_at" json:"failed_at"`
	CreatedAt             time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt             sql.NullTime          `db:"updated_at" json:"updated_at"`
	ErrorMessage          sql.NullString        `db:"error_message" json:"error_message"`
	WorkerID              sql.NullString        `db:"worker_id" json:"worker_id"`
}

type ExternalCode struct {
	ID             string                `db:"id" json:"id"`
	Code           string                `db:"code" json:"code"`
	ExternalSystem string                `db:"external_system" json:"external_system"`
	Properties     pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt      time.Time             `db:"created_at" json:"created_at"`
	ExpiresAt      time.Time             `db:"expires_at" json:"expires_at"`
	ConsumedAt     sql.NullTime          `db:"consumed_at" json:"consumed_at"`
}

type MailboxConversation struct {
	ID                 string         `db:"id" json:"id"`
	Kind               string         `db:"kind" json:"kind"`
	Title              sql.NullString `db:"title" json:"title"`
	CreatedByProfileID sql.NullString `db:"created_by_profile_id" json:"created_by_profile_id"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type MailboxEnvelope struct {
	ID              string                `db:"id" json:"id"`
	TargetProfileID string                `db:"target_profile_id" json:"target_profile_id"`
	SenderProfileID sql.NullString        `db:"sender_profile_id" json:"sender_profile_id"`
	SenderUserID    sql.NullString        `db:"sender_user_id" json:"sender_user_id"`
	Kind            string                `db:"kind" json:"kind"`
	Status          string                `db:"status" json:"status"`
	Message         sql.NullString        `db:"message" json:"message"`
	Properties      pqtype.NullRawMessage `db:"properties" json:"properties"`
	AcceptedAt      sql.NullTime          `db:"accepted_at" json:"accepted_at"`
	RejectedAt      sql.NullTime          `db:"rejected_at" json:"rejected_at"`
	RevokedAt       sql.NullTime          `db:"revoked_at" json:"revoked_at"`
	RedeemedAt      sql.NullTime          `db:"redeemed_at" json:"redeemed_at"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime          `db:"deleted_at" json:"deleted_at"`
	ConversationID  string                `db:"conversation_id" json:"conversation_id"`
	ReplyToID       sql.NullString        `db:"reply_to_id" json:"reply_to_id"`
}

type MailboxParticipant struct {
	ID             string       `db:"id" json:"id"`
	ConversationID string       `db:"conversation_id" json:"conversation_id"`
	ProfileID      string       `db:"profile_id" json:"profile_id"`
	LastReadAt     sql.NullTime `db:"last_read_at" json:"last_read_at"`
	IsArchived     bool         `db:"is_archived" json:"is_archived"`
	JoinedAt       time.Time    `db:"joined_at" json:"joined_at"`
	LeftAt         sql.NullTime `db:"left_at" json:"left_at"`
}

type MailboxReaction struct {
	ID         string    `db:"id" json:"id"`
	EnvelopeID string    `db:"envelope_id" json:"envelope_id"`
	ProfileID  string    `db:"profile_id" json:"profile_id"`
	Emoji      string    `db:"emoji" json:"emoji"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type Profile struct {
	ID                              string                `db:"id" json:"id"`
	Slug                            string                `db:"slug" json:"slug"`
	Kind                            string                `db:"kind" json:"kind"`
	ProfilePictureURI               sql.NullString        `db:"profile_picture_uri" json:"profile_picture_uri"`
	Pronouns                        sql.NullString        `db:"pronouns" json:"pronouns"`
	Properties                      pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt                       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt                       sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt                       sql.NullTime          `db:"deleted_at" json:"deleted_at"`
	ApprovedAt                      sql.NullTime          `db:"approved_at" json:"approved_at"`
	Points                          int32                 `db:"points" json:"points"`
	FeatureRelations                string                `db:"feature_relations" json:"feature_relations"`
	FeatureLinks                    string                `db:"feature_links" json:"feature_links"`
	DefaultLocale                   string                `db:"default_locale" json:"default_locale"`
	FeatureQa                       string                `db:"feature_qa" json:"feature_qa"`
	FeatureDiscussions              string                `db:"feature_discussions" json:"feature_discussions"`
	OptionStoryDiscussionsByDefault bool                  `db:"option_story_discussions_by_default" json:"option_story_discussions_by_default"`
}

type ProfileCustomDomain struct {
	ID            string         `db:"id" json:"id"`
	ProfileID     string         `db:"profile_id" json:"profile_id"`
	Domain        string         `db:"domain" json:"domain"`
	DefaultLocale sql.NullString `db:"default_locale" json:"default_locale"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type ProfileLink struct {
	ID                        string                `db:"id" json:"id"`
	ProfileID                 string                `db:"profile_id" json:"profile_id"`
	Kind                      string                `db:"kind" json:"kind"`
	Order                     int32                 `db:"order" json:"order"`
	IsManaged                 bool                  `db:"is_managed" json:"is_managed"`
	IsVerified                bool                  `db:"is_verified" json:"is_verified"`
	RemoteID                  sql.NullString        `db:"remote_id" json:"remote_id"`
	PublicID                  sql.NullString        `db:"public_id" json:"public_id"`
	URI                       sql.NullString        `db:"uri" json:"uri"`
	AuthProvider              sql.NullString        `db:"auth_provider" json:"auth_provider"`
	AuthAccessTokenScope      sql.NullString        `db:"auth_access_token_scope" json:"auth_access_token_scope"`
	AuthAccessToken           sql.NullString        `db:"auth_access_token" json:"auth_access_token"`
	AuthAccessTokenExpiresAt  sql.NullTime          `db:"auth_access_token_expires_at" json:"auth_access_token_expires_at"`
	AuthRefreshToken          sql.NullString        `db:"auth_refresh_token" json:"auth_refresh_token"`
	AuthRefreshTokenExpiresAt sql.NullTime          `db:"auth_refresh_token_expires_at" json:"auth_refresh_token_expires_at"`
	Properties                pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt                 time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt                 sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt                 sql.NullTime          `db:"deleted_at" json:"deleted_at"`
	Visibility                string                `db:"visibility" json:"visibility"`
	IsFeatured                bool                  `db:"is_featured" json:"is_featured"`
	AddedByProfileID          sql.NullString        `db:"added_by_profile_id" json:"added_by_profile_id"`
}

type ProfileLinkImport struct {
	ID            string                `db:"id" json:"id"`
	ProfileLinkID string                `db:"profile_link_id" json:"profile_link_id"`
	RemoteID      sql.NullString        `db:"remote_id" json:"remote_id"`
	Properties    pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt     time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfileLinkTx struct {
	ProfileLinkID string         `db:"profile_link_id" json:"profile_link_id"`
	LocaleCode    string         `db:"locale_code" json:"locale_code"`
	Title         string         `db:"title" json:"title"`
	Group         sql.NullString `db:"group" json:"group"`
	Description   sql.NullString `db:"description" json:"description"`
	Icon          sql.NullString `db:"icon" json:"icon"`
}

type ProfileMembership struct {
	ID              string                `db:"id" json:"id"`
	ProfileID       string                `db:"profile_id" json:"profile_id"`
	MemberProfileID sql.NullString        `db:"member_profile_id" json:"member_profile_id"`
	Kind            string                `db:"kind" json:"kind"`
	Properties      pqtype.NullRawMessage `db:"properties" json:"properties"`
	StartedAt       sql.NullTime          `db:"started_at" json:"started_at"`
	FinishedAt      sql.NullTime          `db:"finished_at" json:"finished_at"`
	DeletedAt       sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfilePage struct {
	ID               string         `db:"id" json:"id"`
	ProfileID        string         `db:"profile_id" json:"profile_id"`
	Slug             string         `db:"slug" json:"slug"`
	Order            int32          `db:"order" json:"order"`
	CoverPictureURI  sql.NullString `db:"cover_picture_uri" json:"cover_picture_uri"`
	PublishedAt      sql.NullTime   `db:"published_at" json:"published_at"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt        sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	AddedByProfileID sql.NullString `db:"added_by_profile_id" json:"added_by_profile_id"`
	Visibility       string         `db:"visibility" json:"visibility"`
}

type ProfilePageTx struct {
	ProfilePageID string      `db:"profile_page_id" json:"profile_page_id"`
	LocaleCode    string      `db:"locale_code" json:"locale_code"`
	Title         string      `db:"title" json:"title"`
	Summary       string      `db:"summary" json:"summary"`
	Content       string      `db:"content" json:"content"`
	SearchVector  interface{} `db:"search_vector" json:"search_vector"`
}

type ProfilePointPendingAward struct {
	ID              string                `db:"id" json:"id"`
	TargetProfileID string                `db:"target_profile_id" json:"target_profile_id"`
	TriggeringEvent string                `db:"triggering_event" json:"triggering_event"`
	Description     string                `db:"description" json:"description"`
	Amount          int32                 `db:"amount" json:"amount"`
	Status          string                `db:"status" json:"status"`
	ReviewedBy      sql.NullString        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt      sql.NullTime          `db:"reviewed_at" json:"reviewed_at"`
	RejectionReason sql.NullString        `db:"rejection_reason" json:"rejection_reason"`
	Metadata        pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
}

type ProfilePointTransaction struct {
	ID              string         `db:"id" json:"id"`
	TargetProfileID string         `db:"target_profile_id" json:"target_profile_id"`
	OriginProfileID sql.NullString `db:"origin_profile_id" json:"origin_profile_id"`
	TransactionType string         `db:"transaction_type" json:"transaction_type"`
	TriggeringEvent sql.NullString `db:"triggering_event" json:"triggering_event"`
	Description     string         `db:"description" json:"description"`
	Amount          int32          `db:"amount" json:"amount"`
	BalanceAfter    int32          `db:"balance_after" json:"balance_after"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
}

type ProfileQuestion struct {
	ID            string         `db:"id" json:"id"`
	ProfileID     string         `db:"profile_id" json:"profile_id"`
	AuthorUserID  string         `db:"author_user_id" json:"author_user_id"`
	Content       string         `db:"content" json:"content"`
	AnswerContent sql.NullString `db:"answer_content" json:"answer_content"`
	AnswerURI     sql.NullString `db:"answer_uri" json:"answer_uri"`
	AnswerKind    sql.NullString `db:"answer_kind" json:"answer_kind"`
	AnsweredAt    sql.NullTime   `db:"answered_at" json:"answered_at"`
	AnsweredBy    sql.NullString `db:"answered_by" json:"answered_by"`
	IsAnonymous   bool           `db:"is_anonymous" json:"is_anonymous"`
	IsHidden      bool           `db:"is_hidden" json:"is_hidden"`
	VoteCount     int32          `db:"vote_count" json:"vote_count"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type ProfileQuestionVote struct {
	ID         string    `db:"id" json:"id"`
	QuestionID string    `db:"question_id" json:"question_id"`
	UserID     string    `db:"user_id" json:"user_id"`
	Score      int32     `db:"score" json:"score"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type ProfileResource struct {
	ID               string                `db:"id" json:"id"`
	ProfileID        string                `db:"profile_id" json:"profile_id"`
	Kind             string                `db:"kind" json:"kind"`
	IsManaged        bool                  `db:"is_managed" json:"is_managed"`
	RemoteID         sql.NullString        `db:"remote_id" json:"remote_id"`
	PublicID         sql.NullString        `db:"public_id" json:"public_id"`
	URL              sql.NullString        `db:"url" json:"url"`
	Title            string                `db:"title" json:"title"`
	Description      sql.NullString        `db:"description" json:"description"`
	Properties       pqtype.NullRawMessage `db:"properties" json:"properties"`
	AddedByProfileID string                `db:"added_by_profile_id" json:"added_by_profile_id"`
	CreatedAt        time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt        sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type ProfileTx struct {
	ProfileID    string                `db:"profile_id" json:"profile_id"`
	LocaleCode   string                `db:"locale_code" json:"locale_code"`
	Title        string                `db:"title" json:"title"`
	Description  string                `db:"description" json:"description"`
	Properties   pqtype.NullRawMessage `db:"properties" json:"properties"`
	SearchVector interface{}           `db:"search_vector" json:"search_vector"`
}

type ProtectionPowChallenge struct {
	ID         string    `db:"id" json:"id"`
	Prefix     string    `db:"prefix" json:"prefix"`
	Difficulty int16     `db:"difficulty" json:"difficulty"`
	IpHash     string    `db:"ip_hash" json:"ip_hash"`
	Used       bool      `db:"used" json:"used"`
	ExpiresAt  time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type Question struct {
	ID            string         `db:"id" json:"id"`
	UserID        string         `db:"user_id" json:"user_id"`
	ProfileID     sql.NullString `db:"profile_id" json:"profile_id"`
	Content       string         `db:"content" json:"content"`
	IsHidden      bool           `db:"is_hidden" json:"is_hidden"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	AnsweredAt    sql.NullTime   `db:"answered_at" json:"answered_at"`
	AnswerURI     sql.NullString `db:"answer_uri" json:"answer_uri"`
	IsAnonymous   bool           `db:"is_anonymous" json:"is_anonymous"`
	AnswerKind    sql.NullString `db:"answer_kind" json:"answer_kind"`
	AnswerContent sql.NullString `db:"answer_content" json:"answer_content"`
}

type QuestionVote struct {
	ID         string    `db:"id" json:"id"`
	QuestionID string    `db:"question_id" json:"question_id"`
	UserID     string    `db:"user_id" json:"user_id"`
	Score      int32     `db:"score" json:"score"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type RuntimeState struct {
	Key       string    `db:"key" json:"key"`
	Value     string    `db:"value" json:"value"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID                       string         `db:"id" json:"id"`
	Status                   string         `db:"status" json:"status"`
	OauthRequestState        string         `db:"oauth_request_state" json:"oauth_request_state"`
	OauthRequestCodeVerifier string         `db:"oauth_request_code_verifier" json:"oauth_request_code_verifier"`
	OauthRedirectURI         sql.NullString `db:"oauth_redirect_uri" json:"oauth_redirect_uri"`
	LoggedInUserID           sql.NullString `db:"logged_in_user_id" json:"logged_in_user_id"`
	LoggedInAt               sql.NullTime   `db:"logged_in_at" json:"logged_in_at"`
	ExpiresAt                sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt                time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                sql.NullTime   `db:"updated_at" json:"updated_at"`
	LastActivityAt           sql.NullTime   `db:"last_activity_at" json:"last_activity_at"`
	UserAgent                sql.NullString `db:"user_agent" json:"user_agent"`
	OauthProvider            sql.NullString `db:"oauth_provider" json:"oauth_provider"`
	OauthAccessToken         sql.NullString `db:"oauth_access_token" json:"oauth_access_token"`
	OauthTokenScope          sql.NullString `db:"oauth_token_scope" json:"oauth_token_scope"`
}

type SessionPreference struct {
	SessionID string    `db:"session_id" json:"session_id"`
	Key       string    `db:"key" json:"key"`
	Value     string    `db:"value" json:"value"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type SessionRateLimit struct {
	IpHash      string    `db:"ip_hash" json:"ip_hash"`
	Count       int32     `db:"count" json:"count"`
	WindowStart time.Time `db:"window_start" json:"window_start"`
}

type Story struct {
	ID              string                `db:"id" json:"id"`
	AuthorProfileID sql.NullString        `db:"author_profile_id" json:"author_profile_id"`
	Slug            string                `db:"slug" json:"slug"`
	Kind            string                `db:"kind" json:"kind"`
	StoryPictureURI sql.NullString        `db:"story_picture_uri" json:"story_picture_uri"`
	Properties      pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime          `db:"deleted_at" json:"deleted_at"`
	IsManaged       bool                  `db:"is_managed" json:"is_managed"`
	RemoteID        sql.NullString        `db:"remote_id" json:"remote_id"`
	SeriesID        sql.NullString        `db:"series_id" json:"series_id"`
	Visibility      string                `db:"visibility" json:"visibility"`
	FeatDiscussions bool                  `db:"feat_discussions" json:"feat_discussions"`
}

type StoryInteraction struct {
	ID        string       `db:"id" json:"id"`
	StoryID   string       `db:"story_id" json:"story_id"`
	ProfileID string       `db:"profile_id" json:"profile_id"`
	Kind      string       `db:"kind" json:"kind"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type StoryPublication struct {
	ID          string                `db:"id" json:"id"`
	StoryID     string                `db:"story_id" json:"story_id"`
	ProfileID   string                `db:"profile_id" json:"profile_id"`
	Kind        string                `db:"kind" json:"kind"`
	Properties  pqtype.NullRawMessage `db:"properties" json:"properties"`
	CreatedAt   time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime          `db:"deleted_at" json:"deleted_at"`
	IsFeatured  bool                  `db:"is_featured" json:"is_featured"`
	PublishedAt sql.NullTime          `db:"published_at" json:"published_at"`
}

type StorySeries struct {
	ID               string         `db:"id" json:"id"`
	Slug             string         `db:"slug" json:"slug"`
	SeriesPictureURI sql.NullString `db:"series_picture_uri" json:"series_picture_uri"`
	Title            string         `db:"title" json:"title"`
	Description      string         `db:"description" json:"description"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt        sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type StoryTx struct {
	StoryID      string      `db:"story_id" json:"story_id"`
	LocaleCode   string      `db:"locale_code" json:"locale_code"`
	Title        string      `db:"title" json:"title"`
	Summary      string      `db:"summary" json:"summary"`
	Content      string      `db:"content" json:"content"`
	SearchVector interface{} `db:"search_vector" json:"search_vector"`
}

type User struct {
	ID                  string         `db:"id" json:"id"`
	Kind                string         `db:"kind" json:"kind"`
	Name                string         `db:"name" json:"name"`
	Email               sql.NullString `db:"email" json:"email"`
	Phone               sql.NullString `db:"phone" json:"phone"`
	GithubHandle        sql.NullString `db:"github_handle" json:"github_handle"`
	GithubRemoteID      sql.NullString `db:"github_remote_id" json:"github_remote_id"`
	BskyHandle          sql.NullString `db:"bsky_handle" json:"bsky_handle"`
	BskyRemoteID        sql.NullString `db:"bsky_remote_id" json:"bsky_remote_id"`
	XHandle             sql.NullString `db:"x_handle" json:"x_handle"`
	XRemoteID           sql.NullString `db:"x_remote_id" json:"x_remote_id"`
	IndividualProfileID sql.NullString `db:"individual_profile_id" json:"individual_profile_id"`
	CreatedAt           time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}
