package telegram

import "time"

// TelegramVerificationCode represents a pending verification code for account connection.
// Generated by the bot when a user sends /start, consumed by the web UI verify-code endpoint.
type TelegramVerificationCode struct {
	ID               string
	Code             string
	TelegramUserID   int64
	TelegramUsername string
	CreatedAt        time.Time
	ExpiresAt        time.Time
	ConsumedAt       *time.Time
}

// TelegramGroupInviteCode represents a short-lived code generated by the bot
// when a lead types /invite in a group chat. The code is DM'd to the lead,
// who then pastes it in the AYA UI to create an envelope (invitation).
type TelegramGroupInviteCode struct {
	ID                      string
	Code                    string
	TelegramChatID          int64
	TelegramChatTitle       string
	CreatedByTelegramUserID int64
	CreatedAt               time.Time
	ExpiresAt               time.Time
	ConsumedAt              *time.Time
}

// LinkResult contains the result of a successful account linking.
type LinkResult struct {
	ProfileID        string
	ProfileSlug      string
	TelegramUserID   int64
	TelegramUsername string
}

// ProfileLinkInfo represents a linked Telegram account.
type ProfileLinkInfo struct {
	ID        string
	ProfileID string
	RemoteID  string
	PublicID  string
}

// RawGroupTelegramLink is an intermediate type returned from the repository,
// before visibility filtering is applied in the service layer.
type RawGroupTelegramLink struct {
	ProfileSlug    string
	ProfileTitle   string
	MembershipKind string
	LinkTitle      string
	LinkURI        string
	LinkPublicID   string
	LinkVisibility string
}

// GroupTelegramLink represents a Telegram link from a group profile visible to the user.
type GroupTelegramLink struct {
	ProfileSlug  string
	ProfileTitle string
	LinkTitle    string
	LinkURI      string
	LinkPublicID string
}

// CreateProfileLinkParams contains parameters for creating a telegram profile link.
type CreateProfileLinkParams struct {
	ID               string
	ProfileID        string
	RemoteID         string // Telegram user ID as string
	PublicID         string // Telegram username
	URI              string // https://t.me/<username>
	Order            int
	AddedByProfileID string
}
